nanocurrency/nano-node

- CMakeLists.txt
If you don't do that you need to specify -DBOOST_LOG_DYN_LINK or it won't link under linux
> Force building with static boost (like the pre-built versions)

- rai/qt/qt.cpp
Adds the block count to the status bar (with a tool tip to explain what it means), might make it easier for new users and people trying to support them getting their wallet running. Following up #60
> Status block

- rai/qt/qt.cpp
Fix for #87 - simple if clause which checks new_password->text () is empty, if empty then tells user and doesn't allow empty password to be set.
> Empty password

- rai/node/rpc.cpp
- rai/node/rpc.hpp
Will be useful if someone send less than threshold, but cumulative > threshold. Such as 99 + 99 > 100 and cannot be received by current exchanges
> RPC receive

- rai/qt/qt.cpp
- rai/qt/qt.hpp
Warnings for backup/import Seed with locked wallet
Tooltips for several buttons
Balance in account viewer
> GUI: seed warnings, several tooltips, balance in Account viewer

- rai/core_test/rpc.cpp
- rai/node/rpc.cpp
- rai/node/rpc.hpp
+ pending, accounts_pending to accept "threshold" parameter
+ **wallet_pending**
+ **pending_exists** (to check if transaction is completed with receive)
+ **search_pending_all** (to search pending for all wallets)
+ **receive_minimum, receive_minimum_set** (to change receive_minimum without node restart)
+ republish to accept "sources" parameter (depth of rebroadcast for receive/open source chains)
+ **wallet_republish** (to rebroadcast last blocks from all wallet accounts)
+ **work_get, work_set, wallet_work_get** (https://github.com/clemahieu/raiblocks/issues/95)
> RPC extended

- rai/core_test/rpc.cpp
- rai/node/rpc.cpp
- rai/node/rpc.hpp
+ **delegators, delegators_count** (named account as representative; should be helpful for web explorer)
+ **account_info** (open block, change representative block, last modified timestamp for account)
+ **blocks_info** (extended "blocks" with amount & block account; should be helpful for web wallet)
+ **work_peer_add, work_peers, work_peers_clear** (to manage work_peers without restart)
> RPC extended (part 2)

- rai/node/rpc.cpp
- rai/node/rpc.hpp
**block_count_type** returns number of send, receive, open & change blocks
**unchecked** returns unchecked hash+block up to "count"
**unchecked_keys** returns unchecked DB key, hash & block countent startinh from "key" up to "count"
**unchecked_clear** cleans all unchecked blocks
**unchecked_get** to retrieve unchecked block by hash
> RPC block_count_type, unchecked, unchecked_get, unchecked_keys, unchecked_clear

- CMakeLists.txt
Samples are: bulding at Ubuntu 16.04 for CentOS, building at CPU with AVX2 (Haswell+) for older architectures etc.
> Returning optional custom Crypto++ for old OS & CPU building

- rai/qt_test/qt.cpp
This change makes the test failures much less likely.
> qt_test: each test gets its own event_processor

- rai/node/node.cpp
While toying around with the command-line client found some unreadable help messages due to missing newlines. Figured this was too minor for a bounty ;-)
> Make some command-line help messages readable by adding newlines

- rai/node/node.cpp
The block_processor_thread resource is not properly joined or detached when a node object goes out of scope causing a terminate exception
> Add destruction of node resources to destructor

- ci/build.sh
Many tests in core_test operate under the assumption that genesis and other account data is populated with testnet values. This means core_test requires being built targeting the testnet. Whether or not this may cause coverage issues I don't know.
> switch CI to use testnet

- rai/core_test/rpc.cpp
- rai/node/rpc.cpp
This allows cross-origin requests in a sandboxed environment sending [CORS-safelisted request headers](https://developer.mozilla.org/en-US/docs/Glossary/Simple_header) such as  `Content-Type`.
More headers can be allowed in the future or we can echo back the request's `Access-Control-Request-Headers` if it exists, but this is a start.
Allowing any header using `*` is not well supported.
See: https://stackoverflow.com/a/13147554
> Add Access-Control-Allow-Headers to RPC responses

- rai/node/openclwork.hpp
openclwork.cpp:570:13: warning: ‘_cl_command_queue*
clCreateCommandQueue(cl_context, cl_device_id,
cl_command_queue_properties, cl_int*)’ is deprecated
[-Wdeprecated-declarations]
queue = clCreateCommandQueue (context, selected_devices [0], 0,
&queue_error);
> Supressing openclwork.cpp deprecation warnings

- rai/qt/qt.cpp
I noticed someone on Reddit or Bitcointalk forgetting to store the wallet seed somewhere after using the button that copies it to the user clipboard. I think this simple textual change makes it more clear that simply clicking the button does not yet perform the back-up, people have to store the wallet seed somewhere safely.
> improve button text for copying wallet seed to clipboard

- rai/qt/qt.cpp
Just some minor QT Stylesheet additions to make the wallet app a little easier on the eyes, without straying from that native look.
> add padding to text fields, make headings bold

- Dockerfile
This automatically creates a container volume for the database and log files. Using a data volume greatly enhances performance since the database would otherwise be stored within the container's layered filesystem(which is an anti pattern).
By default this creates the volume on the host's filesystem on the first container start. Using Docker's volume opens possibilities for many types of storage options. See Docker's volume [documentation](https://docs.docker.com/engine/admin/volumes/) for more details.
No need to manually specify the "docker run -v /foo:/bar" parameter anymore.
cc @zjeraar
> Add docker data volume

- rai/qt/qt.cpp
- rai/qt/qt.hpp
This pull request combines the "Lock" and "Unlock" button into a single button which is toggled depending on the lock state.
Additionally, it will disable the password field when the wallet is unlocked. 
Unlocked wallet:
Locked wallet:
This fixes #237, #279, #288
> combine lock & unlock button into a single button + password field

- rai/qt/qt.cpp
- rai/qt/qt.hpp
This PR switches the multi-line QLabel for a single line read-only QLineEdit so that the user can only ever select their entire wallet address. This also plays a little nicer when resizing the wallet to a larger size (increasing the window width).
Improves #367 
Or, when the window size is increased.
Additionally, this adds visual feedback after the "Copy" button is pressed by temporarily changing the button text to "Copied".
> use readonly QLineEdit for wallet address

- rai/qt/qt.cpp
- rai/qt_test/qt.cpp
Following up on #311, this pull request sets the proper initial state for the toggle button for new wallets. It also updates `qt_test` to take the new flow into account.
I'm quite new to C so please let me know if there's anything that can be improved upon here.
> Update wallet.enter_password test for lock toggle button

- rai/qt/qt.cpp
Stretches the last section (column) of each QTableView instance so that the entire table width is always utilized.
> stretch last column of all tableview instances (so table uses entire avail. width)

- rai/node/common.hpp
I checked older versions, and it seems that this has never been used. Maybe the intention was to reuse bulk_pull for range queries (which @clemahieu has mentioned as a need - and which would require a count -  but new messages types are probably more appropriate)
> Remove unused count field from bulk_pull.

- rai/node/node.cpp
This is required for some servers to properly parse the request.
> Set callback Content-Type to application/json

- CMakeLists.txt
- rai/secure.cpp
~~Observes the CMake BUILD_SHARED_LIBS variable when building rai_lib.~~
~~See: https://cmake.org/cmake/help/v3.0/variable/BUILD_SHARED_LIBS.html#variable:BUILD_SHARED_LIBS~~
**Edit:** I've updated the build definition to continue to build all executables static and build our separate `rai_lib` shared library.
> Allow static build of rai_node

- rai/core_test/node.cpp
- rai/core_test/wallet.cpp
- rai/lib/blocks.cpp
- rai/node/node.cpp
- rai/node/wallet.cpp
- rai/node/wallet.hpp
The rekey() operation writes to memory and to LMDB, but the visibility of the two operations is totally different, leading to a number of race conditions.
I had another version of this patch that made the visibility of the password match that of the LMDB transaction through a new transaction finalizer concept, and a transaction read barrier, but it was much more complex. This version just duplicates the wallet key in memory, where visibility can be serialized with the password.
> Fix wallet race condition.

- rai/core_test/node.cpp
- rai/node/node.cpp
- rai/node/node.hpp
- rai/qt/qt.cpp
- rai/secure.cpp
- rai/secure.hpp
This fixes an issue where pending balances won't show up until the user triggers a UI refresh some other way.
> Add balance observer.

- rai/core_test/node.cpp
- rai/core_test/rpc.cpp
Fixes 2/3 of the unstable tests for #456. However, `bootstrap_processor.push_diamond` looks like it might be an actual failure.
> Fix node.fork_no_vote_quorum and rpc.account_info tests

- rai/qt/qt.cpp
- Right-align the balances in history.
- Make the balance text consistent when viewing other accounts.
> Tweak wallet balance display.

- rai/core_test/node.cpp
- rai/core_test/rpc.cpp
- rai/core_test/wallets.cpp
- rai/node/node.cpp
- rai/node/node.hpp
- rai/node/rpc.cpp
- rai/node/utility.cpp
- rai/node/utility.hpp
- rai/node/wallet.cpp
- rai/secure.cpp
- rai/secure.hpp
This fixes a problem encountered by some users with many wallets, where the node would crash or behave incorrectly when creating additional wallets. The underlying cause is the max db limit in LMDB (plus a mistake in the wallet store), which is hardcoded to 128. @clemahieu suggested we make it a config param.  
Also fixes the RPC endpoint to correctly report wallet creation failed.
> Fix wallet creation crash, add lmdb_max_dbs config.

- README.md
This pulls from a few other popular cryptocurrency README's by adding a **Resources** section with links to the various available resources, like the Discord chat or the RaiBlocks forum. 
I had several people ask me for instructions on how to run a node so I've added in several links to the wiki, since that's where the bulk of this information can be found right now.
> add resource links to readme

- rai/core_test/wallet.cpp
- rai/lib/blocks.cpp
- rai/node/node.cpp
- rai/node/node.hpp
- rai/node/wallet.cpp
This PR introduces a --vacuum feature on rai_node / rai_wallet.
Test case, 13GB wallet on a fast SSD:
* Vacuuming took about 3 minutes
* Size after vacuum: 5GB
Since lmdb doesn't offer inline vacuuming, the vacuuming dumps live mdb pages to a copy of the db, which is finally replaced by the compacted db.
A general question about the code base: There doesn't seem to be a good place for shared constants (such as strings) in the various subprojects. Should we introduce some sort of `constants.hpp`? Sprinkling copies of string constants like "data.ldb" around is brittle and hard to maintain.
> Vacuum feature

- rai/node/node.cpp
- rai/rai_node/entry.cpp
I've been trying to convince clang-format to nicely format the program options, but it seems to have no knobs for tuning builder-style statements (other than ColumnLimit, which doesn't suffice.)
Options currently end up on a long line, making it hard to read and edit. Any concurrent program option edits are going to conflict.
With this patch I basically ask if using `// clang-format off` is okay for these special cases.
This may close https://github.com/clemahieu/raiblocks/issues/416
> Override clang format for program options

- CMakeLists.txt
- FindBoost.cmake
Adds CMake option BOOST_CUSTOM to inline FindBoost.cmake allowing for detection of Boost 1.66 built from source on Windows and Linux. Would be interested to see if it works on Mac as well and if the option could be removed all together
> CMake and Boost 1.66

- rai/core_test/rpc.cpp
Not sure why it was disabled, but it passes consistently on my machine. It takes about 1 second, which I don't think is too long.
> Re-enable payment_wait test

- rai/core_test/message_parser.cpp
- rai/node/bootstrap.cpp
- rai/node/bootstrap.hpp
- rai/node/common.cpp
- rai/node/common.hpp
- rai/node/node.cpp
This patchset adds a new message type "bulk_pull_blocks" (0x09) which allows one to request from a
node a range of blocks (min_hash to max_hash).  Alternatively, the checksum for a range of blocks can
be requested to  determine if it is likely that there are new blocks in that range that need to be pulled.
Further, a limited number of blocks can be requested by specifying a non-zero "max_count" argument.
> Add a new message type "bulk_pull_blocks"

- rai/node/common.cpp
This PR is a request for discussion regarding deep nesting more than anything else. These pyramids appear a few places.
I find the short-circuit idiom easier to read, and it nicely mirrors the corresponding `write_header` function.
`read_header` was low-hanging fruit (and I assume it's already covered by tests, seems to work fine)
> Replace deep nesting with result short-circuit idiom

- rai/node/bootstrap.cpp
- rai/node/bootstrap.hpp
- rai/node/node.cpp
- rai/node/node.hpp
Blocks that go into unchecked lose the callback that triggers fork handling. This patch triggers
it directly, instead of relying on the callback.
> Apply bootstrap fork handling uniformly.

- rai/qt/qt.cpp
Most of the timers aren't ideal, the UI should be reacting to specific events... but that's a bigger job.
This should stop QT asserting and its a bit more thread safe.
> Use QTimers in head code. Fixes #503

- ci/bootstrap_boost.sh
Also add -p for mkdir for when first run of the script fails.
> Fix ci/bootstrap_boost.sh to rm what's intended

- rai/node/bootstrap.cpp
if connection_shared is expired
> Preventing possible requeue_pull loop

- rai/node/bootstrap.cpp
- rai/node/bootstrap.hpp
- rai/node/node.cpp
This patch reduces initial bootstrap times by searching for higher-performing peers, and improves the overall behavior when the number of bootstrap peers is high.
I recommend setting "bootstrap_connections" to 32, 64 or 128 in the config to test.
> Improve bootstrap performance.

- rai/core_test/block_store.cpp
- rai/core_test/gap_cache.cpp
- rai/core_test/ledger.cpp
- rai/core_test/network.cpp
- rai/core_test/peer_container.cpp
- rai/core_test/processor_service.cpp
- rai/core_test/rpc.cpp
- rai/node/bootstrap.cpp
- rai/node/bootstrap.hpp
- rai/node/common.hpp
- rai/node/node.cpp
- rai/node/node.hpp
- rai/node/rpc.cpp
- rai/node/testing.cpp
- rai/node/testing.hpp
- rai/node/wallet.cpp
- rai/qt/qt.cpp
- rai/qt_test/qt.cpp
- rai/secure.cpp
- rai/secure.hpp
- rai/slow_test/node.cpp
This PR deals with time:
* There were two different seconds-since-epoch implementations, one using std::chrono, the other using boost::posix_time. I've factored out the chrono approach into common.hpp and updated all call sites to use that one (both approaches produced the same result)
* Using `system_clock` for measuring durations is problematic, since the system clock may jump (for instance when NTP kicks in, or DST transitions). `steady_clock` is thus used instead.
* Removed an ostream `operator<<` taking a system_clock which was never used.
I don't think any of the code depends on wall time (except seconds_since_epoch), but please verify this.
> Use steady_clock and clean up epoch-time use

- rai/node/node.cpp
- rai/node/node.hpp
Logging currently flushes every single log record to disk. While nice for diagnosing crashes, this is very very slow, even on my ssd. In one io completion handler I measured, a third of the time was spent logging, and most of that was flushing.
This PR proposes a new logging config flag called `"flush"`. I've kept the conservative default of true, so nothing changes until you set it to false. 
I do think it should be default false in the future, as people can always flip the switch to diagnose crashes. Or should I make default false already now?
If this is merged, the config wiki needs to be updated.
> Make slow log flushing optional

- ci/test.sh
- Reduce timeouts to 7 mins
- Enable timeout for load test
> [CI config] Reduce per-test timeouts

- rai/node/bootstrap.cpp
This patch introduces a hardcoded checkpoint on the number of frontiers a node should know about before we pull based on the frontiers it provides. This number should monotonically increase with node releases.
There are many stuck nodes with 8000-2M checked blocks in the network, and it's both a waste of time and a potential source of unresolvable forks to pull from them.
This is the smallest of 4 changes to get 100% reliable bootstrapping from zero in ~30 minutes.
Note: This isn't meant to and will not help with any kind of bootstrap poisoning attack, it simply helps with a real problem on the live network.
> Avoid bootstrapping from stuck nodes.

- rai/core_test/node.cpp
- rai/node/bootstrap.cpp
- rai/node/bootstrap.hpp
- rai/node/node.cpp
- rai/node/node.hpp
This patch adds a new config setting "bootstrap_max_connections", which solves two problems:
a) There's no need to spin up 64 connections when doing the usual nearly-synced 30-50 frontier bootstraps the node does all the time.
a) "bootstrap_connections" can remain at 4, or whatever the user previously had set. They will benefit from the new default value of "bootstrap_max_connections" regardless of whether they change their config.
> Scale bootstrap connections based on load.

- rai/lib/blocks.cpp
- rai/lib/interface.cpp
- rai/lib/numbers.cpp
- rai/lib/work.cpp
- rai/node/node.cpp
- rai/secure.cpp
- rai/versioning.cpp
A very boring renaming patch. People seem to trip up on false-is-success, etc, so more descriptive names may help. @androm3da we talked about this one. I picked *error* instead of *failure*, since *error* is already used in quite a few places.
I'll do another round for the node subdir later on.
> Rename result to more descriptive names

- rai/node/openclwork.cpp
The blake2b state buffer is 128 bytes long, not 256.
> Fix OpenCL printstate

- docker/node/Dockerfile
- docker/node/config.json
- docker/node/entry.sh
Don't try and copy .so as rai_node is static.
Put default json config in docker.
Add entry point for cmd
Clean up the dockerfile to have fewer build steps
This should fix #502 but will need to change the wiki once it's in and the new docker image is published.
> Clean up and fix docker

- rai/core_test/ledger.cpp
- rai/node/node.cpp
- rai/node/rpc.cpp
- rai/secure.cpp
- rai/secure.hpp
If a send block has a higher balance than the previous, then it's trying to spend a negative amount, not spend more than it has.
> process_result::overspend -> process_result::negative_spend

- rai/node/wallet.cpp
Instead of public key of source account
> Correct hashes in logs for pending blocks

- rai/core_test/node.cpp
- rai/node/bootstrap.cpp
- rai/node/bootstrap.hpp
- rai/node/node.cpp
- rai/node/node.hpp
- rai/node/wallet.cpp
This patch adds unresolved fork tracking to the bootstrapper. It will continue to try to resolve the forked blocks until it succeeds, or the bootstrap finishes (likely stalled if there are any unresolved forks).
A single unresolved fork can mean the bootstrap will stall with a few million unchecked blocks.
> Force resolution of forks during bootstrap.

- rai/secure.cpp
Resolves #598, resolves #602.
A block's dependency (`previous` or `source`) was being added to the ledger after the hash2 was calculated, which caused the assert to fail. This fixes the problem.
> Fix ledger processor hash2 race condition

- rai/secure.cpp
Now it matches the other block types. I think this might have also been part of #598, as I got a different segfault after running it for a while.
> Fix ledger_processor::change_block block_put

- rai/core_test/rpc.cpp
- rai/node/rpc.cpp
- rai/node/wallet.cpp
- rai/node/wallet.hpp
Probably needs some more discussion.
Note that currently, send IDs are per wallet. If we decide to keep that behavior, it should be documented.
> Add RPC send ID for idempotency

- Info.plist
When ran on macOS, the App name (in the top left of the screen) still says 'Raiblocks'. This patch changes that to 'Nano'.
> Update macOS BundleName

- rai/node/bootstrap.cpp
The bootstrap rep weights make it easy to resolve forks, so we don’t need to avoid unsynced clients.
> Get rid of the frontier minimum, not needed anymore.

- CMakeLists.txt
to fix https://github.com/nanocurrency/raiblocks/issues/636
> Compatibility with Cmake 2.8 (CentOS 7)

- rai/node/node.cpp
- rai/node/wallet.cpp
- rai/node/wallet.hpp
- rai/qt/qt.cpp
Currently, only seed import from the Qt wallet creates an account. When using --wallet_change_seed, the wallet would display the wrong address until the user manually created accounts.
Node and wallet refactored to share seed-change code.
> Fixes --wallet_change_seed to add account

- CMakeLists.txt
- rai/node/rpc.cpp
- rai/node/rpc.hpp
- rai/node/rpc_secure.cpp
- rai/node/rpc_secure.hpp
- rai/rai_node/daemon.cpp
- rai/rai_wallet/entry.cpp
This PR implements HTTPS (TLS) support for RPC, along with optional client certificate verification. To build with TLS support, flip the RAIBLOCKS_SECURE_RPC cmake cache variable.
A reviewer might want to read https://github.com/cryptocode/notes/wiki/RPC-TLS
Note that this implementation does not cover callbacks (which I assume are mostly local anyway), but https client calls can be implemented if needed in a separate PR.
I've only tested on macOS, so I hope someone can build and test on Linux and Windows, after which we probably want openssl/libressl builds in CI.
> TLS support for RPC

- .travis.yml
- ci/deploy-docker.sh
Now, the docker tag `latest` (the default) will refer to the latest commit tagged in git (effectively the latest release).
You can see a test run of this on my fork here: https://travis-ci.org/PlasmaPower/raiblocks/builds/345122239
> Properly version (tag) docker images

- rai/core_test/node.cpp
Failing tests, to be investigated:
- node - send_single_many_peers
- node - fork_bootstrap_flip
- node - bootstrap_no_publish
> Disable failing tests

- rai/qt/qt.cpp
Currently the "Utx" type is useless as it doesn't tell you if it's a send or receive.
> Change ublocks UI display to match old blocks

- rai/blockstore.cpp
- rai/blockstore.hpp
- rai/common.cpp
Removes `root_visitor` and `block_dependencies`. Both would not support ublocks and are unused.
> Remove unused code

- rai/ledger.cpp
`bock_successor_clear` relies on the block existing.
> Fix ublocks open rollback

- docker/ci/Dockerfile
- docker/node/Dockerfile
The old one is now redirecting to an HTML page, causing the build to fail.
> Fix docker boost url

- rai/core_test/ledger.cpp
- rai/ledger.cpp
- rai/ledger.hpp
- rai/node/node.cpp
- rai/node/rpc.cpp
- rai/qt/qt.cpp
Adds `ledger.block_destination (transaction, block)` and `ledger.block_source (transaction, block)`. Also uses them where old code assumed non-utx blocks.
> Add ledger functions for ublock compatible info

- rai/core_test/ledger.cpp
Just fixes a minor whitespace problem so Travis is happy.
> Ublocks clang format

- rai/core_test/message_parser.cpp
- rai/node/common.cpp
- rai/node/common.hpp
- rai/node/node.cpp
Communicates errors from message_parser to the node more precisely so errors can be logged.
> Improved error handling in message parser

- ci/bootstrap_boost.sh
There were a few things the "bootstrap_boost.sh" script did not do well, this cleans them up.  This includes checking the checksum of the downloaded tarball, allowing for a minimal build of Boost, and cleanup some incorrect bash options.
> Build of Boost Cleanup

- rai/node/node.cpp
- rai/node/node.hpp
Addressing issue if search_pending was performed without discovered representatives
> Broadcasting active elections blocks to discovered representatives

- rai/common.hpp
- rai/core_test/node.cpp
- rai/ledger.cpp
- rai/node/node.cpp
- rai/node/node.hpp
- rai/node/rpc.cpp
- rai/qt/qt.cpp
As part of this, refactors `node.observers.blocks` to use a `process_return` instead of `account` + `amount`.
> Add is_send to utx block callbacks

- rai/lib/blocks.cpp
Fixes #734 
I chose to have `link` be hex, because that's the more direct representation. It's encoded as an account in `link_as_account`. I chose that name to clarify that it's the same field, just a different representation.
This PR also allows for `link` being hex in `process` calls and such, since it's now returned that way from `block_create`.
> Serialize ublock link as both hex and account

- rai/blockstore.cpp
See  https://github.com/nanocurrency/raiblocks/issues/751
> Remove assert that triggers when burn address is set as representative.

- rai/node/rpc.cpp
Rationale: for 100+ accounts at once even fastest GPU can't handle it
> Disable work generation by default for mass creation of accounts

- rai/node/node.cpp
- rai/node/wallet.cpp
I measured tx times, and e.g. gap_cache::vote was open for ~30s, probably due to the mutex being locked.
> Reorder lock/transaction to start tx only after successful lock

- rai/node/testing.cpp
- rai/node/utility.cpp
- rai/node/utility.hpp
My RaiBlocksTest directory has accumulated tens of thousands of tmp directories and files, totaling 1GB+. Each test run produce hundreds of files using `rai::unique_path`
This PR removes any tmpdirs and lockfiles produced by a test (in the `system` destructor)
The same way you can use environment variables to pick tests (GTEST_FILTER), you can use an environment variable (TEST_KEEP_TMPDIRS=1) to retain the directories, e.g. to view log files when there are test failures.
> Prevent tests from accumulating thousands of files and directories

- rai/blockstore.cpp
- rai/core_test/network.cpp
- rai/core_test/node.cpp
- rai/core_test/wallet.cpp
- rai/node/bootstrap.cpp
- rai/node/rpc.cpp
- rai/node/wallet.cpp
- rai/qt/qt.cpp
- rai/rai_node/entry.cpp
Removed some unused captures and locals, and constructor initialization list reordering to match field order.
> Silence some compiler warnings

- rai/common.hpp
- rai/core_test/conflicts.cpp
- rai/node/bootstrap.cpp
- rai/node/common.cpp
There's no "protocol_version_max" since "max" and "using" are always the same in the reference node.
> Protocol version constants

- rai/core_test/peer_container.cpp
- rai/node/bootstrap.cpp
- rai/node/node.cpp
- rai/node/node.hpp
This does a two things for elections while bootstrapping:
- Space out the initial `confirm_req`s to reduce packet loss
- Retry `confirm_req`s for big reps if we don't get a response
This also makes rep_crawler more aggressive, so that we have more reps to `confirm_req`.
> Make elections when bootstrapping more resilient

- rai/ledger.cpp
Right now it's `2^128 - amount`.
> Fix state block send callback amount to not be inverted

- rai/node/bootstrap.cpp
- rai/node/node.cpp
- rai/node/rpc.cpp
BOOST_LOG: 
* argument indexing (bug- and ordering fixes)
* wording and more consistent punctuation before error messages to simplify parsing by log monitoring software.
> Logging improvements

- rai/node/rpc.cpp
Fetching account balance & previous for send blocks if aren't given directly
Double check current balance if previous block is specified (as some users can acidentally mess it)
Account field is not required for state blocks as it has private/public key
If there is no link in request for state blocks use source or destination
> Minor RPC block_create changes

- rai/core_test/rpc.cpp
"previous" field can be auto-filled now
> Fixing RPC block_create test

- rai/core_test/rpc.cpp
This gives accurate gtest assert errors instead of ptree exceptions when tests fail on those lines.
I've avoided one case since https://github.com/nanocurrency/raiblocks/pull/814 removes that line anyway (and which fixes the failing block_create test)
> Use default values when getting success/error ptree nodes

- rai/blockstore.hpp
- rai/common.hpp
Some comments were outdated/wrong. The qualified type references in docs allows for navigation in resulting html.
> Correct mdb table comments with Doxygen conversion

- rai/node/rpc.cpp
> Allow zero balance in block_create for state block sends

- rai/node/rpc.cpp
> Fixed 'account' field for state send subtype in 'account_history' RPC call

- CMakeLists.txt
- rai/core_test/block_store.cpp
- rai/core_test/ledger.cpp
- rai/core_test/network.cpp
- rai/core_test/node.cpp
- rai/core_test/processor_service.cpp
- rai/ledger.cpp
- rai/ledger.hpp
- rai/node/bootstrap.cpp
- rai/node/node.cpp
- rai/node/node.hpp
- rai/node/rpc.cpp
- rai/node/rpc.hpp
- rai/node/stats.cpp
- rai/node/stats.hpp
- rai/qt_test/qt.cpp
- rai/slow_test/node.cpp
This PR proposes an internal API for counting and sampling.
Docs here: https://github.com/cryptocode/raiblocks/wiki/Statistics-API
This is just a start - a lot more can be counted, but it's already enough to get some interesting numbers (example: bootstrap initiation is probably called too often)
> Statistics support

- rai/lib/blocks.cpp
dynamic_cast's as used in block comparisons show up in the profiler in a significant way, and it's probably even worse on msvc (which lowers to a mess of string comparisons)
This converts the dyncasts to type()-check + static_cast, which doesn't show up in the profiler at all.
Dynamic casts are used elsewhere too, but in less perf' critical paths, so they can be dealt with later.
> Convert dynamic casts to static casts

- rai/node/node.cpp
if logging.max_size > default value
> Prevent log deletion by inactive_node

- rai/node/node.cpp
Only consequence in release mode was a missed log entry and occasional asserts while developing.
> Fix inverted check in scan_receivable causing spurious asserts

- rai/core_test/conflicts.cpp
- rai/core_test/ledger.cpp
- rai/core_test/network.cpp
- rai/core_test/node.cpp
- rai/node/bootstrap.cpp
- rai/node/node.cpp
- rai/node/node.hpp
- rai/node/wallet.cpp
Rep votes don't need to be computed during election construction since they're always computed before broadcasting the winner.
Removing unused transaction parameters in election and active_transactions.
> Removing tx dependency

- rai/qt/qt.cpp
- rai/qt/qt.hpp
Since we have stats we might as well show them (not everyone runs with RPC on). 
meltingice on Discord and possibly others are looking into graphing these stats on their web frontends, so I won't bother doing any Qt graphs for this.
> Statistics pane under Advanced in Qt wallet

- rai/node/rpc.cpp
To make the pregeneration of work using multiple work peers easier I added the use_peers option to generate_work. With this light wallets (for example) can easily switch their node to use the multiple work peers configured in the node instead of having to query each work-node.
I added this as rpc parameter instead of a config option as proposed in #855 to not change the RPC behaviour if the config is changed.
I think this PR is pretty interesting for Canoe and Nanovault which both use work_generate to pregenerate the work and thought about adding multiple work peers. Also the default behaviour (not using work peers with that rpc) was pretty unexpected for multiple people I told about this.
> optional use_peers param to generate_work rpc

- rai/node/wallet.cpp
Invert loop iteration since the number of accounts in the wallet is likely smaller than the number of pending entries.
Automatic block confirmation already checks if the destination is in a local wallet so we don't need to re-implement this.
Re-searching the pending table for source blocks for the confirmed account can be better implemented in the future with an account dirty flag or queued block insertion.
Since we don't need a callback after confirmation we don't need the search code in its own class.
> Simplify and improve performance of search_pending.

- doxygen.config
For now, pushing docs to https://nanoapi.github.io/doxygen
> Rename Doxygen name to Nano

- rai/common.hpp
- rai/core_test/ledger.cpp
- rai/core_test/node.cpp
- rai/core_test/wallet.cpp
- rai/ledger.cpp
- rai/ledger.hpp
- rai/node/node.cpp
- rai/node/rpc.cpp
- rai/node/wallet.cpp
- rai/slow_test/node.cpp
Stateblocks are now being parsed and generated, Canary blocks no longer matter since only nodes that understand them are still on the network
> Stateblock Canary Check Cleanup

- rai/qt/qt.cpp
A few people have been confused by "Bad block hash" and messages like that, and it turns out the block hash copied from block explorers or whatnot contains a trailing space.
> Trim whitespaces in certain input fields in Qt wallet

- rai/node/utility.cpp
128GB mapsize is sufficient to maintain node performance and allow lower end devices to operate. The existing 1TB mapsize requirement that is present in the current release prevents widespread node adoption.
> Support lower end devices

- rai/ledger.cpp
Currently counted as legacy blocks as well, which gives a bogus total count. If we want to discriminate between open/send/receive/change, we can add specific state block stats later on.
> Don't count state blocks twice in stats

- rai/node/rpc.cpp
> RPC wallet_change_seed functionality should match CLI

- rai/node/wallet.cpp
So only owner can read and update the backup. https://github.com/nanocurrency/raiblocks/issues/928.
> Set permissions on backup files 

- rai/lib/utility.hpp
- rai/lib/work.cpp
- rai/node/node.cpp
- rai/node/stats.cpp
I didn't see any downsides in converting observer_set's call operator into a `notify` function. It helps finding call sites (IDE's generally suck at finding operator usage), as well as making the call sites a bit clearer to readers IMO.
> Replace call operator with notify function

- CMakeLists.txt
Without this when compiling rai_node on fedora 28 I get many undefined references starting with:
```
[ 68%] Linking CXX executable rai_node
/usr/lib/gcc/x86_64-redhat-linux/8/../../../../lib64/libboost_log_setup.a(init_from_settings.o): Funktiossa ”boost::log::v2s_mt_posix::(anonymous namespace)::default_syslog_sink_factory<char>::create_sink(boost::log::v2s_mt_posix::basic_settings_section<char> const&)”:
(.text+0x1b72): määrittelemätön viite kohteeseen ”boost::log::v2s_mt_posix::sinks::syslog_backend::set_severity_mapper(boost::log::v2s_mt_posix::aux::light_function<boost::log::v2s_mt_posix::sinks::syslog::level (boost::log::v2s_mt_posix::record_view const&)> const&)”
```
> Move boost_log_setup before boost_regex when linking

- .travis.yml
- CMakeLists.txt
- ci/build-travis.sh
- ci/deploy-docker.sh
- ci/test.sh
These changes make the compilation on travis faster, with ~36 minutes as reference, it takes about ~20 minutes with cold caches and ~10 minutes with warm caches.
Summary of changes:
* Enable build caches: ccache and cargo, this requires two slightly different approaches because the linux build runs inside a docker container. The solution on osx is just enabling the caches as explained in the travis documentation, the solution for linux maps a few folders from the docker container to the host to be able to store the cache. ccache is enabled through a cmake 3.4 feature, thus the change in the required version.
* Enable homebrew cache: it does not avoid the compilation but speeds up the download.
* Reduce tests timeout from 420 to 120. One of the tests hangs and was slowing down the build …
> Speed up travis builds: enable ccache, cache cargo and reduce test timeouts

- rai/common.cpp
The previous value does not exceed the threshold of 0xffffffc000000000 and is therefore invalid.
> Fix the work value of the beta network genesis block

- rai/node/wallet.cpp
Boost will now round down to `2^32 - 1` instead of just ignoring the marker bit (`2^32`). This fixes it to properly ignore the marker bit in all boost versions.
> Fix deterministic wallet keys in boost 1.67 or above

- rai/node/rpc.cpp
- rai/node/rpc.hpp
- rai/node/rpc_secure.cpp
For easier debugging with many RPC calls
Now ID is logged only on RPC completion
> Log ID for each RPC call

- rai/blockstore.cpp
- rai/blockstore.hpp
- rai/common.cpp
- rai/common.hpp
- rai/core_test/block_store.cpp
- rai/core_test/ledger.cpp
- rai/core_test/node.cpp
- rai/core_test/rpc.cpp
- rai/ledger.cpp
- rai/ledger.hpp
- rai/node/bootstrap.cpp
- rai/node/common.cpp
- rai/node/common.hpp
- rai/node/node.cpp
- rai/node/node.hpp
- rai/node/rpc.cpp
- rai/node/stats.cpp
- rai/node/stats.hpp
- rai/qt/qt.cpp
This PR adds epoch blocks, which are a variant of state blocks. They will be used to prevent future old type (non-state) blocks. This code may also be used for future upgrades.
How to detect if a state block is a epoch block:
- Its link field is epoch_link (currently `"epoch v1 block"` then a bunch of null bytes)
- Its balance is the same as the previous block for the account (or 0 if previous is 0)
Additional requirements of an epoch block (for more details see `rai::ledger_processor::epoch_block_impl`):
- Its account must not be the burn account
- It is signed by epoch_signer (currently the genesis account) instead of its account
- Its representative is the same as the previous block for the account (or the burn account if previous is 0)
- Its account's version must be 0
An epoch block …
> Add epoch blocks to disable old type blocks

- rai/node/common.hpp
Allows message types to be safely removed in the future, and I think it's good documentation since it's part of the protocol.
> Explicitly set message type values

- rai/core_test/network.cpp
- rai/node/bootstrap.cpp
- rai/node/bootstrap.hpp
Currently the range for "bulk_pull" is not inclusive of the start block if that is also the end block, change the semantics such that this is not the case if a block (rather than an account) is specified as the start member.  This allows you to pull a single block by specifying the start and end members as the same value.
> Make "bulk_pull" with a start block inclusive of that start block

- CMakeLists.txt
- rai/core_test/CMakeLists.txt
- rai/lib/CMakeLists.txt
- rai/node/CMakeLists.txt
- rai/slow_test/CMakeLists.txt
Another round of cleanups in the cmake code. The commits should be self explanatory.
> Minor cleanups in cmake code

- rai/node/rpc.cpp
Otherwise the error message is undefined.
> Empty response message when there's no error code

- rai/core_test/message_parser.cpp
- rai/node/bootstrap.cpp
- rai/node/bootstrap.hpp
- rai/node/common.cpp
- rai/node/common.hpp
- rai/node/node.cpp
- rai/node/stats.cpp
- rai/node/stats.hpp
This will close #988 
Still to do:
Tests will be added as a separate change set.
> Bulk pull account

- rai/core_test/CMakeLists.txt
- rai/core_test/gap_cache.cpp
- rai/core_test/ledger.cpp
- rai/core_test/network.cpp
- rai/core_test/node.cpp
- rai/core_test/rpc.cpp
- rai/core_test/testutil.hpp
- rai/core_test/wallet.cpp
- rai/core_test/wallets.cpp
- rai/node/testing.cpp
- rai/node/testing.hpp
- rai/qt_test/qt.cpp
Summary:
* Uses deadlines (durations in any time unit) instead of iterations
* gtest extended with ASSERT_NO_ERROR which prints std::error_code messages on error. 
* system::poll returns std::error_code. ASSERT_NO_ERROR will have more uses in the future as more code migrates to error_code.
* Deadline scale factor support
The scale factor is an environment variable which makes it easier to experiment with deadlines (instead of recompiling).
It can also be set when running tests on slow machines.
For instance, to see if 10% of the deadline (1 second in this case) is enough to pass the `node_receive_quorum` test:
`DEADLINE_SCALE_FACTOR=0.1 GTEST_FILTER=node.node_receive_quorum Debug/core_test`
To allow 20% more time on all tests on a slow machine, a Travis config or whatever can export: …
> Deadlines in tests

- rai/node/bootstrap.cpp
Handle remote endpoint fetching more carefully, it could be for a disconnected socket which will
throw an error
> Handle remote endpoint fetching more carefully

- rai/core_test/wallet.cpp
Fixing some wallet tests on master to use strongly typed iterators
> Fixing wallet Tests for strongly typed iterators

- rai/node/cli.cpp
- rai/node/wallet.cpp
& remove unnessesary enter_initial_password after wallets.create in cli.cpp
> Move enter_initial_password out of node.background

- README.md
And added a source for check a node status on the network.
> Update ledger Information

- rai/node/node.cpp
- rai/node/stats.cpp
- rai/node/stats.hpp
Several reports of missed callback. This PR adds `http_callback.initiate` and `error.http_callback`. If the initiation count > what the recipient observes, maybe there's a problem at the other end.
> Add callback stats

- rai/core_test/block_store.cpp
- rai/core_test/gap_cache.cpp
- rai/core_test/ledger.cpp
- rai/core_test/network.cpp
- rai/core_test/node.cpp
- rai/core_test/processor_service.cpp
- rai/core_test/rpc.cpp
- rai/core_test/versioning.cpp
- rai/core_test/wallet.cpp
- rai/core_test/wallets.cpp
- rai/node/bootstrap.cpp
- rai/node/cli.cpp
- rai/node/lmdb.cpp
- rai/node/lmdb.hpp
- rai/node/node.cpp
- rai/node/rpc.cpp
- rai/node/testing.cpp
- rai/node/wallet.cpp
- rai/node/wallet.hpp
- rai/qt/qt.cpp
- rai/qt_test/qt.cpp
- rai/rai_node/entry.cpp
- rai/rai_wallet/entry.cpp
- rai/secure/blockstore.cpp
- rai/secure/ledger.cpp
- rai/slow_test/node.cpp
Wallet refactor.  Fixes #1085.
> Wallet refactor

- rai/core_test/rpc.cpp
- rai/node/rpc.cpp
The non-test part of edcdb15 was reverted in 2a6030c, which broke the test
> Fix duplicate send ID insufficient balance again

- rai/lib/numbers.cpp
Abort if decoding hex numbers fail in a constructor.
We may want to not merge this PR and instead get rid of this constructor as discussed in #888 but this is a start
Closes #888
> Abort if decoding hex numbers fails

- rai/lib/utility.cpp
- rai/node/node.cpp
There seems to be nodes on betanet running with livenet databases (blocks are from livenet). Since it's easy to mix up databases when using `--data_path`, this PR proposes to check that the db contains the correct genesis block ~~write the network id into the `meta` db and abort the process if it doesn't match the process' network id on startup.~~
> Check genesis on startup

- rai/core_test/block_store.cpp
- rai/node/lmdb.cpp
28945d6 copied the vote constructor, but was rebased on top of vote by hash where that changed. This also adds a test for the behavior.
> Fix vote DB deserialization

- rai/core_test/node.cpp
- rai/node/node.cpp
> Fix vote rebroadcasting

- rai/core_test/block_store.cpp
- rai/node/lmdb.cpp
Fixes https://github.com/nanocurrency/raiblocks/issues/1164
> Compare value in merge itr only when key is equal

- rai/node/cli.cpp
- rai/node/wallet.cpp
- rai/node/wallet.hpp
> Add --clear_send_ids CLI option

- util/makesrc
Script will create source tarball to replace github releases broken automatically created ones fixed #1109 
Next issue will be to automate this script as an artifact in one of the CI/CD tools.
makesrc <tag>
requires ruby gem github_changelog_generator
API_KEY generated here https://github.com/settings/tokens/new?description=GitHub%20Changelog%20Generator%20token
> Script to make source tarball to replace Github's broken one

- rai/node/node.cpp
@rkeene oops, this change wasn't added to the commit in https://github.com/nanocurrency/raiblocks/pull/1179
> Enable bootstrap weights on betanet

- rai/core_test/block_store.cpp
- rai/node/lmdb.cpp
- rai/node/lmdb.hpp
- rai/secure/blockstore.hpp
As it's used only n block_processor, there is no reason to cache it for different write transacton
> Remove unchecked_cache

- rai/node/node.cpp
- rai/secure/common.hpp
About 18% of the bootstrap targets are nodes that can never be in sync - this sets the minimum version to ensure the node groks VBH (please verify version). An alternative is to depeer them outright, or we can use this as a first step.
> Minimum bootstrap node version

- rai/node/lmdb.cpp
- rai/node/node.cpp
- rai/rai_node/daemon.cpp
- rai/rai_wallet/entry.cpp
If the user has not granted access to change permissions, don't abort when trying to change permissions
> Swallow exceptions regarding changing filesystem permissions

- CMakeLists.txt
Fixes #1212 by setting stack size to 8MB to match linux
> Resize stack to 8MB to match Linux

- rai/core_test/node.cpp
After pull request #1157 was merged the requirements for quick confirmation changed, this patchset improves the test `node.quick_confirm` to conform to those requirements as well as verifies explicitly the resulting balances
> Improve node.quick_confirm test

- rai/node/lmdb.cpp
Release assert on DB failures, since while they should not happen we do not want the program to continue past it without error recovery (which we lack if there is an assert)
> Release assert on DB failures

- rai/node/node.cpp
In the basic broadcast_confirm_req case, limit to 32 representatives
or peers.  This will limit the outgoing bandwidth.
This changes the semantics of broadcast_confirm_req to require the
caller to call it again if the first call didn't achieve the desired
results.  In practice, this is already done because it may not reach
any peers (indeed there may be none connected).
> In broadcast_confirm_req case, limit to 32 peers

- rai/node/node.cpp
- rai/node/node.hpp
- rai/node/rpc.cpp
100 ms by default
25 ms for RPC republish
> Republish unconfirmed blocks with delay

- rai/node/node.cpp
- rai/node/node.hpp
Improves logging to indicate how many representatives it is broadcasting to in each batch, and delays the second group by 50ms from the first group (instead of 0ms).
> Basic confirm_req improvements

- rai/node/node.cpp
Copy processed_active before dequeuing it so that we may call node.active.start without a lock held
Option 2 for issue #1235
> Copy processed_active before dequeuing it

- rai/rai_wallet/entry.cpp
set "enable_voting": "false", "bootstrap_connections_max": "4"
to reduce load on slow PCs
> Change default desktop config.json

- rai/node/node.cpp
- rai/node/node.hpp
Replaces pull request #1237 
Start new elections for previous block & source if there are less than 100 active elections
> Fix deadlock for elections escalation

- rai/secure/ledger.cpp
Checking the balance of the previous block may be slow if the previous block is not a state block.
Therefore, re-order the epoch test to check the link codes first before the more expensive test of checking to see if the delta_balance is zero.
> Check epoch_link before checking balance of state blocks

- rai/core_test/node.cpp
- rai/node/node.cpp
To reduce unnecessary average nodes load.
- addditional disable successor confirmation for nodes with disabled voting in config
>  Remove processing blocks from confirm_req

- rai/core_test/network.cpp
Keepalive removed. Nodes should be unknown for each other until bootstrap (offline)
More intermediate checks to find issue parts
Currently should fail with https://github.com/nanocurrency/raiblocks/pull/1246
> Extended bulk.offline_send

- rai/core_test/node.cpp
Conflicting port 54000 default for beta & test networks
> Fix node.password_fanout test with running beta node

- rai/node/logging.hpp
- rai/node/node.cpp
This gives more information in places where we don't catch (an example I've seen before is buggy log statements, i.e. lacking arguments for the format specifier, which throws boost::system::error_code)
> Log common exceptions before asserting

- rai/node/node.cpp
- rai/node/node.hpp
As it is, if you set io_threads to 16, you'll get 16 network threads as well.
> Separate config option for network threads

- rai/node/node.cpp
- rai/secure/ledger.cpp
If previous block not existing/not commited yet, ledger.block_source can cause segfault for state blocks
So source check can be done only if previous != nullptr or previous is 0 (open account)
Fixes #1280
> Fix escalation source block check

- rai/node/lmdb.cpp
- rai/node/rpc.cpp
- rai/node/wallet.cpp
Up to 25-50% performance increase for large wallets search
1 request in for loop instead of 2 requests (if there are no pending/unchecked for given key - most likely scenario).
> Improve pending & unchecked search performance

- rai/node/common.cpp
- rai/node/common.hpp
- rai/node/node.cpp
- rai/node/stats.cpp
- rai/node/stats.hpp
Better error messages for gap_cache::vote (Fixes #1208)
Better error messages when deserializing buffers (Fixes #1207)
> Better error messages

- CMakeLists.txt
Work around no longer necessary as threads are always spawned with 8MB stack size added in #1289
> Revert stack size linking for windows

- rai/node/node.cpp
There seems to be a missing mutex around this call to a huge boost multi-index item
> Add mutex around peers.get<T>()

- rai/node/rpc.cpp
This PR contains the changes to fix the behaviour described in #1270. In this fix, decrementing the count for the number of entries in an accounts history only occurs when the entry is not empty (i.e. when the history visitor visits the change block and it is not set to raw)
> No longer decrement the count if the entry is empty during account_history RPC call.

- rai/qt/qt.cpp
- rai/qt/qt.hpp
Updates the GUI labelling to use `NANO`, `Mnano`, `knano` and `nano` instead of `XRB`, `Mxrb`, `kxrb` and `xrb` respectively.
> New unit labels from legacy XRB to NANO style

- rai/core_test/node.cpp
- rai/lib/utility.cpp
- rai/lib/utility.hpp
- rai/node/CMakeLists.txt
- rai/node/node.cpp
- rai/node/node.hpp
- rai/node/voting.cpp
- rai/node/voting.hpp
- rai/secure/common.cpp
- rai/slow_test/node.cpp
This patch decouples vote generation from quorum solicitation. Previously both were done in one large announce loop which on average would delay vote generation by 1/2 the announcement interval.
Now we announce votes as soon as a local decision is made i.e. a block is inserted in to the ledger.
> Separate vote generation process

- rai/core_test/rpc.cpp
- rai/node/rpc.cpp
This patch resolves an issue with the RPC handler for `account_move` incorrectly decoding accounts by hex. According to https://github.com/nanocurrency/raiblocks/wiki/RPC-protocol#account-move this method should accept addresses rather than public keys and therefore needed `decode_account` instead.  
Closes #666
> Using decode_account instead of decode_hex in account_move RPC handler

- rai/qt/qt.cpp
- rai/qt/qt.hpp
- rai/qt_system/entry.cpp
Uses the QSettings class to provide persistence for QT Settings, in this case the XRB scale ratio as set by the radio button group in the Advanced tab.
Closes #511
> Using QSettings to persist application settings for selected ratio scale

- rai/node/node.cpp
- rai/node/stats.cpp
- rai/node/stats.hpp
This catches ICMP rejects from firewalls too.
Seems like we keep trying to send to quite a few endpoints that we'll probably never be able to contact. Should maybe add a backoff on these endpoint (they may be down and get back up)
Adding stats for now.
> Add unreachable host stats

- ci/deploy-docker.sh
So we can pull the "latest-rc" tag that points to the latest release candidate.
> Add "latest-rc" tag for Docker

- rai/node/cli.cpp
When using the wallet_import currently the wallet_id must be created, with this change passing --force 1 would allow it to create the wallet using the specified wallet_id and then import into that wallet from the json file
> CLI wallet_import force wallet creation if requested

- rai/node/bootstrap.cpp
- rai/node/stats.cpp
- rai/node/stats.hpp
- rai/qt/qt.cpp
Payload traffic is currently only collected for udp. This PR adds stats for bootstrap traffic as well.
> Bootstrap traffic stats

- ed25519-donna/ed25519.c
- rai/core_test/interface.cpp
Advantage: resistance to side channel attacks
Disadvantage: signatures will be non-deterministic
> Make signatures non-deterministic

- rai/node/lmdb.cpp
- rai/node/lmdb.hpp
This adds a second cache layer, so that the vote store remains consistent during flushing.
Fixes #1206
> Fix vote_cache

- rai/node/bootstrap.cpp
To avoid a situation where we commit too much memory to the `bulk_pull_account` bootstrap operation, allow duplicates to be sent if too much memory has been allocated.
> Limit the amount of deduplication items we store

- ed25519-donna/ed25519.c
Follow up to #1353. I noticed that https://eprint.iacr.org/2017/985.pdf recommended dedicating a full hash block to the key and random bytes to prevent side channel attacks (I don't recall that from the paper I had previously read). This is also similar to how keys work in blake2b, and again there's really no reason not to do it.
> Dedicate a full r hash block to attacker unknown bytes

- rai/node/rpc.cpp
Fixes #1347 
Related to boost json library: https://github.com/boostorg/property_tree/blob/develop/include/boost/property_tree/json_parser/detail/write.hpp#L161
> removing std::endl from filter_request

- rai/node/node.cpp
To avoid unnecessary background() calls, as well as to reduce the amount of `block_arrival.recent` invocations. 
`block_arrival.recent` is called from `process_receive_one` as well, so not calling it from the observer should still get the arrival.erase logic done.
> Only observe blocks if callback is configured

- rai/node/logging.cpp
- rai/node/logging.hpp
- rai/node/nodeconfig.cpp
- rai/node/nodeconfig.hpp
- rai/rai_node/daemon.cpp
- rai/rai_node/daemon.hpp
- rai/rai_wallet/entry.cpp
There's been a couple of instances where the version number haven't been changed in all places. This puts the json config version in a member so it's only one place to change it.
> Make config upgrades more robust

- rai/node/peers.cpp
- rai/node/peers.hpp
- rai/node/rpc.cpp
If `peer_details` is true, add account/ip/rep weight to the `confirmation_quorum` RPC call.
> RPC confirmation_quorum: optionally include account/ip/rep weight

- CMakeLists.txt
- rai/node/CMakeLists.txt
The cmake restructuring removed the linker reference.
> Fix secure rpc build

- rai/node/node.cpp
- rai/node/node.hpp
>  Early detection for votes overflow

- rai/node/rpc.cpp
- rai/secure/ledger.cpp
When calling account_history with a block that does not exist, it currently fails to find the block resulting in dereferencing a NULL pointer.
This change makes it return an error.  Another option is to make it return an empty history for the hash.
> Ensure the block exists in account_history

- rai/node/node.cpp
- rai/node/node.hpp
- rai/node/rpc.cpp
to include confirmation time per block and Avg
example response
```curl -sd {\"action\":\"confirmation_history\"} [::1]:55000                                                                                         {
"confirmation_stats": {
"count": "18",
"average": "18.657268277833328"
},
"confirmations": [
{
"hash": "862AB923DA184D85D5719D8222463E6DA6D6DB33F026B079B5F628C0598C4645",
"duration": "7.6989772170000004",
"tally": "67004984199081277794346622015067693764"
},
```
...
> Extend Confirmation History 

- rai/core_test/network.cpp
- rai/node/bootstrap.cpp
- rai/node/bootstrap.hpp
- rai/node/node.cpp
- rai/node/node.hpp
- rai/node/nodeconfig.cpp
- rai/node/nodeconfig.hpp
- rai/node/rpc.cpp
- rai/rai_node/daemon.cpp
- rai/rai_node/daemon.hpp
- rai/rai_node/entry.cpp
- Improve lazy_start function, limit lazy_keys size to 1024 (https://github.com/nanocurrency/raiblocks/pull/1422)
- Add lazy_mode flag before lazy_run if running after usual bootstrap (https://github.com/nanocurrency/raiblocks/pull/1423)
- ~Force drop lazy bootstrap connection for long chains to prevent high bandwidth usage (https://github.com/nanocurrency/raiblocks/pull/1424)~
- Force drop lazy bootstrap connection for long bulk_pull to prevent high bandwidth usage
- Force drop lazy bootstrap connection for unexpected block (unconfirmed)
- Lazy bootstrap timeout with active pulls (https://github.com/nanocurrency/raiblocks/pull/1425)
- Finish lazy bootstrap without lazy pulls (https://github.com/nanocurrency/raiblocks/pull/1428)
- Add launch flags --disable_legacy_bootstrap, …
> [v17] Lazy bootstrap improvements

- rai/core_test/network.cpp
- rai/node/bootstrap.cpp
- rai/node/bootstrap.hpp
- rai/node/node.cpp
- rai/node/node.hpp
- rai/node/nodeconfig.cpp
- rai/node/nodeconfig.hpp
- rai/node/rpc.cpp
- rai/rai_node/daemon.cpp
- rai/rai_node/daemon.hpp
- rai/rai_node/entry.cpp
- Improve lazy_start function, limit lazy_keys size to 1024 (https://github.com/nanocurrency/raiblocks/pull/1422)
- Add lazy_mode flag before lazy_run if running after usual bootstrap (https://github.com/nanocurrency/raiblocks/pull/1423)
- ~Force drop lazy bootstrap connection for long chains to prevent high bandwidth usage (https://github.com/nanocurrency/raiblocks/pull/1424)~
- Force drop lazy bootstrap connection for long bulk_pull to prevent high bandwidth usage
- Force drop lazy bootstrap connection for unexpected block (unconfirmed)
- Lazy bootstrap timeout with active pulls (https://github.com/nanocurrency/raiblocks/pull/1425)
- Finish lazy bootstrap without lazy pulls (https://github.com/nanocurrency/raiblocks/pull/1428)
- Add launch flags --disable_legacy_bootstrap, …
> [master] Lazy bootstrap improvements

- rai/core_test/node.cpp
- rai/node/node.cpp
- rai/node/node.hpp
If possible. Confirm elections for: previous block, source or link
> Confirm dependent active elections

- rai/node/node.cpp
- rai/node/node.hpp
- rai/node/rpc.cpp
Confirmation History avg and per block timers to be in MS as the rest of the timers are
declaration more easily readable
> Update Confirmation Timers to be ms not sec

- rai/node/bootstrap.cpp
The docs recommend shutdown before close [1] and most asio servers I've seen do this (the IPC patch does the same). Should evict pending io ops immediately/flush buffers properly on all platforms before closing.
[1] https://www.boost.org/doc/libs/1_66_0/doc/html/boost_asio/reference/basic_stream_socket/close/overload2.html
> Close sockets gracefully

- rai/node/common.hpp
From https://en.cppreference.com/w/cpp/language/extending_std:
> It is undefined behavior to add declarations or definitions to namespace std or to any namespace nested within std, with a few exceptions
A struct template **endpoint_hash** and full explicit specializations were defined within the std namespace; I have moved them out. As they are only used within this file I have wrapped them in an unnamed namespace and moved the existing **endpoint_hash_raw** & **ip_address_hash_raw** static functions into that as well; using static for internal linkage should be avoided (see More Effective C++ Item 31).
> Remove endpoint_hash from std namespace

- rai/node/rpc_secure.hpp
Virtual function specifiers have always been implicitly inherited from their base classes. So the use of the virtual keyword in these cases has been redundant but was recommended in pre-modern C++ so that it was more easily distinguishable from non-virtual functions when reading derived class definitions. However since C++11, the override specifier has superseded this with compile time safety, and so explicitly writing both in a derived class is not required. 
I propose that the virtual specifier is removed in any function declaration where both the override and virtual function specifiers are used. 
The following command was used in the root directory to find and replace all instances where virtual and override specifiers were used.
find -type f -print0 | xargs -0 sed -ri …
> Remove virtual function specifiers where override is used

- rai/node/node.cpp
Function template specializations are not candidates for overload resolution, and should be avoided where possible. Herb Sutter describes the Dimov/Abrahams example explaining why:
http://www.gotw.ca/publications/mill17.htm
A recent detailed talk summarising the issues during CppCon2018 can be found [here](https://www.youtube.com/watch?v=NIDEjY5ywqU)
Typed template parameters can just have the type substituted directly using standard function overloading.
> Remove function template specializations

- rai/core_test/processor_service.cpp
- rai/lib/work.cpp
- rai/node/bootstrap.cpp
- rai/node/node.cpp
- rai/node/voting.cpp
- rai/node/wallet.cpp
This should fix #1284. Some of these locks are for setting `stopped` and `started` flags, those functions could get a cleaner look by using `std::atomic_bool` on those flags and avoiding the explicit lock/unlock.
> Pessimisation fix for condition_variable notify_*

- util/build_prep/bootstrap_boost.sh
Support more ways to build Boost, which may be required on some platforms.
This adds "-C" to build with clang's "libc++", as well as "-f" to build a PIC version of all the objects, which will be required for PIE executables on newer versions of Ubuntu.
Additionally a "-v" option is added so you can specify greater debug levels to, for example, see the compile strings.
> Add more support for building boost with different options

- rai/lib/blocks.cpp
- rai/secure/common.cpp
When removing items from the vote uniquer `votes` set, use a random item rather than always the first item
Fixes #1471 
This change will also include the fix for the block uniquer
> Remove random items from the uniquer sets

- rai/node/node.cpp
- rai/node/node.hpp
This may be temporary solution as initially all unchecked state blocks should be placed in blocks deque (second verification is not required)
> Verify more state blocks if blocks deque is empty

- rai/core_test/block_store.cpp
- rai/node/lmdb.cpp
- rai/node/lmdb.hpp
- rai/node/node.cpp
- rai/node/rpc.cpp
- rai/secure/blockstore.hpp
- rai/secure/common.cpp
- rai/secure/common.hpp
Currently without upgrade path (clear unchecked before or after using patch)
Part of work on #1478
> Remove dupsort from unchecked table

- ci/test.sh
Two related changes:
1. The retry timer we set expired on December 20, 2018 -- before we had a chance to fix all the intermittently failing tests (originally set in #1218)
2. The bash specification contains a bug where empty arrays are treated as unbound, this works around that
> Extend test retry

- rai/core_test/ledger.cpp
- rai/core_test/network.cpp
- rai/core_test/node.cpp
- rai/core_test/processor_service.cpp
- rai/core_test/rpc.cpp
- rai/core_test/wallet.cpp
- rai/node/bootstrap.cpp
- rai/node/bootstrap.hpp
- rai/node/node.cpp
- rai/node/node.hpp
- rai/node/rpc.cpp
- rai/node/rpc.hpp
- rai/node/testing.cpp
- rai/node/testing.hpp
- rai/qt_system/entry.cpp
- rai/rai_node/daemon.cpp
- rai/rai_node/entry.cpp
- rai/rai_wallet/entry.cpp
- rai/slow_test/node.cpp
Also proposes using `io_ctx` instead of `service` for variable/field names; seems to make more sense after the change.
> Move from deprecated io_service to io_context

- rai/node/rpc_secure.cpp
I propose to replace all binds with lambdas. As of C++14 there isn't anything that std::bind does which lambdas can't do (that I know of). Lambdas are actually used throughout the code except notably in rai_secure.cpp. In addition to removing this construct entirely from the codebase, it keeps the asio callbacks more consistent.
As "Effective Modern C++ Item 34 - Prefer lambdas to std::bind" describes, to the uninitiated _1 essentially looks like magic (among other things). std::bind1st and std::bind2nd have been removed in C++17, and std::bind is set to follow suit. For more information about std::bind there is a handy section of this video by [Stephan T Lavavej](https://youtu.be/zt7ThwVfap0?t=1511):
> Replace bind with lambda

- ci/deploy-docker.sh
We migrated the nanocurrency repository to an Organization on DockerHub,
this required us to create a new user to manage the releases.
> Update DockerHub username

- rai/core_test/uint256_union.cpp
- rai/lib/numbers.cpp
On an MSVC Release build I profiled bootstrapping a fresh node for 30 seconds (chosen arbitrarily) to see if there was anything obvious which easily be improved. I found that 7% of the time was spent inside rai::uint256_union::number() when requesting frontiers.
There is a boost function boost::multiprecision::import_bits() which takes a sequence of bytes and constructs the appropriate multiprecision number (and conversely export_bits() to do the opposite). I tried using this instead and there was a small performance improvement. Next I looked at the callers and the majority were from the less than operator rai::uint256_union::operator<. Inside it, it calls number() on each operand and does the comparison with the result. However I think this step is unnecessary, and the bytes can be …
> Improve requesting frontier performance

- rai/node/node.cpp
This was found using MSVC 2017 in a debug build; it's possible it happens with others.
When votes are being announced, there is a loop which traverses all the representatives. While iterating it checks if the current representative is inside rep_votes, if it is then it takes the last element of the representative vector and swaps it with the current one being iterated; the last element is then discarded. It then continues iterating using the newly swapped representative. This works fine until we are unfortunate enough to be iterating over the last element of the vector which also happens to be inside rep_votes. It gets popped off and our current iterator (j) becomes invalidated. The node then falls over when the next (j != m) condition statement is reached. I now check whether we are at …
> Fix crash when announcing votes

- rai/qt/qt.cpp
- rai/qt/qt.hpp
Several second lockups on beta on my account with tons of pending due to observers trigging pending balance calculations. This seems to fix it, as well as lockups when user initiates searching for pending and bootstrap.
> Reduce UI lockups

- rai/qt/qt.cpp
Sorted Blocks: xxxxx Unsorted: xxxxxx
fixes #1245
> Update UI block status

- nano/nano_node/entry.cpp
- nano/nano_wallet/entry.cpp
- nano/secure/utility.cpp
- nano/secure/utility.hpp
As a part of the rename from RaiBlocks to Nano (#1504), we now default to a different data path.
This adds a migration from the old/legacy path to the new path.
> Migrate existing data from ~/RaiBlocks to ~/Nano

- nano/nano_node/entry.cpp
I made a few changes:
1 - Reduce number of traverses of the vm tree; doing vm.count("something") and vm["something"] are both O(log) operations, but can be accomplished with a single O(log) using vm.find() instead. This also removes duplicated hardcoded strings (although that could have also been done by creating a variable), vm derives from std::map so count will always either be 0 or 1.
2 - Remove excess std::endl usage. This creates a newline, but also flushes the buffer (expensive), it is recommended to use "\n" when needing a new line instead, and only explicitly flush when necessary.
3 - Removed a warning under MSVC 2017 about converting size_t to uint32_t in the "debug_mass_activity" compound block.
4 - There were a couple of "for (uint64_t i (0); true; ++i)" blocks, but **i** is …
> Minor cleanup of entry.cpp for node

- nano/node/cli.cpp
Closes https://github.com/nanocurrency/raiblocks/issues/1340
On weak cpu's, changing seed can take a few minutes due to work generation (determinstic_insert caches work for the first four accounts) and users may think the command is stuck. This prints a bit of info about what's going on.
> UI feedback when changing seed

- nano/core_test/uint256_union.cpp
- nano/nano_node/daemon.cpp
- nano/nano_wallet/entry.cpp
- nano/secure/utility.hpp
`rai::fetch_object` doesn't need `config_file` parameter, `config_file` is only used inside this function, carries no input/output.
Close #1143
> Remove redundant config_file parameter of fetch_object

- nano/core_test/node.cpp
- nano/node/wallet.cpp
To prevent node.unlock_search assert
Initially part of v17 https://github.com/nanocurrency/raiblocks/pull/1409
> Add recursive_mutex to foreach_representative

- nano/core_test/rpc.cpp
- nano/node/rpc.cpp
to change representative for existing accounts (https://github.com/nanocurrency/raiblocks/issues/1019, @renesq)
> "update_existing_accounts" option for RPC wallet_representative_set

- docker/ci/Dockerfile
In the Dockerfile used for continuous integration all the boost libraries are built; however we only need 4: thread, log, filesystem & program_options. Now this isn't a big issue as we use the option "--cache-from nanocurrency/nano-ci:latest", which picks up the boost files from the intermediate cache layer. But it would be a bit quicker getting the cache and also result in a smaller docker image.
I've made another adjustment as per the docker best practices ["Always combine RUN apt-get update with apt-get install in the same RUN statement"](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#apt-get). This is because, if we only changed the second RUN then we would not be getting the latest repositories from apt even though apt-get update is called in the first one, …
> Only build essential boost libraries in docker

- nano/core_test/network.cpp
- nano/node/bootstrap.cpp
- nano/node/bootstrap.hpp
> Slightly more efficient way of storing duplicates

- nano/core_test/interface.cpp
- nano/lib/interface.cpp
- nano/lib/interface.h
> Zero-terminate all things we refer to as strings

- nano/node/common.hpp
In similar vein to #1460  the ip_address_hash struct and specializations have been removed from polluting the std namespace.
> Remove ip_address_hash from std namespace

- util/build_prep/bootstrap_boost.sh
- util/build_prep/update-common
Due to bugs in bash empty arrays are treated as unset, but we use empty
arrays in some conditions in the boost bootstrap script.  When calling
that script from the build prep script by inclusion, remove the nounset
flag so that empty arrays can be used as empty arrays.
> Get rid of nounset flag when running the Boost bootstrap subscript

- nano/core_test/rpc.cpp
- nano/node/rpc.cpp
- nano/node/rpc.hpp
- nano/node/wallet.cpp
- nano/node/wallet.hpp
Adds optional `index` parameter to RPC [account_create](https://github.com/nanocurrency/nano-node/wiki/RPC-protocol#account-create). Wiki will need to be changed.
Additionally extends `account_create` unit tests.
> Optional deterministic index in RPC account_create

- nano/core_test/CMakeLists.txt
- nano/core_test/timer.cpp
- nano/lib/CMakeLists.txt
- nano/lib/timer.hpp
- nano/node/node.cpp
Documentation started here: https://github.com/cryptocode/notes/wiki/Timer
I've introduced it into a couple of node.cpp functions; seems to simplify the timing code a fair amount.
> Timer utilities

- nano/node/node.cpp
- nano/node/node.hpp
https://github.com/nanocurrency/raiblocks/issues/1073
Instead of looping through all resolved addresses, only iterate if there is a failure and try again.
> (Proposal) Fix multiple rpc callbacks for same host.

- nano/node/node.cpp
- nano/node/peers.cpp
This is part of https://github.com/nanocurrency/raiblocks/issues/1044, where `std::random_shuffle` is removed in C++17.
> Move to random_pool for shuffling

- nano/qt_test/qt.cpp
Neglected to update tests to match status, fixes tests broken in #1510
> Fix tests broken with #1510

- nano/node/node.cpp
- nano/node/node.hpp
With limit 1024
Replacing old https://github.com/nanocurrency/nano-node/pull/1158
> List of rolled back blocks in block_processor

- nano/core_test/rpc.cpp
- nano/node/rpc.cpp
Set default count to 0. Fixes issue caused by incorred https://github.com/nanocurrency/nano-node/pull/775 update
> Fix RPC wallet_change_seed

- nano/node/lmdb.cpp
MDB_NOSYNC could provide improvements with disk usage by not calling fsync after commit
MDB_NORDAHEAD improves memory usage by not trying to read ahead in the DB, This has no effect on windows but other OSes should benefit. Windows does not read ahead so it is not affected
> MDB improvements

- nano/node/node.cpp
Some tests rely on stats. In this case the `node_id_handshake` stat was updated before peer insertion, causing the test to fail sporadically.
> Fix intermittent send_node_id_handshake failure

- nano/lib/utility.cpp
- nano/lib/utility.hpp
- nano/node/node.cpp
- nano/node/node.hpp
announce_loop () --> request_loop ()
announce_interval_ms --> request_interval_ms
as it's no longer used to announce votes
> Rename announce_votes () to request_confirm ()

- nano/node/node.cpp
- nano/node/node.hpp
Alternative to https://github.com/nanocurrency/nano-node/pull/1566
> Check state blocks existence in ledger before verification

- nano/core_test/block_store.cpp
- nano/core_test/ledger.cpp
- nano/lib/numbers.hpp
- nano/node/lmdb.cpp
- nano/node/lmdb.hpp
- nano/secure/blockstore.hpp
- nano/secure/ledger.cpp
- nano/secure/ledger.hpp
Proposing to remove checksum as it isn't used beyond tests, to save some IO in `ledger::update_latest` and remove some code.
> Remove checksum table

- nano/qt/qt.cpp
Adds network next to the version number, e.g, "Version 18.0 Beta network"
> Indicate active network in Qt wallet

- nano/core_test/message_parser.cpp
- nano/node/bootstrap.cpp
- nano/node/bootstrap.hpp
- nano/node/common.cpp
- nano/node/common.hpp
- nano/node/node.cpp
This solves #1585
It removed anything which references bulk_pull_blocks, which was deprecated before and shouldn't be used anymore.
The only thing that is probably worth mentioning is the comment I've added to the removed `bulk_pull_blocks` enum value in common.hpp to indicate that the message was previously used and deleted, so as not to use it unintentionally, although maybe it's fine.
> Remove deprecated bulk_pull_blocks

- nano/core_test/node.cpp
- nano/lib/jsonconfig.hpp
- nano/node/nodeconfig.cpp
- nano/node/nodeconfig.hpp
This solves #1575 and also 2 other config bugs (`jsonconfig::replace_child ()` not working as expected, and `allow_local_peers` is not being read from the config file).
**nodeconfig.cpp** - Add upgraded section from 16 to 17 which updates `rai.raiblocks.net` -> `peering.nano.org` and `rai-beta.raiblocks.net` -> `peering-beta.nano.org`.  To reduce some duplication of the hardcoded strings, I've made some internal linkage variables. Also using `emplace_back` so that nano::accounts can be created inside the vector directly.
**jsonconfig.hpp** - There were some warnings generated for unused `ex` variables so I've now removed them.
Added a new test which checks that both live/beta preconfigured peer urls are successfully changed and one for allow_local_peers.
> Upgrade preconfigured peers in config.json file to use nano url instead of rai

- nano/node/logging.cpp
- nano/node/logging.hpp
https://github.com/nanocurrency/nano-node/issues/1618
> Increase default max log folder size to 128Mb

- nano/node/rpc.cpp
"Too many open files (24)" instead of 24, etc.
> Improved error message when unable to accept RPC connection

- nano/core_test/rpc.cpp
- nano/node/testing.cpp
Test failing occasionally only with Windows core_test.exe build. Wasn't able to reprocude failures on Linux machine.
`system.wallet (0)` returning `nodes[0]->wallets.items.begin ()->second` while wallets.items is unordered_map. According to http://www.cplusplus.com/reference/unordered_map/unordered_map/begin/ an unordered_map object makes no guarantees on which specific element is considered its first element. In test there are 2 wallets in unordered_map: 1st default, 2nd created with RPC.
> Fix rpc.wallet_create_seed test

- nano/lib/plat/darwin/thread_role.cpp
- nano/lib/plat/freebsd/thread_role.cpp
- nano/lib/plat/linux/thread_role.cpp
- nano/lib/plat/windows/thread_role.cpp
- nano/lib/utility.cpp
- nano/lib/utility.hpp
Add support for getting the current thread's name as a string, which can be useful for logging.
Includes a bit of cleanup as well.
> Add support for getting the current thread's name as a string

- nano/core_test/rpc.cpp
- nano/node/node.cpp
- nano/node/node.hpp
- nano/node/rpc.cpp
- nano/node/rpc.hpp
Tracks the node uptime in seconds.
Sample
```json
{"action": "uptime"}
{"seconds": "73"}
```
> RPC uptime

- nano/qt/qt.cpp
Otherwise it takes up to 5 seconds for the ratio change to be reflected in the UI
> Update balance on ratio change

- nano/node/node.cpp
@wezrule noticed outdated_version sometimes causes a large amount of log entries. No reason to log this, it's expected and there's a stat for it.
> Filter outdated_version errors from logging

- nano/node/bootstrap.cpp
- nano/node/bootstrap.hpp
Currently when we overflow the number of concurrent TCP sockets
we wish to service we accept them then immediately disconnect.
This change causes us to defer accepting new connections until we
are ready for them, relying instead on the OS socket backlog to
queue TCP handshakes until full, then stop processing new
connections when the backlog is full.
We use the I/O threads for scheduling all but one accept, so this
keeps the same thread affinity.
> Better handling of TCP accept overflow

- nano/core_test/CMakeLists.txt
- nano/core_test/ipc.cpp
- nano/nano_node/daemon.cpp
- nano/nano_wallet/entry.cpp
- nano/node/CMakeLists.txt
- nano/node/ipc.cpp
- nano/node/ipc.hpp
- nano/node/logging.cpp
- nano/node/logging.hpp
- nano/node/node.cpp
- nano/node/nodeconfig.cpp
- nano/node/nodeconfig.hpp
- nano/node/rpc.cpp
- nano/node/rpc.hpp
- nano/node/stats.cpp
- nano/node/stats.hpp
Remaining
After reviewing/testing, will also add this:
This adds support for external RPC servers that communicate with the node via IPC (currently domain sockets and tcp).
Using external web servers can benefit service scalability and security. IPC connections are persistent, which should reduce time_wait (file descriptor exhaustion) issues on busy servers.
The internal RPC server can thus be disabled in the config, yet have the functionality exposed via IPC. The JSON format is exactly the same as the internal server - clients only need to change URL. 
A proof-of-concept REST server in Go is available at https://github.com/nanocurrency/rpc-go.
The IPC gateway allows for other message payloads like protobuf (there's a PR for protobuf which would need some work to work with this PR) …
> Support external RPC servers via IPC

- nano/core_test/rpc.cpp
- nano/node/rpc.cpp
- nano/node/rpc.hpp
- nano/node/stats.cpp
- nano/node/stats.hpp
Closes #1620 
`stats_clear` clears all existing stats, and `stats` is  updated to include seconds since last clear (or node startup if never cleared)
> RPC to clear stats

- nano/node/bootstrap.cpp
- nano/node/node.cpp
- nano/node/node.hpp
@wezrule Wanna see if this fixes the TSAN traces you noticed during bootstrap? Should also fix a shutdown race.
> Fix race conditions reported by TSAN

- nano/node/lmdb.cpp
- nano/node/lmdb.hpp
Factored out block reading to mirror how `block_exists` does it. IOW it allows blocks with known types to be looked up directly instead of checking all tables. The only customer right now is `block_raw_get`.
The lookup order is changed to state (v1, v0), send, receive, open, change. Previously state was looked up last.
> Change order of block table lookups

- nano/core_test/node.cpp
- nano/core_test/signing.cpp
- nano/node/node.cpp
- nano/node/node.hpp
- nano/node/nodeconfig.cpp
- nano/node/nodeconfig.hpp
This solves #1606 and provides a finished implementation of #1614 which which was created from the work of @termoose @guilhermelawless so thanks a lot!
Currently the vote and block processors add checks to the `signature checker` which runs on a separate thread and sets the value of a promise which the calling threads are blocked on until it is set. Having it in a separate thread doesn't really do much because the calling threads are blocked straight away so the caller might as well do the work themselves. I have removed that thread and added a thread pool which can be user assigned on the config.json file and is called if the batch size of the signatures to check are > 512. This value was heuristically chosen as the largest size seemed to be 2048 (hardcoded) and 256 size chunks were …
> Multi-thread the signature checker

- nano/node/ipc.cpp
Which was actually a string lifetime issue spotted by msvc's iterator debug support.
> Fix windows tests for ipc

- nano/node/bootstrap.cpp
The first time received_frontier is called, it's only measuring the time of count++. Since the standard only guarantees non-decreasing values for steady_clock, it looks like the value could be zero on systems with low timer resolution, causing (since it's a `double`) NaN, +/-inf or undefined behavior if !is_iec559. Not likely, but a guard seems good here anyway. The approach is consistent with that of `bootstrap_client::block_rate ()`
> Fix potential div-by-zero issue in receive_frontier

- nano/core_test/rpc.cpp
- nano/lib/blocks.cpp
- nano/lib/blocks.hpp
- nano/lib/utility.cpp
- nano/lib/utility.hpp
- nano/lib/work.cpp
- nano/lib/work.hpp
- nano/node/bootstrap.cpp
- nano/node/bootstrap.hpp
- nano/node/node.cpp
- nano/node/node.hpp
- nano/node/peers.cpp
- nano/node/peers.hpp
- nano/node/rpc.cpp
- nano/node/voting.cpp
- nano/node/voting.hpp
- nano/node/wallet.cpp
- nano/node/wallet.hpp
- nano/secure/common.cpp
- nano/secure/common.hpp
- nano/secure/ledger.cpp
- nano/secure/ledger.hpp
This provides an alternate implementation for #1439. The idea is to scan a `node` and all nested variables for sequence containers (`std::vector`, `std::list` etc..) and outputs the number of elements and the size in bytes of the container in a JSON-RPC call when requesting:
Request:
```
{
"action":"stats",
"type":"objects"
}
```
Response:
```
{
"node": {
"ledger": {
"bootstrap_weights": {
"count": "125",
"size": "7000"
}
}
"peers": {
"peers": {
"count": "38",
"size": "7296"
},
"attempts": {
"count": "95",
"size": "3800"
},
},
.
.
...
}
}
```
Ideally the members could be scanned recursively until something which has the methods `.size ()` & `operator[]` and the `value_type` alias is found and then use this. However C++ currently lacks reflection (even in c++17) without some very nasty …
> Memory stats in RPC

- nano/node/node.cpp
- nano/node/node.hpp
Fixing rare node.vote_republish test failures (process_confirmed () can be called before block_processor transaction commit to roll back fork)
>  Improve node::process_confirmed ()

- nano/node/node.cpp
- nano/node/stats.cpp
- nano/node/stats.hpp
Also a clang-format guard where versions disagree.
> Encapsulate and lock stat_datapoint, fixes core_test tsan

- nano/node/rpc.cpp
to trigger automatic rebroadcast and election after https://github.com/nanocurrency/nano-node/commit/e6ab82f5e6ccce2f0de6b529f25a3aef8ee5c204
Credits for finding bug to **Barnabas Liu**
> Set current time for block in RPC process

- nano/node/node.cpp
- nano/node/node.hpp
There are some intermittent test failures (I could only reproduce them on a MAC), caused by a SIGABRT in the ~std::unique_ptr destructor. It seems that the mutex is going out of scope before the thread pool has fully finished. When the last promise.set_value () is called it notifies the main thread that the thread work is finished, and then exits the function (set_thread_names), but the threads haven't fully finished (i.e they still need to call destructors). I'm now (re)using the class member mutex so that it stays in the scope during this cleanup.
> Fix scope issue when setting thread names in the multi-threaded signature checker

- nano/core_test/rpc.cpp
- nano/node/rpc.cpp
- nano/node/rpc.hpp
- nano/node/rpc_secure.cpp
Useful for preflighting requests when using CORS.
rebase of #422 before i messed up the push :/
> Support the HTTP OPTIONS verb for RPC

- nano/node/rpc.cpp
operation_aborted must be checked before calling acceptor members.
> tsan: fix rpc shutdown acceptor issue

- nano/lib/config.hpp
- nano/lib/work.cpp
- nano/lib/work.hpp
- nano/nano_node/entry.cpp
- nano/node/bootstrap.hpp
- nano/node/common.hpp
- nano/node/node.cpp
- nano/node/node.hpp
- nano/node/peers.cpp
- nano/node/portmapping.cpp
- nano/node/portmapping.hpp
- nano/node/voting.hpp
- nano/node/wallet.cpp
- nano/node/wallet.hpp
- nano/qt/qt.cpp
- nano/secure/common.cpp
We do a lot of conditional checking like `nano::nano_network == nano::nano_networks::nano_test_network` I have created some helper constexpr variables which can be used instead e.g `nano::is_test_network`.
It especially helps in situations like this:
`(nano::nano_network == nano::nano_networks::nano_test_network ? nano_test_account : nano::nano_network == nano::nano_networks::nano_beta_network ? nano_beta_account : nano_live_account)`
Which becomes:
`(nano::is_test_network ? nano_test_account : nano::is_beta_network ? nano_beta_account : nano_live_account)`
> Create and use new network helper constants

- nano/node/common.cpp
- nano/node/node.cpp
- nano/node/node.hpp
- nano/node/rpc.hpp
Seems #1680 only searched for the test network and changed those (and any near them). Add missing ones for beta/live.
> Add missing beta/live network helper constants

- nano/lib/timer.hpp
Makes it possible to pass a std::chrono clock type to `nano::timer`. Default is steady_clock since we're using that everywhere else - high_resolution_clock, etc can be chosen when needed.
> Configurable timer clock type

- nano/core_test/network.cpp
- nano/lib/blocks.cpp
- nano/lib/blocks.hpp
- nano/lib/errors.hpp
- nano/node/bootstrap.cpp
- nano/node/common.cpp
- nano/node/common.hpp
- nano/node/lmdb.cpp
- nano/node/node.cpp
- nano/node/testing.hpp
- nano/secure/blockstore.cpp
- nano/secure/common.cpp
- nano/secure/versioning.cpp
While working on Issue #1374 I have to (de)serialize a new object type which had a few member variables. While looking at the existing serialization functions to the data store I thought it would be more readable to use exceptions. It turns something like this:
```
auto error (read (stream_a, min_hash));
if (!error)	
{	
error= read (stream_a, max_hash);	
if (!error)
{	
error= read (stream_a, mode);	
if (!error)
{
error = read (stream_a, max_count);
}
}	
}	
return error;
```
Into:
```
auto error (false);
try
{
nano::read (stream_a, min_hash);
nano::read (stream_a, max_hash);
nano::read (stream_a, mode);
nano::read (stream_a, max_count);
}
catch (std::runtime_error const &)
{
error = true;
}
return error;
```
The previous (existing) form doesn't scale well, some places have 6 members and …
> Convert deserializers to use exceptions

- nano/node/node.cpp
- nano/secure/common.cpp
nano::read no longer returns a bool.
Also noticed a build warning about member variable initialization in node.cpp which seems to have crept in, fixed that as well.
> Deserializer changes in unchecked_info

- nano/node/lmdb.hpp
`stopped` is accessed from different threads and is flagged up by TSAN as a data race.
> Data race when upgrading sideband information

- appveyor.yml
fixes #45 replacing adhoc zip with proper portable packages, sample of build artifact virus total
https://www.virustotal.com/#/file/b6834a309c1b92c5ab999dcb32df16c9d5693826192446377b8765964d86965f/detection
> Use cpack to build zip for win

- nano/node/rpc_secure.cpp
I want to add a separate PR to begin incorporating the TLS build in CI tests.
> Update missed rai:: references to nano::

- .gitlab-ci.yml
- ci/build-centos.sh
- etc/systemd/nanocurrency-beta.service
- etc/systemd/nanocurrency.service
- nanocurrency-beta.spec.in
- nanocurrency.spec.in
- util/build_prep/centos/prep.sh.in
This is a work in progress needing scripting and cleanup
> adding support for rpm building

- CMakeLists.txt
When using gcc 8.2 with Eclipse generated Makefiles on Linux I get unresolved pthread symbols. It appears to only be a gcc error where -lpthread is explicitly required. The recommendation is to use `find_package (Threads)`:
https://cmake.org/pipermail/cmake/2016-February/062729.html
Tested on Mac/clang, Fedora/gcc, and appveyor (Windows) seems to build it ok as well.
> Find pthread in CMakeLists.txt

- nano/core_test/block_store.cpp
- nano/node/lmdb.cpp
- nano/node/rpc.cpp
- nano/node/rpc_secure.cpp
- nano/secure/blockstore.cpp
- nano/secure/ledger.cpp
Account block count + sideband block height now match at the head
Sideband/confirmation height now start at 0 to indicate that they are uninitialized
> Make the sideband open block start at a height of 1

- nano/node/wallet.cpp
Tiny cleanup while looking at https://github.com/nanocurrency/nano-node/issues/406
There are more of these, but taking those in a PR after #1729 gets merged to avoid known merge conflicts.
> Remove unnecessary cast

- nano/node/peers.cpp
- nano/node/peers.hpp
rep_weight / probable_rep_account had random values.
> Initialize peer_information members

- nano/node/lmdb.cpp
Clang 7.0.0, Ubuntu 18.10
```
[ RUN      ] block_store.peers
/root/nano_build/lmdb/libraries/liblmdb/mdb.c:7405:19: runtime error: null pointer passed as argument 2, which is declared to never be null
/usr/include/string.h:43:28: note: nonnull attribute specified here
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /root/nano_build/lmdb/libraries/liblmdb/mdb.c:7405:19 in
[       OK ] block_store.peers (8 ms)
```
> [ASAN] replace junk data with 0 for peer_put ()

- nano/node/lmdb.cpp
- nano/node/node.cpp
- nano/node/node.hpp
- nano/secure/common.cpp
- nano/secure/common.hpp
Fixes ASAN warning Mac/Clang:
```
[1m/Users/user/Library/raiblocks/crypto/cryptopp/randpool.cpp:46:4:[1m[31m runtime error: [1m[0m[1mreference binding to null pointer of type ‘const CryptoPP::NameValuePairs’[1m[0m
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /Users/user/Library/raiblocks/crypto/cryptopp/randpool.cpp:46:4 in
[1m/Users/user/Library/raiblocks/crypto/cryptopp/cryptlib.cpp:61:64:[1m[31m runtime error: [1m[0m[1mreference binding to null pointer of type ‘const CryptoPP::NameValuePairs’[1m[0m
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /Users/user/Library/raiblocks/crypto/cryptopp/cryptlib.cpp:61:64
```
This is because our `ledger_constants globals` variable is initialized with globals from CryptoPP which haven't been properly initialized yet. There is not …
> Fix ASAN warning caused by global initialization order using CryptoPP functions

- nano/core_test/block.cpp
Not supported on all platforms. It was an experiment to try and catch asserts, but there seems to be a few issues with the implementation in gtest.
> Remove expect_death test

- nano/core_test/block_store.cpp
- nano/core_test/wallet.cpp
- nano/core_test/work_pool.cpp
- nano/lib/blocks.cpp
- nano/lib/interface.cpp
- nano/lib/numbers.cpp
- nano/lib/numbers.hpp
- nano/lib/work.cpp
- nano/nano_wallet/entry.cpp
- nano/node/bootstrap.cpp
- nano/node/lmdb.cpp
- nano/node/node.cpp
- nano/node/nodeconfig.cpp
- nano/node/openclwork.cpp
- nano/node/peers.cpp
- nano/node/rpc_secure.cpp
- nano/node/testing.cpp
- nano/node/wallet.cpp
- nano/qt_system/entry.cpp
- nano/secure/common.cpp
- nano/slow_test/node.cpp
thread_local version seems to cause TSAN error with `s_TeFilled` variable inside CryptoPP
> Use a single synchronised random pool across all threads

- nano/node/bootstrap.cpp
Unclear if *not* checking `block_processor.full` is intentional here, so putting it up for discussion. The wallet also doesn't call full(), but Serg felt that's correct there (e.g. receive_action)
> Check if block processor is full in bulk push server

- nano/lib/numbers.cpp
This was something I spotted when looking at this area of code. `false` here is being implicitly converted to an int **0** which is passed in to a function which already has a default parameter `unsigned chunk_size = 0`. So I'm just removing it.
> Remove implicitly converted argument

- nano/node/node.cpp
`full` is not checked as to whether it has any elements in before popping off the container, which I guess can happen in some circumstances as the comment above the function declaration states `// Return nullptr if the container has stopped`. I have added an assert to check for this as well as a precaution.
> Check that full is not empty and assert

- nano/node/lmdb.cpp
Same as was done for block_raw_get, i.e order table lookups according to match probability.
> Improve block_exists table lookup order

- CMakeLists.txt
Minimum requirements for opt.c is SSE2. It is also min requirements for our Win & Linux builds
> Use optimized Argon2 source for all x86_64 builds

- nano/core_test/rpc.cpp
- nano/node/rpc.cpp
- nano/node/rpc.hpp
- nano/node/rpc_secure.cpp
Fixes #1166 .
Wiki update:
_enable_control required, version 19.0+_
Returns the total pending balance for unopened accounts in the local database, starting at **account** (optional) up to **count** (optional), sorted by account number. _**Notes:**_ By default excludes the burn account.
Request:
```
{  
"action": "unopened",  
"account": "xrb_1111111111111111111111111111111111111111111111111111hifc8npp",   
"count": "1"
}
```
Response:
```
{
"accounts": {
"xrb_1111111111111111111111111111111111111111111111111111hifc8npp": "207034077034226183413773082289554618448"
}
}
```
> RPC unopened

- nano/core_test/rpc.cpp
- nano/lib/blocks.cpp
- nano/lib/blocks.hpp
- nano/node/rpc.cpp
- nano/node/rpc_secure.cpp
A new option `json_block` (bool) is added to `create_block` and a few other RPCs stringifying blocks. 
Default is "false" (the old behavior)
If set to "true", the returned block will be proper JSON instead of being stringified with embedded escapes of newlines and quotes. This makes it easier to move offline-signed blocks for processing via the Qt wallet or websites with process functionality.
(A future PR could make `process` support non-stringified blocks.)
> RPC: option to render block as JSON

- nano/nano_node/entry.cpp
Replaces #550 
`--debug_random_feed` makes it easy to feed output from the random generator used for keypair/seed generation into test suites, such as [dieharder](https://webhome.phy.duke.edu/~rgb/General/dieharder.php) (available at least for macOS and Linux)
Example:
```
brew install dieharder
./nano_node --debug_random_feed | dieharder -a -g 200
rng_name    |rands/second|   Seed   |
stdin_input_raw|  7.24e+06  |3948269495|
#=============================================================================#
test_name   |ntup| tsamples |psamples|  p-value |Assessment
#=============================================================================#
diehard_birthdays|   0|       100|     100|0.55550323|  PASSED
diehard_operm5|   0|   1000000|     100|0.35161023|  PASSED
diehard_rank_32x32|   0| …
```
> Command to generate input to RNG test suites

- nano/core_test/rpc.cpp
- nano/node/rpc.cpp
- nano/node/rpc.hpp
Followup to https://github.com/nanocurrency/nano-node/pull/1740 which optionally returned json block literals instead of strings. This does the same for input blocks. In total, this should make working with blocks in RPC's a bit more ergonomic.
> RPC: Support json literals as block input

- nano/node/node.cpp
Previously representatives had to have 1000 Nano voting weight to be included in online_reps and this reduces the amount to any representatives that have at least 1 raw delegated to them.
> Include all representatives with delegated weight in online representatives list

- nano/core_test/rpc.cpp
- nano/nano_wallet/entry.cpp
- nano/node/daemonconfig.cpp
- nano/node/rpcconfig.cpp
- nano/node/rpcconfig.hpp
frontier_request_limit and chain_request_limit are not used. Introduces a version field for the rpc json child.
> RPC config versioning, remove unused options

- nano/node/rpc.cpp
https://github.com/nanocurrency/nano-node/issues/1723
> Deprecate `payments_` RPC calls

- nano/core_test/rpc.cpp
- nano/node/node.cpp
- nano/node/rpc.cpp
https://github.com/nanocurrency/nano-node/issues/809
> Add subtype field for state blocks in RPC block_info, blocks_info

- nano/core_test/CMakeLists.txt
- nano/core_test/logger.cpp
- nano/core_test/node.cpp
- nano/node/blockprocessor.cpp
- nano/node/bootstrap.cpp
- nano/node/cli.cpp
- nano/node/ipc.cpp
- nano/node/lmdb.cpp
- nano/node/logging.cpp
- nano/node/logging.hpp
- nano/node/node.cpp
- nano/node/node.hpp
- nano/node/openclwork.cpp
- nano/node/portmapping.cpp
- nano/node/rpc.cpp
- nano/node/testing.cpp
- nano/node/wallet.cpp
The constraint on this task was "Arguments should be forwarded so there's no performance penalty for calling this function in the event the logging entry is skipped due to timing."
This is achieved using forward references and perfect forwarding.
A new object `nano::logger` has been created with 2 new functions: `try_log` and `always_log`. The constructor for `nano::logger` contains a reference to a time object which denotes the minimum time that successive log calls can be made. So if it is set to 1ms, and a log call is made, another one won't be output (with `try_log`) until 1ms has passed, any made prior are ignored. `always_log` overrides this behaviour and always outputs. This is because there could be matching start/stop entries which can look strange if only 1 is output and there …
> Time limited logging

- nano/node/bootstrap.cpp
- nano/node/node.cpp
All receive_actions are already covered under stats, same with some other others where the log entry doesn't add anything extra, so log output has been removed. I have kept ones which give additional information as they can still be useful. Coupled with #1789 they should have a reduced impact on log file size.
> Don't output useless log file entries

- nano/node/rpc.cpp
MSVC has a limit of 128 nested blocks.
Also moved `rpc_handler` constructor definition to be with the other `rpc_handler` functions
> Replace nested if/else with map for no argument rpc_handler functions

- nano/core_test/node.cpp
- nano/core_test/peer_container.cpp
- nano/node/CMakeLists.txt
- nano/node/node.cpp
- nano/node/node.hpp
- nano/node/peers.cpp
- nano/node/peers.hpp
- nano/node/repcrawler.cpp
- nano/node/repcrawler.hpp
- nano/node/rpc.cpp
Overall changes:
* Reps are tracked by account instead of endpoint. This thus adds support for multiple reps per host, with an increase of total weight on livenet.
* Rep crawling is currently partly in peer container and partly in free standing functions. This patch puts all the functionality into a class.
Functional changes compared to v18:
* Stored peers are crawled at startup. In my tests, this obtains sufficient weight within a couple of seconds instead of up to a minute.
* Since the rep container is now separate from the peer container, the latter no longer has a `last_rep_request` index. The rep crawler grabs random peers in addition to iterating known reps periodically. Along with the changes mentioned below, this quickly finds reps on startup, even if there are no stored peers.
* …
> Improve representative crawler

- nano/node/cli.cpp
Return error if new wallet is encrypted & provided password invalid
Full import for new wallet with --force option instead of private keys import
> Improve CLI --wallet_import

- nano/node/lmdb.cpp
Add static assert for std layout in mdb_val constructors where we treat objects as blobs instead of serializing.
> Require standard layout in mdb_val

- nano/node/lmdb.cpp
To help diagnose release_assert reports from users (such as the comment in https://github.com/nanocurrency/nano-node/issues/1808)
Sample output:
_Could not open lmdb environment: 13, Permission denied_
> Output error if lmdb env cannot be opened

- nano/core_test/node.cpp
- nano/core_test/rpc.cpp
- nano/node/node.cpp
- nano/node/node.hpp
- nano/node/rpc.cpp
- nano/node/rpc.hpp
- nano/node/wallet.cpp
* improve add_confirmation_heights ()
* disable process_fork () for confirmed blocks
* replace active blocks check with confirmation status in RPCs pending*
* replace election::confirm_back () with add_confirmation_heights ()
* simplify search_pending for confirmed blocks
* merge RPC block_confirmed into block_info & blocks_info
> Confirmation height enhancement

- nano/core_test/rpc.cpp
- nano/node/rpc.cpp
Per request of @bbedward . This PR serves to add a `sorting` option to RPC "pending". It helps services which will now only need to get the first X blocks ordered by amount, to prioritize receiving the most important blocks instead of dust.
I decided to use `ptree::sort()` due to how cleaner it makes the code vs. having two branches as in `ledger ()`.
===== Wiki entry update =====
Boolean, false by default. Additionally sorts the blocks by their amounts in descending order.
> RPC pending - sort by amount

- nano/node/rpc.cpp
The rules for effective stake required for quorum may change and isn't obvious from the output of confirmation_quorum (it's the largest of online_weight_minimum and quorum_delta)
Adding `peers_stake_required` to make this obvious and allow for future changes to the rules without breaking clients.
> Add required stake to confirmation_quorum

- nano/node/rpc.cpp
- nano/node/rpc.hpp
- nano/node/rpcconfig.cpp
- nano/node/rpcconfig.hpp
Closes https://github.com/nanocurrency/nano-node/issues/1671
We've had reports of RPC requests sometimes taking 1 second before being handled. Some clients, such as curl (and Python wrappers), sends an `Expect: 100-continue` header for large requests (per rfc7231). These clients typically wait one second for the header response before sending the body (a workaround in curl is to use -H Expect:)
The PR also adds the ability to restrict request body sizes via `config.json`. The proposed default limit is 32MB (this must be large enough for services - opinions welcome)
> RPC 100-continue and max request size

- nano/node/blockprocessor.cpp
instead of elections only for bootstrap forks
> Start elections for all forks of unconfirmed blocks

- nano/core_test/rpc.cpp
- nano/node/rpc.cpp
Similar to #1748 but for accounts_pending.
===== Wiki entry update =====
Boolean, false by default. Additionally sorts each account's blocks by their amounts in descending order.
> RPC accounts_pending - sort by amount

- nano/core_test/peer_container.cpp
- nano/node/node.cpp
- nano/node/node.hpp
- nano/node/peers.cpp
- nano/node/peers.hpp
- nano/qt_test/qt.cpp
- Purging the peer_container
- Sending keepalives to nodes we haven't heard from
- Signaling the disconnect observer
This makes the logic around each easier to reason around and movable to different portions of the code.
> Separating the concepts of:

- nano/node/transport/tcp.cpp
- nano/node/transport/udp.cpp
Another place where clang format versions disagree. Pushing since it's just comments and having formatting oscillate is annoying.
> Add clang format guard in more lambdas

- nano/node/node.cpp
- nano/node/node.hpp
Master currently crashes in active_transactions::confirm_frontiers from time to time.
> Fix active_transactions/signature checker initialization order

- nano/core_test/CMakeLists.txt
- nano/core_test/websocket.cpp
- nano/node/CMakeLists.txt
- nano/node/node.cpp
- nano/node/node.hpp
- nano/node/nodeconfig.cpp
- nano/node/nodeconfig.hpp
- nano/node/websocket.cpp
- nano/node/websocket.hpp
- nano/node/websocketconfig.cpp
- nano/node/websocketconfig.hpp
Adds support for notifications via Websockets. This offers a more efficient callback mechanism for block confirmations, and allows for multiple listeners. As it's topic-based, filtering and additional events can be added in the future. Proper JSON is returned (the http callback returns stringified blocks). Comments on message formatting are most welcome. Note that the http callback is still supported.
Preliminary docs: https://github.com/cryptocode/notes/wiki/Websocket-support
Sample nodejs client: https://github.com/cryptocode/nano-websocket-sample-nodejs
> Websocket support

- nano/core_test/network.cpp
There was a race causing tcp_listener_timeout_keepalive to fail intermittently. The issue is that async_write's handler is sometimes called before the visitor is called in bootstrap. Effect is `connected == true`, but `connections.size ()` is still zero.
Fixed by waiting for the keepalive stat to be updated.
> Fix race in tcp_listener_timeout_keepalive

- nano/core_test/conflicts.cpp
- nano/core_test/ledger.cpp
- nano/core_test/node.cpp
- nano/lib/blocks.cpp
- nano/lib/blocks.hpp
- nano/lib/numbers.hpp
- nano/node/blockprocessor.cpp
- nano/node/node.cpp
- nano/node/node.hpp
- nano/node/rpc.cpp
- nano/secure/ledger.cpp
- nano/secure/ledger.hpp
A type alias in the same vein as nano::signature to improve readability and a new qualified_root 
function in `block` to construct the value.
> qualified_root type alias

- nano/node/ipc.cpp
As `size_response` is declared on the stack it may go out of scope before the `async_write` completion handler is called.
> Extend lifetime of size response in rpc handler

- load-tester/src/main.rs
These are just some things I noticed while looking at this area. When testing with small send counts this error message sometimes appeared:
```
Error: failed to check account xrb_31sstakuod4x3kkeiibi39hand6mgrtsmbmetwe8t9y7azgfirxp9m9u1crb info on primary node
caused by: Account not found
```
This is because sends are sent randomly to accounts, so it's possible that an account doesn't get a send so the `account_info` won't exist in the database when trying to find it afterwards. I now make sure that every account gets at least one send (although gave up trying to do it efficiently as I'm not familiar with Rust). From speaking to other members of the team, no one is that familiar with Rust so I think it would be good to re-write this into something else more like Python.
> Some improvements to load tester script

- nano/node/stats.cpp
fixed by creating case for enum error_socket_close
> Fix missed enum in switch

- nano/node/transport/udp.cpp
- nano/node/transport/udp.hpp
TSAN reported races in socket usage as well as unlocked access to the channels container in `max_ip_connections`
The call to `channels.socket.async_send_to` has been encapsulated in udp_channels (so the caller doesn't have to know about the mutex)
> TSAN: fix races in udp channels

- nano/node/transport/udp.cpp
The load-tester exposed this lock ordering bug:
IO thread 1:
: rpc::process -> TX WRITE LOCK -> ... -> udp::channels::size -> MUTEX LOCK
IO thread 2:
: ongoing_peer_store -> MUTEX LOCK -> TX WRITE LOCK
(load-tester still occasionally times out with the tool's defaults; reducing node count or increasing timeout helps, but there's no longer a deadlock)
> Fix lock ordering issue in udp_channels

- nano/node/cli.cpp
In mdb_store::initialize we now set the genesis account's open block as being confirmed (which makes sense). When clearing the confirmation heights we probably want the genesis account to go to 1 rather than 0 which is what this PR does.
> When clearing confirmation heights set the genesis account to be 1

- nano/node/repcrawler.cpp
- nano/node/repcrawler.hpp
The unlocked version of total_weight() was called where a lock is needed. Weight was also computed twice, now it's passed as an argument.
> tsan: Fix race in repcrawler and remove redundant weight computation

- nano/core_test/work_pool.cpp
Due to the random nature of a successful proof when generating pow this test can fail when comparing the time taken for 2 threads to find a valid proof even when 1 thread has a delay. I have made this delay more pronounced, which does increase the time taken to complete the test (100ms on my machine), but it seems worthwhile to do this to cause it to fail even more infrequently (pretty much 0)
> Reduce work.eco_pow intermittent failure rate

- nano/node/node.cpp
- nano/node/transport/udp.cpp
- nano/node/transport/udp.hpp
#1873 and #1876 fixed some issues in udp_channels (lock ordering causing load-tester to fail + tsan race reports), but they introduced another race.
Sockets are not thread safe and the recommended solution is to use strands.
Changes: Any access to the udp `socket` has to go through the strand, and bind_executor is used to also put the completion handler in the strand. This makes it safe to access the socket from the handler. 
Using strands means no more calling `socket.local_endpoint/is_open/close` or async initiating functions directly - `asio::post` is used for this. This makes it a bit awkward to do calls like socket.local_endpoint(..)  - as the caller would need a completion callback - so the local endpoint is put in a field in the constructor. The `stop` function then invalidates it …
> Use asio strands in udp channels

- nano/rpc/rpc_handler.cpp
Mac/Clang ASAN warning
```
[ RUN      ] rpc.wallet_history
SUMMARY: AddressSanitizer: stack-use-after-scope vector:639 in (anonymous namespace)::history_visitor::should_ignore_account(nano::uint256_union const&)
```
A default argument which is a temporary bound to const reference was assigned to a member variable and accessed later in another method `should_ignore_account`. However from the standard:
> A temporary bound to a reference member in a constructor’s ctor-initializer (§12.6.2 [class.base.init]) persists until the constructor exits
I have removed the default argument and just pass an empty std::vector in the one place utilizing the default argument.
> Fix ASAN warning in wallet.history

- nano/core_test/rpc.cpp
```
[ RUN      ] rpc.account_history
[1m/Users/user/Library/raiblocks/nano/core_test/rpc.cpp:1223:52:[1m[31m runtime error: [1m[0m[1mdowncast of address 0x611000050a40 which does not point to an object of type ‘nano::send_block’[1m[0m
[1m0x611000050a40:[1m[30m note: [1m[0mobject is of type ‘nano::state_block’[1m[0m
39 00 80 3c  b0 6a 2d 09 01 00 00 00  b0 31 1e a5 57 08 d6 a5  3c 75 cd bf 88 30 02 59  c6 d0 18 52
[1m[32m              ^~~~~~~~~~~~~~~~~~~~~~~[1m[0m
vptr for ‘nano::state_block’
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior
```
Just pass the block directly like all other tests do instead of trying to cast it.
> Fix ASAN warning in rpc.account_history

- nano/lib/numbers.cpp
```
[ RUN      ] uint128_union.decode_decimal
=================================================================
ERROR: AddressSanitizer: stack-use-after-scope on address 0x7ffeefbf7750 at pc 0x000105a92279 bp 0x7ffeefbf5ca0 sp 0x7ffeefbf5c98
```
From `nano::uint128_union::decode_dec ()`, this:
`auto result (integer_part.number () * scale + decimal_part.number () * boost::multiprecision::pow (boost::multiprecision::cpp_int (10), (scale_length - decimal_text.length () - 1)));`
is an expression template (the `decimal_part.number ()` and result from `boost::multiprecision::pow`) . It seems that anything used in conjunction with these expression templates needs to be kept in scope as only references are kept within. I have split up the expression into multiple parts.
> Fix ASAN warning for uint128_union.decode_decimal

- nano/lib/config.hpp
- nano/node/ipcconfig.hpp
- nano/node/websocketconfig.cpp
- nano/node/websocketconfig.hpp
beta and test nets currently share default port numbers, which makes rpc and other tests fail if a beta node or wallet is running. Also makes use of network_constants for ipc and websockets.
> Port config cleanup, allow running tests alongside beta node

- nano/node/voting.cpp
- nano/secure/common.cpp
- nano/secure/common.hpp
Colin realized we could remove the vote generator delay. Multiple hashes still got packed when I tested this on beta (with high tps it should still stuff 12 hashes into a v-b-h message)
Some confirmation height tests will fail intermittently until PR #1877 is merged.
> Remove vote generator delay

- nano/secure/common.cpp
- nano/secure/common.hpp
2 bugs:
First, it would crash at a `block_hash` variant:
```
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::bad_get> >'
what():  boost::bad_get: failed value get using boost::get
Aborted (core dumped) 
```
Now, the `block_hash` variant is correctly handled.
Second, only one block would be serialized (overwritten on top of the last one). Now it serializes a list of all blocks. Tested with `--vote_dump`
> Fix vote::to_json()

- nano/core_test/work_pool.cpp
This is a test I wrote, and wanted to try use `set_value_at_thread_exit` as I hadn't used it before. However it raised a TSAN warning when calling future.get (). I tried various things, but it seems that the thread needs to be finished before get () is called on the future, despite the example not doing this https://en.cppreference.com/w/cpp/thread/promise/set_value_at_thread_exit. I could simply just use set_value, but that's no fun :), and it at least shows an example of the apparent correct usage should someone require it in the future.
> Fix TSAN warning with work.eco_pow

- nano/node/node.cpp
- nano/node/node.hpp
I noticed this when running this CLI command `nano_node --network=live --debug_account_count` (Debug/Windows) but I'd imagine it will be caused by other commands depending on timing. It can take a while for the node to actually stop when it should be pretty instant. It was caused by the request loop, so I now check if `stopped` is true to break early out of some unnecessary processing.
> Remove delay exiting node in request processor

- nano/lib/ipc.hpp
- nano/node/ipc.cpp
- nano/node/ipcconfig.cpp
- nano/node/ipcconfig.hpp
- nano/rpc/rpc_handler.cpp
- nano/rpc/rpc_handler.hpp
- nano/rpc_test/rpc.cpp
Enables wallet_seed over a new IPC encoding. In addition to clients using the new encoding, a config flag must be set on each transport the client wants to use for this.
Based on #949 (only wallet_seed is used for now) and #1716
> Unsafe encoding in IPC

- nano/core_test/websocket.cpp
- nano/node/node.cpp
- nano/node/websocket.cpp
- nano/node/websocket.hpp
If the websocket server is active via config but there are no active subscriptions, currently the observer will still create and try to broadcast the block confirmation message.
A simple check would have been to go through all sessions and check if any topics are subscribed. However, since this would be done every time a new block arrives, I have added a map `topic -> subscription count` in the listener to do this lookup in constant time. I'm open to suggestions as I am not sure what the right pattern would be here.
Small test added for this as well.
> Websockets - check for subscriptions before proceeding

- nano/core_test/websocket.cpp
- nano/node/websocket.cpp
- nano/node/websocket.hpp
This adds per-subscription filtering options via an extra field in a subscribe action:
```json
{
"action": "subscribe",
"topic": "confirmation",
"options": {
"all_local_accounts": "true",
"accounts": [ "xrb_123...", "..." ]
}
}
```
Filtering happens after the message is built and is sent for broadcasting, with a bunch of O(1) checks for existance of accounts. We would have to change the dynamics of the websocket server quite a bit to handle it differently. Open to suggestions as usually or just pickup from this PR and improve!
Can add something to `core_test` if this seems ok.
Related: #1901
> Websockets - filtering options

- nano/core_test/websocket.cpp
- nano/node/node.cpp
- nano/node/websocket.cpp
- nano/node/websocket.hpp
Related: #1901 .
```json
{
"topic": "vote",
"time": "1554995525343",
"message": {
"account": "xrb_1n5aisgwmq1oibg8c7aerrubboccp3mfcjgm8jaas1fwhxmcndaf4jrt75fy",
"signature": "1950700796914893705657789944906107642480343124305202910152471520450456881722545967829502369630995363643731706156278026749554294222131169148120786048025353",
"sequence": "855471574",
"blocks": [
"6FB9DE5D7908DEB8A2EA391AEA95041587CBF3420EF8A606F1489FECEE75C869"
]
}
}
```
Added the ability to filter by representative as well, very similarly to the other filtering options. I think this one has no performance penalties, just a O(1) search in an unordered_set.
A good filter would also be `rebroadcasting_only` or a minimum weight. What do you think?
> Websockets - subscribe to votes

- nano/core_test/websocket.cpp
Simpler approach that creates a local `io_context` to call `run_one_for (deadline)` instead of using multiple threads with a deadline timer, avoiding data races.
> Websockets - Fix tests breaking with TSAN

- nano/node/wallet.cpp
if a block doesn't exist in the ledger its definitely not confirmed
Don't bother checking confirmation as that will assert if the block doesn't exist
Update ledger check to block_confirmed_or_being_confirmed to check ledger and confirmation_height_processor
> fix tests and update logic of work_watcher::run()

- nano/core_test/network.cpp
I couldn't reproduce this locally, however I could see an obvious timing issue with the test. It only checks that one of the node ledgers has changed rather than both. I have changed the test to be more in line with the other ones by waiting until the block is confirmed in the node before querying it.
> Fix confirmation_height.single test

- nano/core_test/websocket.cpp
Closing may throw on Windows; any close error can be ignored in the tests.
> Websocket tests: Use error_code when closing

- nano/node/lmdb.cpp
- nano/node/node.cpp
- nano/secure/common.cpp
- nano/secure/common.hpp
`not_an_account ()` is not thread-safe now, it cannot be called in the constructor of `ledger_constants` because there are global objects of it (and it will trigger an ASAN warning with CryptoPP globals not initialized yet). However it can just be moved out into a separate class and set in the constructor because there are relatively few users of it and they don't touch any globals. Ran ASAN on both core tests + daemon and no CryptoPP warnings.
> Make new random_constants class for not_an_account

- nano/core_test/ipc.cpp
- nano/node/ipc.hpp
- nano/rpc_test/rpc.cpp
Fixes 2 asan issues.
1 - The scope of default parameters to const refs does extend beyond the constructor, so pass it in explicitly instead (Edit: seems not to be fixed).
2 - Incorrect cast of a block in rpc.account_history
> Fix some asan rpc issues

- nano/node/json_handler.cpp
This was already fixed in #1887 but looks like the changes got removed (possibly in a refactor/merge error). The exact same changes were used, so I'm merging in straight away as a re-review shouldn't be necessary.
> Fix ASAN warning in wallet.history (again)

- nano/core_test/network.cpp
- nano/core_test/node.cpp
- nano/core_test/peer_container.cpp
- nano/node/json_handler.cpp
- nano/node/transport/udp.cpp
- nano/node/transport/udp.hpp
- nano/qt/qt.cpp
To solve some TSAN reports and encapsulate fields.
> Protect udp_channel members with a mutex

- nano/node/websocket.cpp
- nano/node/websocket.hpp
All thread unsafe operations of the websocket server should go through the strand.
`Shared objects: Unsafe. The application must also ensure that all asynchronous operations are performed within the same implicit or explicit strand. ` [Boost](https://www.boost.org/doc/libs/develop/libs/beast/doc/html/beast/ref/boost__beast__websocket__stream.html).
But I think handshaking does not have to go through the strand.
Tested on a high end Ubuntu 18 GCC8 Boost 1.70,  300 times all websocket.* options on TSAN and ASAN separately. @cryptocode  @SergiySW  wonder if it still happens to you.
> TSAN - Fix websocket tests

- nano/core_test/block_store.cpp
- nano/core_test/gap_cache.cpp
- nano/core_test/ledger.cpp
- nano/core_test/network.cpp
- nano/core_test/node.cpp
- nano/core_test/processor_service.cpp
- nano/core_test/versioning.cpp
- nano/core_test/wallet.cpp
- nano/core_test/wallets.cpp
- nano/nano_node/entry.cpp
- nano/nano_wallet/entry.cpp
- nano/node/lmdb.cpp
- nano/node/lmdb.hpp
- nano/node/wallet.cpp
- nano/node/wallet.hpp
- nano/qt_test/qt.cpp
- nano/rpc_test/rpc.cpp
- nano/secure/blockstore.cpp
- nano/secure/blockstore.hpp
- nano/slow_test/node.cpp
This enables long running read transactions to be broken up and reuse the same transaction object instead of creating a new one each time periodically which is more efficient as per the official [documentation](http://www.lmdb.tech/doc/starting.html#optim). This will help with some of the forthcoming transaction breakup tasks.
As read/write now return different concrete objects (to make use of RAII for automatic cleanup) they can no longer be specified by using a `bool` argument (which is a good thing imo). This is what most of the changes done are for.
It is currently possible to pass a read only transaction object to something that expects a write transaction, this is only apparent at run-time. This can now be made a compile-time constraint by specifying a `write_transaction`. …
> Allow long running read transactions to be broken up

- nano/rpc/rpc_connection.cpp
- nano/rpc/rpc_connection.hpp
Reports of stuck RPC. Based on community reports, Wesley tracked it down to IO threads waiting for header reads to complete. All handlers run in IO threads, so lots of requests could get it stuck. Reorganized the 100-continue header handling (which solves the slow large-request problems people were having) so it no longer waits on a promise. Hopefully this fixes the issue (unable to reproduce before and after though, hopefully community members can try this PR before merge)
> Fix regression introduced by 100-continue

- nano/secure/blockstore.hpp
@cryptocode wasn't sure if `if (value.mv_size != 0)` inside `nano::mdb_store::block_get ()` would be called if the block doesn't exist. `nano::mdb_store::block_account_height ()` returns a height regardless so it could return a garbage value in release mode (in debug it asserts). So to cover this I'm setting some default for the sideband data.
> Set defaults for block_sideband

- nano/lib/config.hpp
- nano/nano_node/daemon.cpp
- nano/nano_rpc/entry.cpp
- nano/nano_wallet/entry.cpp
- nano/rpc/rpc.cpp
- nano/rpc/rpc.hpp
- nano/rpc/rpc_connection.cpp
- nano/rpc/rpc_connection.hpp
When `nano_rpc` is used in-process it now gets passed network/data_path command line arguments so that it is in sync with `nano_node` should they not be the defaults.
Improve error message when `rpc_path` does not point to a valid file.
Removed unused `network_params` variables from some rpc code
> Pass command line arguments (network/data_path) to nano_rpc child process

- nano/nano_node/entry.cpp
This add a new CLI command `--debug_validate_ledger` which can be used to do some simple (currently) validation of the ledger to detect any problems.
@Ricki had an issue where the node was crashing but it gave no useful information. This ended up being because he opened the ledger in v18 (after syncing v19) and some accounts got added. Due to the extra `confirmation_height` in the `account_info`, the size of it inside the database was not correct which caused some error when reading.
@cryptocode had an issue using a ledger which had been used previously in-between to the change from sideband height open block being 1 from 0.
Both those (and some others) should now be detected. I'd imagine as further issues are found in the future they can be added here.
> Simple ledger validation CLI command

- nano/node/json_handler.cpp
Bug was found during beta net testing, if any error code was set before line [1279](https://github.com/guilhermelawless/nano-node/blob/2c3e79ea7bf2ccacf46c0c29f04b765ce3617727/nano/node/json_handler.cpp#L1279) it would be overridden by `nano::error_rpc::block_create_key_required`.
Suggest hiding whitespace changes to see the diff.
> Fix RPC block_create error getting overridden

- nano/core_test/block_store.cpp
- nano/node/lmdb.cpp
- nano/node/lmdb.hpp
- nano/node/node.cpp
- nano/node/node.hpp
- nano/node/wallet.cpp
- nano/node/wallet.hpp
The node should be incompatible with a future version. Currently it is possible to start a v18 node with a v19 ledger, while we cannot retrofit this to existing versions, any future ledger version will be incompatible with this one and so on.
`wallet_init` is unused so have gotten rid of it and pass `wallets_store_init` in its place.
There is a lot of unnecessary work done after there is a database initialization error in the `node::node` constructor, it is now checked at the start.
> Stop node when using an incompatible ledger

- nano/qt_test/qt.cpp
- nano/rpc_test/rpc.cpp
https://github.com/nanocurrency/nano-node/pull/1939
> Fix tests failing after PR#1939

- nano/core_test/node.cpp
- nano/node/lmdb.cpp
- nano/node/lmdb.hpp
- nano/node/node.cpp
- nano/node/wallet.cpp
CLI commands can currently open a write lock on the ledger database when they don't need to. When using `--fast_bootstrap` and aren't synced yet or if there is any other long write transaction running, simple commands like `nano_node --wallet_create` can end up taking a few minutes. A few places where writes were being used are now checked in a pre-pass by using a read transaction to see whether the write is actually required (after first initialization of the ledger, they generally aren't needed).
I found that the read transaction needs to be committed when opening databases (not sure why), but I've replaced abort with that. This is also what it is prior to #1951.
> Makes sure a write lock can be avoided when launching an inactive_node

- nano/core_test/node.cpp
- nano/lib/jsonconfig.hpp
- nano/node/node_rpc_config.cpp
It's reasonable practice to create backups of files which the user is allowed to modify if you are going to modify them. There were also multiple times during the v19 RC1 period where having the original config file beta testers were using before an upgrade would have been useful.
During any upgrades of the config a new file will be created, for instance: `config_backup_15571460497935531.json`
Note: It might look initially strange during upgrades from v18 as the new `rpc_config.json` will have an initial backup because the migration only copies things from the original `config.json`, all the new options for the rpc are done in an upgrade. This can be added to documentation as expected behaviour.
> Backup config files when upgrading

- load-tester/src/launch_node_and_rpc.rs
- nano/lib/rpcconfig.cpp
- nano/lib/rpcconfig.hpp
- nano/nano_node/daemon.cpp
- nano/nano_wallet/entry.cpp
- nano/node/node_rpc_config.cpp
- nano/node/node_rpc_config.hpp
- nano/rpc/rpc_request_processor.cpp
- nano/rpc_test/rpc.cpp
It wasn't very clear that some of the config options were only applied in certain situations (i.e depending on how the rpc server was run; in-process, child process or out of process). I have made it a bit clearer. The `config.json` file for instance a new config node (child_process):
```
"rpc": {
...
"child_process": {
"enable": "false",
"rpc_path": "C:\\Users\\Wesley\\Documents\\raiblocks\\build\\Debug\\nano_rpc.exe"
}
}
```
This only lists things which are `child_process` specific. If enable is false (default) then it uses the in-process RPC.
`rpc_config.json` similarly has a new config node for options specific for an rpc server in a different process (child/out of process) rather than being in the main rpc config node:
```
"process": {
"ipc_port": "56000",
"num_ipc_connections": "4" …
```
> Add specific rpc process config options

- load-tester/src/launch_node_and_rpc.rs
- nano/lib/rpcconfig.cpp
- nano/lib/rpcconfig.hpp
- nano/nano_rpc/entry.cpp
- nano/rpc_test/rpc.cpp
#1977 moved a couple config options to a new rpc process config node, `io_threads` should have been moved as well.
> Move io_threads to rpc process config node

- nano/core_test/peer_container.cpp
- nano/node/transport/udp.cpp
- nano/node/transport/udp.hpp
We had a crash on master we suspected stemmed from unsynchronized access to a MI container, but it seems everything is protected.
However, `udp_channels::modify` was empty and the actual modification happened separately. This seems like a likely cause. Added a callback from which the modifications are done.
> Add modify callback to prevent violating boost multiindex invariants

- nano/node/json_handler.cpp
- nano/rpc_test/rpc.cpp
- Adds value + multiplier to `work_generate`
- Changes all "value" semantics to "difficulty", per [suggestion](https://github.com/nanocurrency/nano-node/pull/1981#issuecomment-492190033). This affects `work_generate` and `work_validate` documentations.
- Makes sure to have high precision (`double`) in all cases, which includes `active_difficulty`
> Finish up difficulty/multiplier semantics in RPC work_generate and work_validate

- nano/lib/blocks.cpp
- nano/lib/blocks.hpp
- nano/lib/numbers.cpp
- nano/lib/numbers.hpp
- nano/lib/work.cpp
- nano/node/json_handler.cpp
- nano/rpc_test/rpc.cpp
Reported by @cryptocode , thanks.
`{"action": "work_validate", "work":"4f4a0cfb4a25dc78", "hash":"0000000000000000000000000000000000000000000000000000000000000002", "difficulty":"000000000000001"}`
Before:
```json
{
"valid": "0",
"difficulty": "82ddbf2c0bd1ae98",
"multiplier": "3.0484946624529728e-08"
}
```
Now:
```json
{
"valid": "1",
"difficulty": "82ddbf2c0bd1ae98",
"multiplier": "0.000000030484947"
}
```
---
Note valid 1 (c6d7f18) and the format fix. Precision is 15 decimal cases, even with higher difficulties.
> Work multiplier format and RPC work_validate fix for lower difficulties

- nano/nano_node/daemon.cpp
The rpc path change didn't compile on macos with boost 1.69
> Update config path on macos/boost 1.69

- nano/node/bootstrap.cpp
- nano/node/bootstrap.hpp
tsan reported this (the separate mutex to protect the observers is to prevent a deadlock)
> Fix race when notifying bootstrap initiator listeners

- nano/core_test/socket.cpp
Thanks to @SergiySW for reporting and @wezrule for finding https://developercommunity.visualstudio.com/content/problem/1997/constexpr-not-implicitely-captured-in-lambdas.html
> Add unnecessary lambda capture to please VS2017

- nano/nano_node/entry.cpp
`--debug_validate_ledger` was added in #1956 but deemed unnecessary by the existing `--debug_validate_blocks`. This has instead been extended to check the `confirmation_height` now.
> Remove unnecessary --debug_validate_ledger CLI option

- nano/node/bootstrap.cpp
The current implementation will send 1 too many items, since count starts at 0.
> Fix off by one error in frontier req server

- nano/nano_wallet/entry.cpp
- nano/node/daemonconfig.cpp
- nano/node/logging.cpp
- nano/node/nodeconfig.cpp
Uses the pattern of returning `version_a < json_version ()` everywhere, which should be less error-prone/less code. Also moves the network variable within the ifdef where it's used.
> Clean up json upgrade code/unused variables

- nano/core_test/difficulty.cpp
- nano/load_test/entry.cpp
- nano/rpc/rpc_connection_secure.cpp
- nano/rpc/rpc_connection_secure.hpp
- nano/rpc/rpc_secure.cpp
The secure RPC build (using `-DNANO_SECURE_RPC=ON`) is failing due to a parameter no longer being used.
Have also fixed a couple other MAC warnings.
> Fix RPC secure build

- nano/load_test/entry.cpp
There appears to be some issues executing `std::system` multiple times in different threads (affects Mac/boost 1.69 which cannot use `boost::process`). Managed to find a solution using a single thread with multiple `std::system` commands in the background (with `&`)
> Fix load tester for mac with boost 1.69

- nano/node/socket.cpp
Leftover from debugging, was hit during testing of the TCP live message PR. The assert should be removed - async_read will just fail with operation_aborted if the socket is closed.
> Remove debugging assert from socket

- nano/core_test/network.cpp
- nano/core_test/testutil.hpp
- nano/rpc_test/rpc.cpp
The `std::stringstream` used to redirect `cerr` is not thread safe as it can be modifed when logging is done in the background while we are trying to read from it. I've wrapped it in a boost sink which gives exclusive access now with a mutex, this is only used in tests. I also don't think it is thread-safe to add a sink on the fly so am doing this at the start of the test as well.
Add more blocks to use in `rpc.confirmation_height_currently_processing` to prevent it failing when run under ASAN.
> Fix TSAN error with test confirmation_height.conflict_rollback_cemented

- nano/node/json_handler.cpp
difficulty_threshold to network_minimum
difficulty_active to network_current
network_minimum is the minimum required difficulty for the block to have valid work
network_current is the current 5min trended average of the active_transactions adjusted_difficulty
> Rename active_difficulty RPC response

- nano/core_test/active_transactions.cpp
- nano/node/active_transactions.cpp
fixed should_flush to properly handle dropping if active.size () >=4 inclusively
fix timing and logic in prioritize_chains.
> active_transactions.prioritize_chains timing fix

- nano/node/transport/udp.cpp
filtering data for DoS purposes. Packet logging should be required
> Decrease logging level for "Reserved sender" message

- nano/node/json_handler.cpp
and could go out of scope before the callback was called
copy into lambda instead
> generate difficulty was passing hash by ref

- nano/core_test/websocket.cpp
- nano/node/websocket.cpp
- nano/node/websocket.hpp
Fixes intermittent test failures, as well as buffer life times issues. The IO mutex is removed to follow the pattern of the TCP socket class where everything goes through a strand. Finally, the session cleanup is moved away from message broadcast; this should improve performance a bit if there are many clients.
> WebSocket fixes and improvements

- ci/test.sh
TIMEOUT_DEFAULT=180 (core_test takes longer than it used to and can sometimes timeout before completion)
retry loop initialized to work until 12-31-2019 23:59:59 UTC
shortened wait for socket cleanup
> Update test script

- nano/rpc_test/rpc.cpp
@SergiySW found this error, I was unable to reproduce with clang 7, 8 or gcc 7 but he has tested a patch I provided and confirmed that the error is now gone.
> Fix TSAN error for the rpc.database_txn_tracker test

- nano/core_test/active_transactions.cpp
remove unused &wallet
delay_frontier_confirmation_height_updating to keep unconfirmed transactions in ledger from getting re-added to active_transactions
> active_transactions test cleanup

- nano/lib/errors.cpp
- nano/nano_node/entry.cpp
- nano/node/json_handler.cpp
to prevent possible OpenCL validation loop
https://github.com/nanocurrency/nano-node/blob/master/nano/node/openclwork.cpp#L698
work_validate is invalid for difficulty < threshold
> Set minimum difficulty for RPC "work_generate"

- nano/core_test/active_transactions.cpp
counter is fully guarded now, no need to sleep
> remove sleep from test

- nano/core_test/testutil.hpp
@SergiySW found an ASAN warning when running the `confirmation_height.conflict_rollback_cemented` test. The `const char *` does not appear to be null terminated. Cannot use `std::stringstream::read` as it expects a non-const char array and would prefer not to introduce a `const_cast`. It's only used in tests so just going to construct a new string of the expected size.
> Update stringstream test sink to bounds check the strings

- nano/core_test/websocket.cpp
- nano/node/node.cpp
- nano/node/websocket.cpp
- nano/node/websocket.hpp
- Change variable and method names from "subscription" to "subscriber" in general
- (bug fix) Do not increase subscribers when re-subbing to the same topic, instead update the current one
- (fix) Do not output an error to log if the error code is EOF (session closed cleanly)
- Move increase/decrease_subscriber_count methods to private, and make `session` a friend of `listener`. I tried to make only the 2 functions that need to access them as friends, but one of them is private. Any alternative?
- Add a getter for `subscriber_count` , useful only in the new test for now but you never know.
> Websockets: prevent re-sub

- nano/core_test/core_test_main.cc
- nano/lib/blocks.cpp
- nano/lib/blocks.hpp
- nano/nano_node/entry.cpp
- nano/nano_wallet/entry.cpp
- nano/node/wallet.cpp
- nano/qt_system/entry.cpp
- nano/qt_test/entry.cpp
- nano/rpc_test/entry.cpp
- nano/slow_test/entry.cpp
When profiling bootstrapping for only 30 seconds, there is [50MB](https://imgur.com/ys1XEmM) of heap memory allocated in `nano::block::deserialize_block` this has now been [eliminated](https://imgur.com/Knwm9K4). Instead of many smaller allocations used frequently, a memory pool per block type is reused. Requesting heap memory is also slow as it requires an OS call which can take an indeterminate amount of time, so there should be a performance gain as well, although I have not quantitatively measured this.  There will be longer term benefits as well because there will be less fragmentation of memory.
Note from the documentation:
> The boost::singleton_pool is thread safe if there is only 1 thread running before main and 1 thread running after main. The underlying pool constructed by the …
> Use a memory pool to reduce block deserialization heap usage

- nano/core_test/node.cpp
- nano/node/nodeconfig.cpp
- nano/node/nodeconfig.hpp
- nano/node/voting.cpp
Puts back the delay logic, but with a lower (and now configurable) delay based on load testing performed by @guilhermelawless (thanks!). Adds a unit test to verify that bundling occurs.
> Add configurable vote generator delay and bundling test

- nano/node/node.cpp
- nano/node/node.hpp
While checking for heap memory allocations there is a lot in the [gap_cache::add](https://imgur.com/69Of03U) function (default `std::unordered_set` constructor which sets up the initial hash table). The number of voters is quite small so I decided to benchmark if using a `std::vector` would offer any benefits. As the number of voters gradually increases, where it checks for existing `nano::account` objects and iterates over the whole collection each time, I recorded an equivalent scenario at various intervals with 2 different compilers:
http://quick-bench.com/psAI43n2tRg9ZLw4AER3cehYXJs
| Voters | Clang 7  | gcc 8.2 |
| ------- | ------------- | ------------- |
| 5 | 1.9x  | 3.2x |
| 20 | 2.4x  | 4.3x  |
| 100 | 2.1x | 13x  |
| 255 | 1.6x  | 27x |
The **x** denotes how many times faster …
> Change gap cache voters to use a vector

- nano/node/active_transactions.cpp
- nano/node/node.cpp
- nano/node/node.hpp
The wallet depends on confirmation_height_processor, and search_pending sometimes calls it before the node is fully constructed, causing a segfault.
> Fix initialization order bug in nano::node

- nano/node/network.cpp
> Update broadcast_confirm_req to use confirm_req by hash

- nano/node/bootstrap.cpp
- nano/node/node.cpp
- nano/node/node.hpp
On Windows (at least) when running the tests it would often crash on `node.fork_bootstrap_flip` among other tests due to a mutex being locked which is already locked higher up in the stack. It is caused by `bootstrap_initiator.stop ()` being called while the mutex is locked before the `attempt = nullptr` call. The `attempt` is holding the last reference to the `node` shared_ptr which may already have been stopped by the `system::~system` destructor which explicitly calls `node->stop ()`. It then eventually calls `bootstrap_initiator.stop ()` which leaks to a deadlock. There's probably a few ways to solve this, but this could be a problem with other node members (I have seen similar errors before) so I decided to add a check in `node::stop` to see if it has been stopped already before …
> Fix deadlock in tests

- nano/node/common.cpp
- nano/node/network.cpp
- nano/node/network.hpp
Use header extensions count instead
> Remove count byte from confirm_req by hash

- nano/node/bootstrap.cpp
- nano/node/bootstrap.hpp
Following on from #2043 I am still getting a deadlock on Windows from a similar issue where the last `node` shared_ptr reference is freed while holding the mutex of `bootstrap_initiator` and the `~bootstrap_initiator` destructor is implicitly called (and hence `stop`) which then has the same problem as before as it then locks the same mutex while already holding it. Made `stopped` a `std::atomic<bool>` so that it can be checked without locking the mutex. The `thread` can already be joined, so have moved this inside the `stopped` function (when `stopped` is false) to avoid an already joined error.
> Fix deadlock in tests (Continued)

- nano/core_test/node.cpp
- nano/node/active_transactions.cpp
- nano/node/active_transactions.hpp
@SergiySW noticed a low number of frontiers being prioritized despite iterating over a lot of accounts with uncemented blocks. This turned out to be because they had the same number of uncemented blocks and were being overwritten because a `std::set` was used and this doesn't allow duplicates. Using a `boost::multi_index` container now as it also makes sense to have efficient account searching when needing to update the uncemented account should it change inbetween iterating. Updated the test to check accounts with the same number of uncemented blocks, and also check that modifying existing accounts works correctly.
> Handle accounts which have the same number of uncemented blocks when prioritizing frontiers

- nano/node/transport/tcp.cpp
- nano/node/transport/udp.cpp
While investigating a long held lock in vote processor, a few things popped up. This PR reduces lock time in UDP ongoing_keepalive the same way it's already done for TCP.
set_last_packet_sent removed since it's already called in channel->send (can you verify this is correct @SergiySW?)
Also removes a left-over weak_ptr.
> Reduce lock time in UDP ongoing keepalive

- nano/core_test/node.cpp
- nano/node/active_transactions.cpp
- nano/node/active_transactions.hpp
- nano/node/json_handler.cpp
- nano/node/nodeconfig.cpp
- nano/node/nodeconfig.hpp
defaults to maintain existing behavior 2048
update tests for v17 and upgrade path
rename variable to confirmation_history_size to be more accurate
> Configurable confirmation history container

- nano/node/json_handler.cpp
- nano/rpc_test/rpc.cpp
RPCs [ledger](https://github.com/nanocurrency/nano-node/wiki/RPC-protocol#ledger) and [unopened
](https://github.com/nanocurrency/nano-node/wiki/RPC-protocol#unopened)
Suggested by @renesq , this is an alternative to pagination for lower powered nodes who want information about the ledger (and helps the scalability of this command in the future).
In both cases, the optional `count` is still honored.
Documentation update needed.
> Add threshold optional to RPC unopened and ledger

- nano/node/json_handler.cpp
- nano/rpc_test/rpc.cpp
Wiki markup:
**INCOMPLETE** - needs to be updated with latest changes
---
Retrieves a json representations of **blocks** with block **account**, transaction **amount**, block **balance**, block **height** in account chain, block local modification **timstamp**, block **confirmation status** (since version 19.0), **subtype** (for state blocks since version 19.0).
Starting from version 19.0, **blocks_not_found** is an additional field in the response with the blocks that were not found locally. Before this version, an error would occur instead.
Request
```json
{
"action": "blocks_info",
"hashes": ["87434F8041869A01C8F6F263B87972D7BA443A72E0A97D7A3FD0CCC2358FD6F9", "0000000000000000000000000000000000000000000000000000000000000001"]
}
```
Response:
```json
{
"blocks" : { …
```
> Add blocks_not_found in RPC blocks_info response rather than an error

- nano/lib/stats.cpp
- nano/lib/stats.hpp
- nano/node/node.cpp
- nano/node/node.hpp
When running Clang/TSAN I get the following:
https://gist.github.com/wezrule/279062783ed1ed2a2066ba5c79db0b83
What appears to happen is that the last `std::shared_ptr<nano::node>` reference gets released by an `alarm` operation which then calls the ~stat destructor. This modifies the `map` (unprotected) and at the same time a packet is processed and a `stat` is trying to be incremented. I don't think this is the fault of stats rather the slightly random nature where the last `node` shared_ptr reference is released which can cause problems in quite a few areas. But as this is the one that TSAN is warning about I have fixed it. Just adding a `stop` variable/function to prevent modifying stats when closing down the node. Have moved stats higher up the member list as most things have a …
> TSAN error for send_node_id_handshake test

- nano/core_test/active_transactions.cpp
- nano/core_test/node.cpp
- nano/node/active_transactions.cpp
- nano/node/active_transactions.hpp
- nano/node/nodeconfig.cpp
- nano/node/nodeconfig.hpp
remove transaction counter and associated tests
only flush if roots.size() >= active_elections_size
active_elections_size added to config and re-factor simplified should_flush
update config v17 and upgrade path tests
ensure active_elections_size is 250 or greater
> active_transaction.roots bounding by config instead of confirmation rate

- nano/core_test/node.cpp
- nano/node/active_transactions.cpp
- nano/node/active_transactions.hpp
- nano/slow_test/node.cpp
#2053 changed the collection used for prioritizing frontiers to be a `boost::multi_index` container, but was iterating over the default (wrong) index afterwards. There's not really a way to test this as the active roots has no "insertion" order, I do however check that the `roots` does contain the expected frontier hashes though.
I've also modified the `prioritize_frontiers_for_confirmation` so that instead of stopping iterating when the container is full, it continues and replaces the frontier with the lowest amount of uncemented blocks with higher ones.
> Use correct index when iterating prioritized frontiers

- nano/node/wallet.cpp
Fix TSAN error found when running the `wallet.send_race` test:
https://gist.github.com/wezrule/409a4ad962e36f18c4f6c446232f2803
The issue is that we don't protect accesses to the `block` elements while iterating or check whether the `work_watcher` has been stopped where the blocks container has been modified.  I am now copying some members and checking for `stopped` when it's not possible to do so.
> Fix TSAN error with work_watcher

- nano/rpc_test/rpc.cpp
Running valgrind on rpc_tests come up with a failure:
https://gist.github.com/wezrule/217fbebde0b68394391feb18d35fbd92
This just seems to be because the test can't complete due the deadline timer not being long enough when running under valgrind. 60 seconds seems to be sufficient on my VM
> [Valgrind] Increase deadline timer in the rpc.simultaneous_calls test to account for valgrind slowness

- nano/node/websocket.cpp
json on Discord pointed out the confirmation_type field is at the level above the message node. Makes more sense to put it in the message.
> Move WebSocket confirmation_type into message

- nano/core_test/active_transactions.cpp
- nano/core_test/conflicts.cpp
- nano/core_test/ledger.cpp
- nano/core_test/network.cpp
- nano/core_test/node.cpp
- nano/node/active_transactions.cpp
- nano/node/active_transactions.hpp
- nano/node/node.cpp
- nano/node/node.hpp
- nano/node/nodeconfig.hpp
- nano/node/testing.cpp
- nano/node/testing.hpp
- nano/rpc_test/rpc.cpp
- nano/slow_test/node.cpp
to simplify code and allow different flags usage in tests, i.e. disable bootstrap or UDP
> Use node_flags for delay_frontier_confirmation_height_updating

- nano/node/active_transactions.cpp
- nano/node/json_handler.cpp
- nano/node/network.cpp
There are 2 copies of the blocks `deque` per iteration, and potentially 1000 iterations (`rebroadcast_bundle` max size) for each call to `flood_block_batch` from `active_transactions::request_confirm`. Profiling CPU cycles on the node over a random segment for a few seconds (it must have been in this loop at the time) showed 36% of the time was spent in this function:
https://imgur.com/1wiQDNn
I didn't expect it to be this high, but this was on a Debug build at the time (RelWithDebInfo give more accurate results) so iterator debugging probably played some part, but it's a suitable optimization none-the-less.
Removed an initial copy from the RPC calls as well while I was at it.
> Remove copies of blocks container from network::flood_block_batch

- nano/core_test/network.cpp
- nano/node/confirmation_height_processor.cpp
- nano/node/confirmation_height_processor.hpp
- nano/node/node.cpp
There were reports of duplicates found in the callbacks, and this was cause by self sends and sends to accounts who sent back to the originating account. While this didn't compromise the actual confirmation heights being set it did extra processing for no reason and in the observer multiple callbacks for the same inactive blocks could be sent. This has been rectified by having a separate "iterated" height in addition to a pending confirmation height and checking this. I've updated all confirmation_height tests to check callback counts and a new test to check for the case where a block was being confirmed and it iterates over a block which was voted on previously and added to pending_confirmation_height. So the callback is called after the election, then it is seen as inactive when it gets …
> Fix duplicate iterating in conf height processor with self and circular sends

- nano/node/active_transactions.cpp
- nano/node/active_transactions.hpp
- nano/node/json_handler.cpp
- nano/rpc_test/rpc.cpp
- Optional `include_trend` returns a copy of `active.multipliers_cb` which has the most recently added difficulties in front.
- Adds a test for `rpc.active_difficulty`.
Example response
```json
{
"network_minimum": "ffffffc000000000",
"network_current": "ffffffc1816766f2",
"multiplier": "1.024089858417128",
"difficulty_trend": [
"1.156096135149775",
"1.190133894573061",
"1.135567138563921",
"1.000000000000000",
"1.000000000000000",
"1.000000000000000",
"1.000000000000000",
"1.000000000000000",
"1.000000000000000",
"1.000000000000000",
"1.000000000000000",
"1.000000000000000",
"1.000000000000000",
"1.000000000000000",
"1.000000000000000",
"1.000000000000000",
"1.000000000000000",
"1.000000000000000",
"1.000000000000000",
"1.000000000000000"
]
}
```
> Optional include_trend for RPC active_difficulty

- nano/node/nodeconfig.cpp
#2028 puts back a vote delay, but it's likely ineffective on some RC installations since we don't have upgrade paths for RC's and not everyone updates the config manually/generate new ones. With this PR, the node will use the default delay if missing in config so everyone's using a delay in the next RC.
> Use default vote_generator_delay if missing (for RC updates)

- nano/node/socket.cpp
- nano/node/transport/tcp.cpp
My log had a lot of Disconnecting from 0.0.0.0... messages. Turns out it's logging as timeout when remote has already closed, thus the endpoint is invalidated. Also prevents connecting to the default endpoint (0.0.0.0:0), which bootstrap_peer returns if there isn't a suitable channel.
> TCP: Don't connect to or log invalid peers

- nano/qt/qt.cpp
- nano/qt/qt.hpp
There's already an rpc for this, but this is convenient when debugging via the Qt wallet
> Add ability to clear stats from Qt wallet

- nano/core_test/node.cpp
- nano/lib/stats.cpp
- nano/lib/stats.hpp
- nano/node/node.cpp
The observer stats facilitate debugging callbacks and websockets. The subtotal for stats "observer/confirmation*" should match the stat "confirmation/blocks_confirmed" if everything works as expected (notification is async so numbers may be slightly out of sync for short periods of time)
If a websocket client has a different count, it indicates a bug in websockets, the external client, or the configuration/subscription (though beware intermittent network issues may cause lost messages as WS doesn't guarantee delivery; a queue system like mqtt is needed for that)
> Add observer stats for confirmations

- nano/node/lmdb.cpp
- nano/node/lmdb.hpp
- nano/node/wallet.cpp
- valgrind/valgrind.h
I researched various options that we might be able to use to improve some performance, and this seemed quite useful. From `lmdb.h` for MDB_NOMEMINIT:
>Don't initialize malloc'd memory before writing to unused spaces in the data file. By default, memory for pages written to the data file is obtained using malloc. While these pages may be reused in subsequent transactions, freshly malloc'd pages will be initialized to zeroes before use. This avoids persisting leftover data from other code (that used the heap and subsequently freed the memory) into the data file. Note that many other system libraries may allocate and free memory from the heap for arbitrary uses. E.g., stdio may use the heap for file I/O buffers. **This initialization step has a modest performance cost so some applications …
> Use the MDB_NOMEMINIT flag with the ledger db environment

- nano/core_test/network.cpp
- nano/core_test/node.cpp
- nano/node/CMakeLists.txt
- nano/node/active_transactions.cpp
- nano/node/blockprocessor.cpp
- nano/node/blockprocessor.hpp
- nano/node/confirmation_height_processor.cpp
- nano/node/confirmation_height_processor.hpp
- nano/node/node.cpp
- nano/node/node.hpp
- nano/node/nodeconfig.cpp
- nano/node/nodeconfig.hpp
- nano/node/write_database_queue.cpp
- nano/node/write_database_queue.hpp
- nano/slow_test/node.cpp
This PR does a few things:
1 - Introduces a minimum time when there are blocks pending confirmation height to batch writes, currently set to 50ms but can be change via a new config option `conf_height_processor_batch_min_time`
2 - Checks whether there are other txn writes pending (currently just `process_batch`). If there is and the confirmation height processor has other blocks pending confirmation height then it will continue processing them until it runs out or the `process_batch` write txn lock is finished. 
3 - (Unrelated) Removing the assert in `nano::active_transactions::add`. We have multiple checks for elections but I still think implicit confirmations can cause issues here (@cryptocode had run into the `assert`) and I think the following can happen:
We check if block is …
> Improve batching multiple blocks pending confirmation height processing

- nano/core_test/network.cpp
- nano/core_test/node.cpp
- nano/node/nodeconfig.cpp
- nano/node/nodeconfig.hpp
- nano/node/voting.cpp
- nano/node/voting.hpp
Adds a `vote_generator_threshold` config option ( between 1 and 12 ) and new logic for the vote generator loop. The goal is to make it behave like a deadline timer which is reset when new hashes arrive, and when fired sends the hashes.
- The loop still waits on a condition_variable for up to `vote_generator_delay` (50ms default)
- The cv can be notified by `vote_generator::add` when a new hash arrives, which makes the loop **not** send the votes yet, but wait for more. This happens when hashes are arriving fast.
- When the cv is notified, that means hashes are not arriving sufficiently fast, so the loop sends the votes
The addition of `vote_generator_threshold` helps in configuring what the "high load threshold" should be.
Approximate equation (assumes constant rate during sleep time): …
> Fix vote_generator loop inconsistency during high load

- nano/core_test/websocket.cpp
- nano/node/active_transactions.cpp
- nano/node/active_transactions.hpp
- nano/node/node.cpp
- nano/node/node_observers.hpp
- nano/node/websocket.cpp
- nano/node/websocket.hpp
This implements #2080 - monitors changes in difficulty and notifies via web socket if the active difficulty changes
> Web socket subscription for active difficulty

- nano/node/active_transactions.cpp
Follow-up to #2091 so that observers are always notified (see discussion in original PR)
> Always notify on active difficulty updates

- nano/core_test/node.cpp
- nano/node/active_transactions.cpp
- nano/node/active_transactions.hpp
- nano/node/blockprocessor.cpp
- nano/node/election.cpp
- nano/node/election.hpp
- nano/node/json_handler.cpp
There used to be a vote announcement loop, but that one is now mostly about vote solicitation. I think renaming accordingly makes the code a bit easier to follow. 
I haven't updated the two confirmation RPCs which uses "announcements" as that would be a breaking change. The corresponding variable names are retained as well in the json handler.
`announcements_per_interval` wasn't used and is thus removed.
> Use confirmation request count instead of announcement term

- nano/node/transport/tcp.cpp
message can be processed in background after tcp channel was closed
> Improve assert in tcp_channels::process_message ()

- nano/node/network.cpp
Batch confirm_req by hash/root:
* removed increased delay for each iteration. It could cause much longer confirmations without change (+50 ms each iteration)
* larger max reps limit should allow more aggressive & faster confirmation
* better load balancing across multiple representatives in each iteration
> Improve broadcast_confirm_req_batch delays and max size

- nano/node/bootstrap.cpp
Possible because of background tasks delays. Can affect only Debug builds
> Improve assert in TCP node_id_handshake

- nano/nano_node/daemon.cpp
- nano/node/confirmation_height_processor.cpp
- nano/node/ipc.cpp
The node sometimes takes a few minutes to shutdown when using the `stop` action RPC command. Various things are still run in the background which I tried to explicitly check for and was able to "mostly" get it to shutdown within a couple seconds, but depending on timing some things may send a request and then just timeout waiting for it. I now just call `io_ctx.stop ();` as a "catch all" to explicitly cleanup all the sockets after a few seconds if it hasn't happened already.
I've also optimised the conf height processor slightly by checking if it has been stopped while traversing an account chain in case it is on a very long one.
> RPC stop action can take a long time to close the node down

- nano/lib/errors.hpp
- nano/lib/ipc_client.cpp
- nano/rpc/rpc.cpp
- nano/rpc/rpc_connection.cpp
- nano/rpc/rpc_connection.hpp
- nano/rpc/rpc_connection_secure.cpp
- nano/rpc/rpc_connection_secure.hpp
- nano/rpc/rpc_handler.cpp
- nano/rpc/rpc_handler.hpp
- nano/rpc/rpc_secure.cpp
When running the `nano_rpc` executable directly the following TSAN warning (with boost 1.7, not 1.67) is generated:
https://gist.github.com/wezrule/e6f7a800b654eb6de4ccbbabc90b0ca6
A constructor has been created in the `error` class which takes a `boost::system::error_code` directly which has solved this (an offhand suggestion by @cryptocode).
When making concurrent/simultaneous requests using the child/out-of-process RPC (although strangely in-process which calls the same code works fine), another TSAN warning was generated. It is just a local variable holding a pointer as a string, yet `boost::format` complains about concurrent use:
https://gist.github.com/wezrule/0ba94c6f1c46f9933525380c0b0a7ff3
I don't fully understand (could be a false positive?), but creating a new one via a …
> Strange TSAN warnings running nano_rpc & making simultaneous requests

- nano/node/active_transactions.cpp
@SergiySW noticed that the roots added in `confirm_frontiers` won't be used until the next request loop so moved them to the top.
> Move confirm_frontiers higher up request loop

- nano/lib/work.cpp
- nano/load_test/entry.cpp
- nano/nano_node/daemon.cpp
- nano/nano_rpc/entry.cpp
- nano/node/vote_processor.cpp
- nano/secure/utility.cpp
Very little is allowed in signal handlers, specifically only async-signal-safe functions. This is because code can be halted at any point, if a mutex is already locked elsewhere for instance this will result in deadlock. TSAN gives many warnings when closing the daemon when the SIGTERM/SIGINT and SIGSEGV signals are raised. Instead of calling our application specific code in the signal handler I just stop the io_context (which is done in a few asio examples), the rest of the cleanup code is now done by checking a `sigatomic_t` variable after the asio loop has finished.
Now also using specific Linux file descriptor commands which are known to be async-signal-safe (looked at how the boost stacktrace dump does it as it states signal safety) in the segfault/abort signal handler.
(Unrelated) I …
> [TSAN] Use only async signal safe functions in signal handlers

- nano/core_test/block_store.cpp
- nano/node/cli.cpp
- nano/node/lmdb.cpp
We want the genesis account to have a minimum cemented count of 1 at all times. This is done elsewhere but not during the initial upgrade.
> Set genesis account to have a confirmation height of 1 after initial upgrade

- nano/core_test/difficulty.cpp
- nano/lib/config.cpp
- nano/lib/config.hpp
- nano/node/lmdb.cpp
Valgrind is noisy with tests which use `ASSERT_DEATH_IF_SUPPORTED` as it basically forks a new process which is killed. I think it's better we don't output this during valgrind runs.
> [Valgrind] Check if running under valgrind before doing death tests

- docker/node/Dockerfile
Building the docker image was quite slow, investigated and found it can be sped up by specifying the number of jobs to `make`, at least of machines with many cores. Consensus seems to be use cores + 1 https://stackoverflow.com/questions/3025587/whats-best-value-for-make-j
> Improve docker build speed on multi-core machines

- nano/lib/plat/linux/debugging.cpp
The docker deployment build gives a warning (which is now turned to an error):
`/tmp/src/nano/lib/plat/linux/debugging.cpp:32:40: error: ignoring return value of 'ssize_t write(int, const void*, size_t)', declared with attribute warn_unused_result [-Werror=unused-result]
::write (file_descriptor, "Name: ", 6);`
This doesn't appear in the other travis builds so was only evident after merging to master when the deployments are done. Casting the result to `(void)` doesn't work with this compiler: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=25509 but it probably makes sense to check them anyway although we are limited to what we can do in a signal handler so am just checking for success before continuing.
> Fix unused variable error in deployments

- docker/node/Dockerfile
The travis docker deployment cannot handle the additional core added in #2148, otherwise the error
`virtual memory exhausted: Cannot allocate memory` is given near the end of the build many times. It can handle the same number though, so I'm just removing the extra one. Using `nproc` instead now which is simpler than how I was determining the number of cores before.
For my sanity next time (and in case anyone else needs to do this), the following steps can be done to check the deployment build without have to merge into master:
1 - `.travis.yml` - Under `stages`, remove all except `deploy`. Under `jobs` -> `include`, remove all except deploy.
2 - `ci/deploy-docker.sh` - Replace this file with:
```
#!/bin/bash
set -e
docker build --build-arg NETWORK=live -f docker/node/Dockerfile -t …
```
> Remove extra core utilised during docker deployment build

- nano/core_test/block_store.cpp
- nano/core_test/difficulty.cpp
- nano/core_test/wallets.cpp
- nano/core_test/websocket.cpp
- nano/lib/blocks.hpp
- nano/node/active_transactions.cpp
- nano/node/bootstrap.cpp
- nano/node/cli.cpp
- nano/node/election.cpp
- nano/node/lmdb.cpp
- nano/node/network.cpp
- nano/node/testing.cpp
- nano/node/voting.cpp
- nano/node/wallet.cpp
- nano/node/websocket.cpp
- nano/qt/qt.cpp
- nano/secure/blockstore.hpp
- nano/secure/common.cpp
- nano/secure/ledger.cpp
Using the (void)var idiom used elsewhere in the code base for unused vars (can move to [[maybe_unused]] in c++17). There's also a default-in-switch-related uninitialized error fixed.
> Fix compile errors in release mode after warning->error change

- nano/lib/config.hpp
- nano/node/election.cpp
- nano/node/node.cpp
- nano/node/node.hpp
Extract minimum_principal_weight(), and use the 0.1% factor as a network constant which can possibly be changed for other networks in the future.
> Principal representative factor as a network constant

- nano/lib/errors.cpp
- nano/lib/errors.hpp
- nano/node/json_handler.cpp
- nano/node/json_handler.hpp
- nano/rpc_test/rpc.cpp
- Adds `difficulty_optional_impl()` and `multiplier_optional_impl()`
- Multiplier overrides difficulty if both given
- Multiplier is tested to be valid and > 0
> Accept multiplier in work_generate and work_validate

- nano/node/active_transactions.cpp
If an election was inserted within the current loop, don't consider it for the median calculation.
This should solve the effect during low load where active difficulty gets quite high while sampling only one or two very recent elections.
> Filter recent elections in update_active_difficulty

- nano/node/node.cpp
> In http callback, don't log any http responses indicating success as errors

- nano/lib/numbers.cpp
- nano/lib/numbers.hpp
- nano/node/json_handler.cpp
- nano/node/network.cpp
- nano/node/node.cpp
- nano/node/transport/tcp.cpp
- nano/node/transport/udp.cpp
- nano/rpc_test/rpc.cpp
https://github.com/nanocurrency/nano-node/issues/2181
> Use node_ prefix for node ID

- nano/core_test/websocket.cpp
- nano/node/node.cpp
- nano/node/websocket.cpp
- nano/node/websocket.hpp
Closes https://github.com/nanocurrency/nano-node/issues/2190
The election info fields matches those of `confirmation_history`
> Add support for election info in websocket confirmations

- CMakeLists.txt
- ci/build-travis.sh
To prevent inevitable warnings from different compilers/systems which are not caught by the versions of gcc/clang we use, this is now only turned on by default for our ci. It can still be turned on by setting the `NANO_WARN_TO_ERR` CMake flag though.
> Only use -Werror by default with ci

- nano/node/blockprocessor.cpp
- nano/node/blockprocessor.hpp
- nano/node/json_handler.cpp
- nano/node/node.cpp
- nano/node/node.hpp
- nano/node/wallet.cpp
https://github.com/nanocurrency/nano-node/issues/2194
> Process wallet blocks outside of block processor queue

- nano/node/bootstrap.cpp
- nano/node/bootstrap.hpp
Adding lazy balances check was unreachable
`if (total_blocks == 0)`
> Fix lazy bootstrap balances insert

- nano/secure/blockstore.hpp
- nano/secure/blockstore_partial.hpp
The `nano::uint128_union` passed in is not copied, pointers are made to it inside `nano::db_val` which then goes out of scope (stack lifetime issue). To make sure this doesn't happen again (with this function at least), passing in the type directly to ensure lifetime during this function call. This was only found in release builds on mac/linux, so release builds in ci are being implemented soon to hopefully catch issues like this and others in the future.
(Unrelated) Changed to bracket initialization, because hardly anything else in this file uses it.
> Increase lifetime of temporary rep variable

- nano/core_test/node.cpp
- nano/core_test/wallets.cpp
- nano/node/nodeconfig.cpp
- nano/node/nodeconfig.hpp
- nano/node/voting.cpp
- nano/node/voting.hpp
Also adds the RPC upgrade path for v18 config.
This is a simpler approach than before:
1. Sleep 100ms, only interruptible to send 12 hashes
2. If 3+ hashes arrived, sleep 100ms more
3. Send anything at the end
4. Repeat
This re-uses previous RPC config options. The current set of choices means that, on average:
- Votes will have 12 hashes at ~60 tps  (`12 / (2*0.100)`)
- Up to ~30 tps (`3 / 0.100`) the delay is 100ms
- Above ~30 tps, the delay is 200ms
- The min delay is increase from 50ms to 100ms
These targets are slightly more conservative (favor packaging more than latency) than currently.
> Simplify vote generator logic with a dual sleep

- nano/core_test/block_store.cpp
#2174 should have included an upgrade test, this PR adds it.
I realised the previous one (v13_v14) was also slightly incorrect, it was checking `accounts_v1` when it should have been checking `accounts_v0`, which now succeeds so am checking the `size ()` of the value retrieved from the database to make sure it is working as it should.
> Add mdb database test from v14 to v15

- nano/core_test/logger.cpp
- nano/lib/blocks.cpp
- nano/lib/blocks.hpp
- nano/node/blockprocessor.cpp
- nano/node/bootstrap.cpp
- nano/node/election.cpp
- nano/node/logging.cpp
- nano/node/logging.hpp
for block content and for election tally
https://github.com/nanocurrency/nano-node/issues/806
> Config option for single line logging records

- nano/core_test/node.cpp
- nano/node/blockprocessor.cpp
- nano/node/blockprocessor.hpp
- nano/node/bootstrap.cpp
- nano/node/bootstrap.hpp
Bootstrap can now fill up to half of the block processor size. If half full, tries to continue later with a delayed receive.
> Throttled received block for bootstrap

- nano/core_test/node.cpp
- nano/node/active_transactions.cpp
- nano/node/active_transactions.hpp
- nano/slow_test/node.cpp
`confirmation_height.prioritize_frontiers_overwrite` didn't take into account the new node wallet prioritised frontiers.
The other tests were being hit by the background confirming after the delay (will be solved by the disabled conf height mode in #2175), but have increased the delay for the next frontier confirm request for now anyway.
Also fixes a TSAN error in `node.rep_self_vote`
> Fix failing slow_tests

- nano/node/bootstrap.cpp
- call throttled_receive_block () after receiving bulk_pull block (nano::bulk_pull_client::received_block (...))
- decrease delay for throttled check
- add bootstrap_server stopped status check
> Improve throttled received block for bootstrap

- nano/node/node.cpp
Closes #2224 
Tested with a work peer requiring the header.
> Set application/json as header content type for work peer requests

- nano/core_test/node.cpp
- nano/node/nodeconfig.cpp
- nano/node/nodeconfig.hpp
- nano/node/wallet.cpp
New option `work_watcher_period` defaulting to 5 seconds.
Also moved the `condition.wait` to the end of the loop so that `stopped` is checked before going through blocks.
> Configurable work watcher period

- nano/node/vote_processor.cpp
The read transaction is refreshed after 100 votes (like the active mutex)
Before (using the database txn tracker config option):
>[2019-Aug-20 18:37:07.195274]: 8913ms read held on thread Vote processing
[2019-Aug-20 18:37:07.195274]: Processed 1080 votes in 9719 milliseconds (rate of 111 votes per second)
After the changes, it was left running for 10x longer and no long read transactions were held in the vote processor. Even with:
> Processed 4608 votes in 36809 milliseconds (rate of 125 votes per second)
> Reduce time holding read transaction in vote processor

- nano/core_test/active_transactions.cpp
The `confirmed` deque was not protected by a mutex
> Fix TSAN error in adjusted difficulty test

- nano/secure/common.cpp
Update beta network header_magic_number to finalize de-peering of pre beta reset nodes
> update beta network header_magic_number to finalize beta network reset

- nano/node/nodeconfig.cpp
Reported on beta DB5. Amounts such as online_weight_minimum don't use defaults. This works with json because these files are typically fully populated, but not with toml as it only contain non-defaults.
> Use defaults for amounts in toml

- nano/node/json_handler.cpp
- nano/rpc_test/rpc.cpp
Previously receive blocks were filtered out as it was comparing link hash instead of link as account.
Also added test case for receive blocks in addition to existing send block test case.
> Fixes account_history RPC to include receive blocks when filtering accounts.

- nano/node/logging.cpp
- nano/node/nodeconfig.cpp
TODO in another PR: Extend deserialize default test for full coverage of configs
> Fix some time-related configs being overriden with 0

- nano/core_test/ledger.cpp
- nano/core_test/message.cpp
- nano/core_test/network.cpp
- nano/core_test/node.cpp
- nano/core_test/peer_container.cpp
- nano/nano_node/entry.cpp
- nano/node/active_transactions.cpp
- nano/node/bootstrap.cpp
- nano/node/common.cpp
- nano/node/election.cpp
- nano/node/json_handler.cpp
- nano/node/network.cpp
- nano/node/testing.cpp
- nano/node/transport/tcp.cpp
- nano/node/transport/transport.cpp
- nano/node/transport/transport.hpp
- nano/node/transport/udp.cpp
- nano/node/transport/udp.hpp
- nano/node/voting.cpp
- nano/rpc_test/rpc.cpp
- nano/secure/common.cpp
- nano/secure/common.hpp
- nano/slow_test/node.cpp
Make protocol versions depend on network. Currently same value on all networks, but this can be changed, i.e. depeer by minimum version only on beta. This allowed the removal of `protocol_version_reasonable_min`. Most changes are due to removal of default arguments (which are no longer constants) and replacing nano::version -> network_params.
> Move protocol versions to network_params

- nano/core_test/work_pool.cpp
- nano/lib/work.cpp
- nano/lib/work.hpp
- nano/nano_node/daemon.cpp
- nano/nano_node/entry.cpp
- nano/nano_wallet/entry.cpp
- nano/node/node.cpp
- nano/node/nodeconfig.hpp
- nano/node/openclwork.cpp
- nano/node/openclwork.hpp
- OpenCL work is now properly queued within work pool.
- OpenCL work can now be cancelled properly, which is necessary for #2228 
- Node does not wait for completion anymore when shutting down.
- **Work threads now help in work generation**; one extra thread is added on startup to handle OpenCL. If using OpenCL, the best seems to be using at most `hardware_concurrency - 1` work_threads.
Unrelated: clarifying in a comment that bandwidth_limit is in bytes/sec
> Enhancements to OpenCL work handling

- nano/node/json_handler.cpp
- nano/rpc/rpc_handler.cpp
- nano/rpc_test/rpc.cpp
`enable_control` should not have been required to get the cemented count via RPC, should help some services.
> No longer need enable_control when getting the cemented count

- nano/core_test/block_store.cpp
- nano/core_test/ledger.cpp
- nano/core_test/network.cpp
- nano/core_test/node.cpp
- nano/core_test/processor_service.cpp
- nano/core_test/socket.cpp
- nano/nano_node/entry.cpp
- nano/node/cli.cpp
- nano/node/confirmation_height_processor.cpp
- nano/node/confirmation_height_processor.hpp
- nano/node/json_handler.cpp
- nano/node/node.cpp
- nano/node/node.hpp
- nano/node/nodeconfig.hpp
- nano/qt_test/qt.cpp
- nano/secure/blockstore.hpp
- nano/secure/blockstore_partial.hpp
- nano/secure/ledger.cpp
- nano/secure/ledger.hpp
- nano/slow_test/node.cpp
The `block_count` RPC is of the most common RPCs to call. It can now read from a cached cemented count rather than spending time iterating over all frontiers to compute it each time.
> Cache cemented count

- docker/ci/Dockerfile-clang
- docker/ci/Dockerfile-gcc
The following is output when trying to link a static rocksdb library in some cases:
```
../node/libnode.a(rocksdb.cpp.o):(.data.rel.ro._ZTIN7rocksdb11StackableDBE[_ZTIN7rocksdb11StackableDBE]+0x10): undefined reference to `typeinfo for rocksdb::DB'
```
This wasn't an issue in travis, but DB7 tag seems to be having issues. The solution is to set `USE_RTTI=1` before building the rocksdb library.
https://rocksdb.org/blog/2017/09/28/rocksdb-5-8-released.html
> Set USE_RTTI before building RocksDB in docker

- nano/core_test/difficulty.cpp
- nano/core_test/distributed_work.cpp
- nano/core_test/wallet.cpp
- nano/lib/work.cpp
- nano/lib/work.hpp
- nano/node/wallet.cpp
- nano/node/wallet.hpp
Work watcher was blocking IO threads by waiting for work. Switched to use a callback (within a callback) and adjusted tests.
Solved a few other TSAN issues from recent tests with distributed_work.
> Non-blocking work watcher loop

- nano/core_test/distributed_work.cpp
- nano/core_test/wallet.cpp
- nano/lib/utility.cpp
- nano/node/active_transactions.cpp
- nano/node/bootstrap.cpp
- nano/node/network.cpp
- nano/node/vote_processor.cpp
- nano/node/voting.cpp
Some supurious wakeup prevention:
- Critical: `active_transactions::request_loop ()` has a long wait
- Non-critical: could try to stop attempts more than once in bootstrapping, and increase stats more than once in some places
- Non-functional: writing `while(!predicate) wait(lock)` as `wait(lock, predicate)` 
Also moved the lock creation in `nano::worker::run ()` so it doesn't get re-created every loop
> Prevent supurious wakeup in active transactions request loop

- nano/core_test/block_store.cpp
- nano/core_test/core_test_main.cc
- nano/core_test/toml.cpp
- nano/lib/CMakeLists.txt
- nano/lib/rocksdbconfig.cpp
- nano/lib/rocksdbconfig.hpp
- nano/lib/walletconfig.cpp
- nano/lib/walletconfig.hpp
- nano/nano_node/daemon.cpp
- nano/node/node.cpp
- nano/node/nodeconfig.cpp
- nano/node/nodeconfig.hpp
- nano/secure/blockstore.hpp
A TOML config section is added with a single key/value to enable RocksDB. The CMake variable `-DNANO_ROCKSDB=ON` is required when building the node if wanting to use it though so that it has the required dependencies.
```
[node.rocksdb]
enable = true
```
There needed to be a way to conditionally use either LMDB/RocksDB when running our tests using the same build. This is done with a new environment variable `TEST_USE_ROCKSDB`, not done in this task but travis will be modified to run tests with both backends.
Also outputting what backend is used when the node is launched.
(Unrelated) Setting up the logging object in `core_test` so that boost logging isn't output to standard out before a test has called it.
> Add config option to conditionally enable RocksDB backend

- nano/core_test/toml.cpp
- nano/node/active_transactions.cpp
- nano/node/logging.cpp
- nano/node/logging.hpp
This log is to aid in testing of prioritization. Wasn't sure whether to include the root in the log, thoughts?
> Add log when a block difficulty is updated in active transactions

- nano/node/active_transactions.cpp
- nano/node/bootstrap.cpp
Bug introduced in #2263 . Conditions without predicates would wake up when `node.stop ()` is ran, but with predicates we have to manually add each one.
> Fix delay in stopping the node

- nano/nano_node/entry.cpp
- validate representative block
- check type & previous field for open blocks
- check if successor block exists instead of segfault
- validate total block count
> CLI --debug_validate_blocks enhancement

- nano/node/node.cpp
- nano/secure/ledger.cpp
- nano/secure/ledger.hpp
Based on built-in bootstrap_weight_max_blocks
Similar to https://github.com/nanocurrency/nano-node/pull/2257
> Disable unchecked cleanup if node is not synchronized

- .travis.yml
- ci/deploy-docker.sh
When building for RC and DB tags start CI by building nanocurrency/nano-beta:master tag for docker
if tests are successful push updated beta docker artifact tags cached from nanocurrency/nano-beta:master docker tag
update latest as well as latest-including-rc for nano-beta docker images
> add master tag for beta and caching for subsequent artifacts_beta builds

- nano/node/network.cpp
Now correctly limited to `confirm_req_hashes_max` (7). Introduced in #2130 .
> Fix off by one in broadcast_confirm_req_batch

- nano/core_test/network.cpp
- nano/core_test/node.cpp
- nano/core_test/wallet.cpp
- nano/lib/errors.cpp
- nano/lib/errors.hpp
- nano/node/distributed_work.cpp
- nano/node/distributed_work.hpp
- nano/node/json_handler.cpp
- nano/node/node.cpp
- nano/node/node.hpp
- nano/node/wallet.cpp
- nano/node/wallet.hpp
- nano/qt/qt.cpp
- nano/rpc_test/rpc.cpp
Adds handling of work generation failures in critical paths (everything that is not a test). Failure can be a simple work cancellation which can happen for many reasons - even manually.
- Extract `nano::wallet::action_complete` with work validation + generation + block processing. Was repeated in all `*_action`
- Move work generation logging to distributed work, which makes logging now work for 99% of cases rather than only for precaching
- Fix a minor issue in distributed work where work cancellation would make it start local generation immediately the next time
> Handle work generation failure and cancel

- ci/deploy-docker.sh
without `=` the string isnt properly parsed by the script
> docker `--cache-from` set as single string argument with =

- nano/lib/rpcconfig.cpp
- nano/lib/rpcconfig.hpp
- nano/nano_rpc/entry.cpp
- nano/node/daemonconfig.cpp
Same option as for the node, allowing toml options to be passed to the RPC daemon via arguments. Includes a var name change for consistency.
Example: `nano_rpc --daemon --config port=9999`
Not adding a doc tag as there's already https://github.com/nanocurrency/nano-docs/issues/94
> Add --config option to rpc process

- ci/build-travis.sh
- nano/lib/locks.cpp
- nano/node/bootstrap/bootstrap.cpp
- nano/node/bootstrap/bootstrap.hpp
- nano/node/bootstrap/bootstrap_bulk_pull.cpp
using `-DNANO_TIMED_LOCKS=50`, there was a lot of output from `bootstrap_attempt::should_log` and the `bulk_pull_client` constructor (some of the stack trace has been removed to limit noise) after launching the node:
```
0000020C01E330F0 Mutex held for: 7511ms
4# nano::lock_guard<std::mutex>::~lock_guard<std::mutex> at C:\Users\Wesley\Documents\Nano\raiblocks\nano\lib\locks.cpp:53
5# nano::bootstrap_attempt::should_log at C:\Users\Wesley\Documents\Nano\raiblocks\nano\node\bootstrap\bootstrap.cpp:96
6# nano::bulk_pull_client::request at C:\Users\Wesley\Documents\Nano\raiblocks\nano\node\bootstrap\bootstrap_bulk_pull.cpp:68
7# boost::asio::asio_handler_invoke<<lambda_f0cf6567c36477560ddca8004bc29bbb> > at C:\Boost_1_70_0\include\boost\asio\handler_invoke_hook.hpp:69
```
```
0000020C01E330F0 …
```
> Improve bootstrap attempt locking

- docker/ci/Dockerfile-clang
- docker/ci/Dockerfile-gcc
This is required for distribution to older CPUs without AVX2 support. For those wishing to use that instruction set with docker and RocksDB, they should `docker build` themselves while removing `PORTABLE=1` from the appropriate Dockerfile
> By default the binary we produce is optimized for the platform you're compiling on (-march=native or the equivalent). SSE4.2 will thus be enabled automatically if your CPU supports it. To print a warning if your CPU does not support SSE4.2, build with USE_SSE=1 make static_lib or, if using CMake, cmake -DFORCE_SSE42=ON. If you want to build a portable binary, add PORTABLE=1 before your make commands, like this: PORTABLE=1 make static_lib.
https://github.com/facebook/rocksdb/blob/master/INSTALL.md
> Build RocksDB library as portable in docker

- nano/core_test/block_store.cpp
- nano/core_test/ledger.cpp
- nano/core_test/node.cpp
- nano/core_test/versioning.cpp
- nano/core_test/wallet.cpp
- nano/core_test/wallets.cpp
- nano/nano_node/entry.cpp
- nano/node/json_handler.cpp
- nano/node/lmdb/lmdb.cpp
- nano/node/node.cpp
- nano/node/node.hpp
- nano/node/wallet.cpp
- nano/qt/qt.cpp
- nano/rpc_test/rpc.cpp
- nano/secure/blockstore_partial.hpp
- nano/secure/common.cpp
- nano/secure/common.hpp
- nano/secure/ledger.cpp
- nano/secure/ledger.hpp
Currently to find the representative from the `account_info` an extra read is needed to be done to get the rep block contents and get the representative from that. This causes slow-downs in the initial rep caching and delegator RPCs (so should fix #1517). The `rep_block` has now been replaced with the representative account itself.
To prevent breaking existing service implementations, `rep_block` will be determined on demand for RPCs which currently add to the responses (@guilhermelawless's recommendation), but will be marked as deprecated. In the new RPC 2.0 it `representative` should be returned by default rather than require the flag `"representative":"true"`
Note: Any ledgers used since #2174 will not be valid as this requires a database upgrade and those ledgers will already be on …
> Replace account_info::rep_block with representative account

- nano/core_test/distributed_work.cpp
- nano/core_test/websocket.cpp
- nano/node/distributed_work.cpp
- nano/node/distributed_work.hpp
- nano/node/websocket.cpp
- nano/node/websocket.hpp
No filtering options. Examples:
Generated:
```json
{
"success": "true",
"reason": "",
"duration": "306",
"request": {
"hash": "3ECE2684044C0EAF2CA6B1C72F11AFC5B5A75C00CFF993FB17B6E75F78ABF175",
"difficulty": "ffffff999999999a",
"multiplier": "10.000000000009095"
},
"result": {
"source": "192.168.1.101:7000",
"work": "4352c6e222703c57",
"difficulty": "ffffffd2ca03b921",
"multiplier": "22.649415016750655"
},
"bad_peers": ""
}
```
Cancelled with one bad peer:
```json
{
"success": "false",
"reason": "cancelled",
"duration": "539",
"request": {
"hash": "3ECE2684044C0EAF2CA6B1C72F11AFC5B5A75C00CFF993FB17B6E75F78ABF175",
"difficulty": "ffffff999999999a",
"multiplier": "10.000000000009095"
},
"bad_peers": [
"192.168.1.101:7000"
]
}
```
- Duration is in ms.
- Failure is the same as cancelled but …
> Websocket subscription for work notifications

- nano/core_test/epochs.cpp
- nano/node/confirmation_height_processor.cpp
- nano/node/confirmation_height_processor.hpp
- nano/node/node.cpp
- nano/secure/CMakeLists.txt
- nano/secure/epoch.cpp
- nano/secure/epoch.hpp
- nano/secure/ledger.cpp
- nano/secure/ledger.hpp
Removed `representation_add ()` in `ledger.cpp`. It has an unused `nano::transaction` parameter and calling the contents of the function (1 line) directly where it's used seems cleaner than the extra indirection of this function.
Removed multi-line commented section of code in `core_test/epochs.cpp`. It references an epoch_2 which doesn't currently exist, so will just confuse anyone looking at it.
`nano/secure/CMakeLists.txt` to be consistent with the rest of the file the header goes before the source file.
The confirmation height processor now has a dependency on the ledger class and the constructor is passed a `cemented_count` cache from the ledger, this can just be called from the ledger object directly now, no need to pass it in.
Some functions in ledger/epoch can return `const &` to …
> Some minor cleanup

- nano/core_test/distributed_work.cpp
- nano/node/distributed_work.cpp
- nano/node/distributed_work.hpp
`distributed_work` was running the callback with `boost::none` when stopped, even if it was purposefully stopped by cancelling. This was fixed more gracefully by adding another atomic bool, `cancelled`, and using similar semantics to `set_once` for `cancel_once`.
> Fix rpc.work_peer_bad

- nano/core_test/active_transactions.cpp
- nano/core_test/epochs.cpp
- nano/core_test/wallet.cpp
- nano/node/json_handler.cpp
- nano/node/wallet.cpp
- nano/node/wallet.hpp
- nano/rpc_test/rpc.cpp
Marking as a breaking RPC change, since wallet_add_watch may now fail after pubkey validation. Contains some unrelated formatting fixes on master.
> Verify pubkey against special keys in wallet

- nano/node/active_transactions.cpp
- nano/node/network.cpp
- nano/node/network.hpp
Changing requests_bundle to use deque instead of vector and then pop_front instead of pop_back.  This resolves the inverse PoW priority issues seen during active transaction processing.  Live traffic is still unaffected as this only takes effect once active transaction processing starts.
There are some other version difference between the images below, but PoW priority is shown.
Bootstrapping V20.0 Beta Before the change ...
Compared to bootstrapping V20.0 Beta after the change ...
> Update broadcast_confirm_req_batch to handle PoW priority

- nano/lib/tomlconfig.hpp
- nano/node/cli.cpp
With this, the output of `--generate_config` is a complete TOML file, but with all entries commented out. A user can now pipe the config to file and uncomment any entries that needs change. By keeping everything else commented out, new defaults after upgrades will be used.
The documentation tag for the main PR will cover this.
> Make generate_config produce commented-out entries by default

- nano/node/active_transactions.cpp
- nano/node/active_transactions.hpp
Using the new efficient block count and cemented count caches
> Checking for frontiers only if necessary

- nano/core_test/websocket.cpp
- nano/node/websocket.cpp
provides a keep alive in the form of action
```
{
"action":"ping"
{
```
with a response of
```
{
"ack": "pong",
"time": "<ms since epoch>"
}
```
This allows for checking liveliness of websocket without refreshing or creating a subscription
> ws keepalive

- nano/core_test/distributed_work.cpp
- nano/node/distributed_work.cpp
- nano/node/distributed_work.hpp
- nano/node/json_handler.cpp
- nano/node/node.cpp
- nano/node/node.hpp
- nano/node/wallet.cpp
- nano/rpc_test/rpc.cpp
- Send `account` to work peers via distributed work, to facilitate tracking for precaching. Optional so as to not break tests.
- Return hash on work responses, useful as an id despite not being unique (i.e., there can be two work requests for the same hash).
> Quality of life updates for distributed work

- CMakeLists.txt
- nano/node/cli.cpp
Currently not defining NANO_ROCKSDB (as @guilhermelawless found) as a CMake variable causes a build failure.
Also found a place that is using `#ifdef NANO_ROCKSDB` where it shouldn't.
> Set NANO_ROCKSDB define even when set to OFF

- nano/core_test/toml.cpp
- nano/lib/rocksdbconfig.cpp
- nano/lib/rocksdbconfig.hpp
- nano/node/node.cpp
- nano/node/rocksdb/rocksdb.cpp
- nano/node/rocksdb/rocksdb.hpp
- nano/secure/blockstore.hpp
Defaults have been lowered for many settings to cope with lower end memory devices as RocksDB is very memory hungry. They can be customised by TOML settings now which include recommended values in the comments if the user has enough RAM for them.
> Add some RocksDB TOML config options to tune memory usage

- nano/lib/stats.cpp
- nano/lib/stats.hpp
- nano/node/transport/udp.cpp
- nano/qt/qt.cpp
traffic -> traffic_udp
traffic_bootstrap -> traffic_tcp
Most traffic will now be on `traffic_tcp`, so we might want to consider splitting it up into more fine grained stats at some point.
Docs PR at https://github.com/nanocurrency/nano-docs/pull/118
> Classify traffic stats correctly

- nano/qt/qt.cpp
Fixes an annoyance in the Qt wallet where creating new accounts doesn't update the account list properly.
Moves `refresh()` out of the tx scope, so it's almost all whitespace changes.
> Account creation refresh in qt wallet

- nano/core_test/websocket.cpp
- nano/node/active_transactions.cpp
- nano/node/active_transactions.hpp
- nano/node/election.cpp
- nano/node/json_handler.cpp
- nano/node/websocket.cpp
- nano/rpc_test/rpc.cpp
Used in the block confirmation websocket to keep track of confirmation request counts outside the node.
> Add confirmation request count to election_status

- CMakeLists.txt
- nano/nano_node/CMakeLists.txt
install samples to root of installers, This allows for those on mac to not have to dig for the samples within the app
formatting
> generate sample node and rpc toml after building nano_node target

- nano/core_test/active_transactions.cpp
- nano/node/active_transactions.cpp
- nano/node/active_transactions.hpp
- nano/node/json_handler.cpp
- nano/node/network.cpp
- nano/node/network.hpp
This is split 1/? (a safe one) from #2306 
- Rename variables with suffix `_l` for local variables in `request_confirm` as it's a large function
- Rename some variables so their purpose is obvious
- Add callbacks to allow throttling broadcasting. It could happen that more broadcasts would be queued while the previous ones hadn't finished, especially under load
- Add condition `node.ledger.block_count_cache > node.ledger.cemented_count + roots.size () + pending_confirmation_height_size` before checking frontiers as that can read the disk for 2 seconds when not necessary. It's still not perfect, per the in-file comment, as e.g., 10 roots can be added and they're transformed into a single frontier by the confirmation height processor. Open to ideas on making this condition more consistent. …
> Basic confirmation request loop enhancements

- nano/core_test/distributed_work.cpp
- nano/core_test/toml.cpp
- nano/core_test/wallet.cpp
- nano/node/distributed_work.cpp
- nano/node/distributed_work.hpp
- nano/node/json_handler.cpp
- nano/node/node.cpp
- nano/node/node.hpp
- nano/node/nodeconfig.cpp
- nano/node/nodeconfig.hpp
This secondary list of peers can be used only via RPC work_generate by setting the option "secondary_work_peers" to "true" along with "use_peers"
- Adds secondary_work_peers under a new "experimental" config
- Changes distributed_work to receive a list of peers
- Some fixes to distributed_work where it wouldn't call the failure callback in edge scenarios
- Collect object stats for distributed_work
> Secondary list of peers for generating work

- nano/core_test/active_transactions.cpp
- nano/node/active_transactions.cpp
- nano/secure/versioning.cpp
Includes a couple of formatting fixes for master (according my version of clang-format at least)
> tsan: fix race in inactive_votes_cache_multiple_votes

- nano/core_test/active_transactions.cpp
- nano/core_test/confirmation_height.cpp
- nano/core_test/node.cpp
- nano/lib/config.hpp
- nano/node/active_transactions.cpp
- nano/node/active_transactions.hpp
- nano/node/blockprocessor.cpp
- nano/node/election.cpp
- nano/node/election.hpp
- nano/node/json_handler.cpp
- nano/node/network.cpp
- nano/node/node.cpp
- nano/node/nodeconfig.cpp
- nano/node/nodeconfig.hpp
- nano/node/repcrawler.cpp
- nano/node/repcrawler.hpp
- nano/node/socket.hpp
- nano/secure/versioning.cpp
Closes #2137 , closes #2139  (alternative to both)
**Todo**
**Documentation**
**PR Description**
This PR has 2 main changes:
- Disables per-block confirm_req in the block processor
- Changes the confirmation loop such that it has a period of 0.5s instead of 16-36 seconds.
Other things had to be tuned consequently, such as frontier prioritization timings. Data collected on the beta network shows there are large improvements to bandwidth usage under high load, much more agile PoW prioritization, and reduced tcp write drops.
The optimized bandwidth allows for doing a larger number of batch confirm_req directly to representatives in the same amount of time. The PoW prioritization being more agile means even under saturation the network should correctly prioritize blocks with the highest PoW …
> Active elections loop tuning

- nano/node/distributed_work.hpp
- nano/node/json_handler.cpp
Also fixes distributed_work relaying the account by not storing as a const ref.
> Attempt to fetch account from block hash in RPC work_generate

- nano/node/active_transactions.cpp
Median for active difficulty calculation is now obtained from a sorted container.
Also:
- Switch order of active difficulty update and confirmation requesting, as such the roots container stays sorted correctly.
- Obtain active difficulty only from top 10k elections, not the whole container which can contain temporary elections
- Only add active difficulty if more than 10 samples in the container
- Move mutex unlock/lock inside search_frontiers scope
- Increase high confirmation request count to 128 to reduce tally logging and escalations under load
> Fix active difficulty calculation

- nano/lib/errors.cpp
- nano/lib/errors.hpp
- nano/nano_wallet/entry.cpp
- nano/node/node.cpp
Currently it hits a `release_assert` so is non-obvious about why the gui bails. Also logging it when the node is run under the same conditions.
> Output error message with qt wallet if RocksDB is enabled in config but is unsupported

- nano/nano_node/daemon.cpp
- nano/nano_wallet/entry.cpp
- nano/node/CMakeLists.txt
- nano/node/daemonconfig.cpp
- nano/node/daemonconfig.hpp
- nano/node/node_pow_server_config.cpp
- nano/node/node_pow_server_config.hpp
Follows the same pattern as the RPC process.
Not enabled by default for now.
> Add ability to start pow server as child process

- nano/node/bootstrap/bootstrap.cpp
- nano/node/node.cpp
And prevent a post-bootstrap cleanup if the node was stopped.
> Fix disabled ongoing unchecked cleanup

- .travis.yml
- util/build_prep/macosx/build_qt.sh
Seed cache with qt built on travis at https://github.com/nanocurrency/travis-cache
AWS_BUCKET will be needed by PR's to complete tests and so is needed in the config
AWS_BUCKET does not need to be secure as it is already provided by the artifact downloads
convert tests to use prebuilt
format travis.yml for readability
> create build cache for mac qt in external repo and pull in for testing and artifacts.

- tsan_suppressions
While running TSAN on the tests with `TEST_USE_ROCKSDB=1` (and node built with -`DNANO_ROCKSDB=ON`), on Ubuntu 18.04 with Clang I get the following TSAN output:
https://gist.github.com/wezrule/a64b810c9203ae2a231f14b190529155
This is very similar to ones reported here:
https://github.com/facebook/rocksdb/issues/642
It didn't seem to have a resolution, so I'm just going to suppress them for now. I tried forever to suppress just these singular files/functions in the `tsan_clang_blacklist` file, but it just wouldn't work. In the end I am just using the runtime suppressions file which was originally only required for GCC, will update the docs accordingly.
A gcc build I did on another machine didn't have these tsan errors, but it does use a different version of RocksDB which may be a factor, …
> Suppress RocksDB TSAN warnings with Clang

- nano/nano_rpc/CMakeLists.txt
- nano/node/CMakeLists.txt
Building on ubuntu/boost 1.71 failed for nano_rpc, @wezrule suggested a link ordering fix, similar to #933
> Fix link ordering issues

- nano/node/portmapping.cpp
I noticed port mappings showed up in the router with the default `libminiupnp` description. With this, the router instead shows the mapping as `Nano Node (live)`  (or whatever network is used)
> Add upnp port mapping description

- nano/node/network.cpp
- nano/node/network.hpp
I get this TSAN `thread_leak` error at the end of `node.peers` test on Ubuntu & MacOS with Clang:
https://gist.github.com/wezrule/4635dbf9e588bcdd90c27abdc8ec70de
The `~network` destructor is not getting called, something is holding onto the node reference preventing its destructor being called and hence the packet threads are not being joined. We quite often have a pattern of `join`ing threads in the `stop` function and then calling `stop ()` in the destructor protected by a `stopped` atomic variable. This is what I have done here, this is probably just masking a deeper timing issue somewhere else completely unrelated, but to solve that is probably quite a lot of work. This reduces the symptoms at least and is only in shutting down code, so not a high priority
> TSAN error in node.peers test

- nano/core_test/distributed_work.cpp
Under ASAN `nano::block_hash hash` is more likely to have a 0 value rather than a garbage uninitialized data (with Clang on Ubuntu 18.04 at least), this causes this assert to fire:
```
core_test: /home/wezrule/nano/nano-node/nano/lib/work.cpp:205: void nano::work_pool::generate(const nano::root &, std::function<void (const boost::optional<uint64_t> &)>, uint64_t): Assertion `!root_a.is_zero ()' failed.
Aborted (core dumped)
```
Simply setting it to an initialized value in the affected tests solves it.
> Distributed work test failures under ASAN

- nano/core_test/node.cpp
The following ASAN error appears on both Mac/Ubuntu with clang:
https://gist.github.com/wezrule/2ecb809cacc393835b65e22f27b485cd
It is due to `max_hashes` being used vote observer callback after it has been destructed. This gets called inside of the `system::~system` when stopping the node. The simplest solution is to just put it above system so that it remains in scope.
> ASAN error in vote_by_hash test

- nano/lib/utility.cpp
The following ASAN output was generated with the node.peers test, but it's not specific to this test, just seems to be easily reproducible there. Found on Ubuntu 18.04 with Clang, couldn't reproduce on MacOS:
https://gist.github.com/wezrule/17cb9b81ceeaf1a5ccfcec900f666b82
Was a bit of a bugger to locate as anything could have been causing it, but I knew the node destructor was not being called so something must have been holding a `shared_ptr` reference to it, but wasn't sure what. I ended up rolling back commits to find the culprit, which ended up being https://github.com/nanocurrency/nano-node/pull/1264. In particular (for this example at least) it was this callback:
```
node_l->worker.push_task ([node_l]() {
node_l->ongoing_peer_store ();
});
``` 
The `worker::stop` function is called …
> ASAN leak when exiting node

- docker/node/Dockerfile
Currently our docker image runs as root
This will provide people with the opportunity to migrate over to the new nanocurrency(1000:1000) user setup without forcing the hand quite yet.
If you want to start the migration early `sudo chown -R 1000:1000 /local/mount/path` and then add the following switch to your docker run command [--user=nanocurrency](https://docs.docker.com/engine/reference/run/#user) and [-w=/home/nanocurrency](https://docs.docker.com/engine/reference/run/#workdir) and adjust your mount to `-v <local/mount/path>:/home/nanocurrency`
To preserve existing installations root(0:0) and /root are used if no user & workdir are specified
> Docker USER support

- CMakeLists.txt
- nano/lib/CMakeLists.txt
- nano/lib/locks.cpp
- nano/lib/locks.hpp
- util/build_prep/bootstrap_boost.sh
When https://github.com/nanocurrency/nano-node/pull/2267 was made we exclusively used `std::condition_variable`, this only accepts `std::unique_lock` which made it incompatible with our new `nano::unique_lock`. Unaware of alternatives a new `condition_variable` class was made which unfortunately depended on the boost `context`/`fiber` libraries.
However I recently discovered that there is a `std::condition_variable_any` class which is less constrained and accepts any [BasicLockable](https://en.cppreference.com/w/cpp/named_req/BasicLockable) type, which is compatible with our classes, so I am now using this which has removed the boost dependencies and some other code.
Also removed a CMake warning:
```
CMake Warning (dev) at CMakeLists.txt:35 (set):
implicitly converting 'NUMBER' to …
```
> Use std::condition_variable_any with timed locking

- README.md
During copy-paste of markdown ended up not using URLs for two of the new badges in #2364 . Preview:
[![GitHub release (latest by date)](https://img.shields.io/github/v/release/nanocurrency/nano-node)](https://github.com/nanocurrency/nano-node/releases/latest)
[![GitHub tag (latest by date)](https://img.shields.io/github/v/tag/nanocurrency/nano-node?color=darkblue&label=beta)](https://github.com/nanocurrency/nano-node/tags)
> Badge URLs

- docker/ci/Dockerfile-base
run the following to test locally changes will not be built until committed to master
```
docker build -f docker/ci/Dockerfile-base -t nanocurrency/nano-env:base .
docker build -f docker/ci/Dockerfile-gcc -t nanocurrency/nano-env:gcc .
docker build --build-arg NETWORK=beta --build-arg CI_BUILD=TRUE --build-arg TRAVIS_TAG=cmake_new -f docker/node/Dockerfile -t nanocurrency/local .
```
> allow for updated TARGET usage by updating cmake in nano-env:base

- nano/core_test/distributed_work.cpp
- nano/lib/work.cpp
- nano/node/distributed_work.cpp
- nano/node/distributed_work.hpp
- nano/node/node.cpp
- nano/node/wallet.cpp
Found while running RPC `epoch_upgrade` which places the task in `nano::worker`. When preemptively stopping the node (with SIGINT, not RPC "stop") the I/O threads are destroyed and the background `work_generate_blocking` task can't complete if using work peers.
This adds manual canceling of all ongoing work before attempting to destroy the `worker`.
Also fixes an issue where canceled work would turn into zero-filled work, which was only a problem when stopping the node.
> Improve distributed_work stopping with ongoing worker tasks

- nano/node/lmdb/lmdb.cpp
- nano/node/lmdb/lmdb.hpp
- nano/node/lmdb/lmdb_env.cpp
- nano/node/lmdb/lmdb_env.hpp
During the v14 to v15 database upgrade, the ledger grows from 16GB to 24GB, vacuuming is now done after the upgrade. Vacuuming can take substantial time on lower end devices, for instance my 1vCPU, 2GB Ram droplet took 16 minutes for the upgrade itself (swap space was not used) and a further 20 minutes for the vacuum. On Windows, 3.4GHZ, 16GB RAM, the upgrade and vacuum took under 10 minutes in total, both tests were done with the RelWithDebInfo configuration. Additional log entries were added near the beginning upgrade steps. The following was logged for the 1vCPU droplet where it didn't have enough space for the vacuum (only difference is the last log entry which would say successful if it was):
```
[2019-Oct-29 11:43:41.891987]: Preparing v14 to v15 upgrade...
[2019-Oct-29 …
```
> Vacuum after upgrade

- nano/core_test/CMakeLists.txt
> Fix link ordering issue in core_test (ubuntu/boost 1.71)

- nano/node/active_transactions.cpp
- nano/node/active_transactions.hpp
- nano/node/network.cpp
From 15 to 5 every 500ms to focus more bandwidth on batched requests.
It also removes the burst of batched requests in order to spread them out more over the 500ms loop (was done in 80ms before, now 300ms). Comments about the timings are now clearer.
> Adjust single-hash confirm requests

- nano/node/json_handler.cpp
- nano/node/node.cpp
Moves `distributed_work.stop ()` so that it is one of the first stopped tasks, which solves a deadlock in `wallets` while precaching.
Work generation tasks must stop (cancel) before attempting to stop any of the threads that might be waiting for that work.
As a consequence, RPCs should not block waiting for work either, as the I/O threads are not stopped first if the node is terminated via a signal. This PR reworks `block_create ()` to use the callback version of `work_generate`, and greatly reduces the amount of redundant code.
The changes are mostly in commit f42681b . The other commit, 
b236596 , simply removes an unecessary `if (!ec)` block, but affects all identation.
> Stop work generation before stopping threads waiting for work

- nano/node/json_handler.cpp
- nano/rpc_test/rpc.cpp
`boost::property_tree::read_json (block_stream, block_l);`  needed a try/catch as we have in other places. Added some test cases.
Thanks @Joohansson for the report
> Add error handling to RPC process without json_block

- nano/node/json_handler.cpp
Two fixes discovered from `rpc_test` runs:
1. Asserts in Debug builds because work is set after building blocks (now using error_code, an alternative is setting 0 work temporarily, but I liked this solution better)
2. A timer assert, which pointed to responses being sent twice on success - first via `block_response_put_l` and then via `response_errors`.
> RPC block_create fixes

- CMakeLists.txt
This fixes the macos deployment target to 10.12 allowing targeting older sdk's while building on new OSx hosts
see https://cmake.org/cmake/help/latest/variable/CMAKE_OSX_DEPLOYMENT_TARGET.html
> Target osx 10.12 deployment

- nano/node/bootstrap/bootstrap.cpp
lock_guard d'tor would call unlock again, which is undefined behaviour
> Fix lazy mutex unlock via mutex

- nano/core_test/node.cpp
- nano/node/bootstrap/bootstrap.cpp
- nano/node/bootstrap/bootstrap.hpp
- nano/node/bootstrap/bootstrap_bulk_pull.cpp
- nano/node/bootstrap/bootstrap_frontier.cpp
- nano/node/bootstrap/bootstrap_server.cpp
- nano/node/socket.cpp
- nano/node/transport/tcp.cpp
- nano/node/transport/tcp.hpp
This was reproducible on Ubuntu with Clang, not on MacOS (thanks @cryptocode for testing it and assistance during this), Valgrind also caught this. It was most reproducible with the `node.send_single_many_peers` test, however may need to be run multiple times before seeing it. These leak stacktraces were shown: https://gist.github.com/wezrule/02f5a8d922c13b4bc277581b9e919f64
From the stacktraces it is not apparent what the cause of the issue is, and many different things were tried. The main issue stems from a circular relationship between `channel_tcp`, `bootstrap_server` and `socket`. `channel_tcp` stores a `shared_ptr` to both `bootstrap_server` and `socket`. `socket` stores callbacks in `send_queue`, most of these contain `channel_tcp` shared_ptrs,  so `socket` and `channel_tcp` can …
> [ASAN] memory leak between tcp channels and sockets

- nano/core_test/distributed_work.cpp
Valgrind output for this test:
https://gist.github.com/wezrule/5fe31826a30ca8b7556208da09e42b18
It's a similar issue to:
https://github.com/nanocurrency/nano-node/pull/2355
> [Valgrind] Uninitialized memory in distributed_work.no_peers test

- nano/node/rocksdb/rocksdb.cpp
Thanks to Srayman's testing of the RocksDB ledger backend and providing of the LOG files, we noticed that an incorrect `total_memtable_size` was being used; the value from the config.toml file was being passed directly but this needed to be multiplied into megabytes before being set as a RocksDB option. This could be the cause of the write issues some people were experiencing, further testing by Srayman is still underway, thanks!
Also modifying a typo in a comment.
> Incorrect total memtable size used with RocksDB

- nano/node/bootstrap/bootstrap.cpp
- nano/node/bootstrap/bootstrap.hpp
From run (), lazy_run () etc. if there are several runs in single bootstrap attempt
> Prevent concurrent bootstrap populate_connections ()

- nano/core_test/node.cpp
This failure was tied to a data race on `active_transactions::multipliers_cb`.
```
[ RUN      ] active_difficulty.recalculate_work
/Users/travis/build/guilhermelawless/nano-node/nano/core_test/node.cpp:3208: Failure
Expected equality of these values:
node1.active.active_difficulty ()
Which is: 18414790985620493964
nano::difficulty::from_multiplier (sum / node1.active.multipliers_cb.size (), node1.network_params.network.publish_threshold)
Which is: 18415888479324436004
[  FAILED  ] active_difficulty.recalculate_work (182 ms)
```
> [TSAN] Data race in active_difficulty.recalculate_work test

- .travis.yml
- ci/build-deploy.sh
- ci/build-travis.sh
- docker/ci/Dockerfile-clang
- docker/ci/Dockerfile-gcc
- util/build_prep/fetch_boost.sh
- util/build_prep/fetch_rocksdb.sh
- util/build_prep/macosx/build_qt.sh
use cached rocksdb for all artifacts and nix tests
use cached boost for all artifacts and tests
update dockerfile to use cache
update ci/build-travis.sh to use brew rocksdb for testing on mac otherwise use cached rocksdb
> use cached build artifacts

- nano/node/bootstrap/bootstrap.cpp
- nano/node/bootstrap/bootstrap.hpp
- nano/node/bootstrap/bootstrap_bulk_pull.cpp
* Limit bulk pulls memory usage in lazy bootstrap, flush less pulls from lazy_pulls to pulls
* Limit max lazy bootstrap blocks size if legacy bootstrap is enabled (1M lazy blocks limit)
* Prevent lazy destinations usage if legacy bootstrap is enabled
Better to check with hidden whitespace changes
> Lazy bootstrap memory usage improvements

- nano/core_test/websocket.cpp
- nano/node/common.cpp
- nano/node/common.hpp
- nano/node/wallet.hpp
- nano/rpc_test/rpc.cpp
1. In `bulk_pull` class https://gist.github.com/wezrule/387084bf4189f5dd85fb044abd917d1c
2. In `websocket.work` test https://gist.github.com/wezrule/174edc5e141143fb5656dbe7ad9a5522
3. In `rpc.wallet_create_seed` test https://gist.github.com/wezrule/05b1a84d0582b40cc3f7c16932f3367c (same in `rpc.wallet_change_seed`)
4. In `rpc.wallet_create_fail` https://gist.github.com/wezrule/014686344f0ff43470143d1fa25a7a55
> [Valgrind] Various uninitialized data accesses

- nano/core_test/distributed_work.cpp
Fixes failures such as: https://travis-ci.org/nanocurrency/nano-node/jobs/607767045#L3209
Ran 300 times under Debug TSAN on Linux, would be good to check on OSX which is where it failed sometimes
> Fix occasional failures for core_test.distributed_work* tests

- nano/core_test/bootstrap.cpp
- nano/core_test/node.cpp
- nano/node/bootstrap/bootstrap.cpp
- nano/node/bootstrap/bootstrap.hpp
- nano/node/json_handler.cpp
- nano/node/node.cpp
- nano/node/nodeconfig.hpp
- nano/node/repcrawler.cpp
* start new bootstrap attempt after failed confirmation
* prevent duplicates in frontiers vector
* increase chances of starting first bootstrap connection to requested peer
* disable rep crawler for specific tests (it can start elections)
* return confirmation status in confirm_frontiers () function
* add `force` option to `bootstrap_any` RPC
> Improve bootstrap frontiers confirmation

- nano/lib/rpcconfig.cpp
- nano/node/cli.cpp
- Adds a warning to the enable_control setting
- Generated header always referred to config-node.toml, even though the same header is used for the RPC config
- In the RPC config, most flags are top-level, so the category comment reflects this.
> Updates to TOML generated docs

- nano/rpc/rpc.cpp
Emits a warning in the log, and to stdout, if control is enabled and a non-loopback (which also means non-default) RPC bind address is used. This applies to the external RPC process as well.
> Warn if control is enabled with non-local bind address

- nano/node/portmapping.cpp
This is generated when exiting the node: https://gist.github.com/wezrule/1dbed7439768a0896fb3f8d497547198
We generate urls with `UPNP_GetValidIGD` which allocates memory on the heap but we don't clean this up.
> [ASAN] UPNP url memory leak

- nano/node/bootstrap/bootstrap_bulk_pull.cpp
epoch open blocks with public key equal to existing block hash
> Improve bootstrap for accounts with public key = existing block hash

- nano/node/transport/tcp.cpp
- nano/node/transport/tcp.hpp
Found by @SergiySW during bootstrap (segmentation fault). I am unable to reproduce it even with running `node.send_single_many_peers` 100 times with TSAN. The fix is (hopefully) to guard the `push_back` with a `mutex`.
> Node id handshake container not protected during push

- nano/node/common.cpp
- nano/node/common.hpp
The issue was tracked down to the hash of an endpoint inside a boost::multi_index_container being different depending on where it was called. Unfortunately it seemed that it was only easily reproducible on a release configuration on Windows which made debugging a bit harder. The culprit was the `ip_address_hash_raw` function which assumes that the same random constants variable is used each time. This is the case in the same translation unit, but because it is defined inside an unnamed namespace in a header, each translation unit which includes this (common.hpp) gets its own copy and hence each initialises its own static `random_constants`. Why it is a problem for some compilers/configurations and not others probably boils down to some compiler specific optimisations.
> Fix jumping peer stake total

- nano/core_test/active_transactions.cpp
- nano/node/active_transactions.cpp
Some tests expect an increasing confirmation_request_count even when confirm_req fails (e.g. no reps available), so I made it always increase for the test network.
Without that, note that `bootstrap_processor.lazy_unclear_state_link_not_existing` fails, because active_transactions would not escalate to broadcasting the block.
> Fix active_transactions not doing any confirmation request in tests

- nano/core_test/block_store.cpp
- nano/core_test/confirmation_height.cpp
- nano/node/rocksdb/rocksdb.cpp
- nano/secure/blockstore.hpp
- nano/secure/blockstore_partial.hpp
- nano/secure/ledger.cpp
`block_store_partial::block_del` currently checks all block databases to see if the key (hash) was found an successfully deleted. This involves 5 db accesses for change blocks for instance. This is unnecessary because in all cases `block_del` is called we know what block type and hence what database it will be found in. This wasn't quite the case before, as we had state v0/v1 databases but this is no longer the case, so the block can be deleted with 1 db access now. 
This subsequently also meant that RocksDB no longer needed to check if the key exists (a db read) when deleting because all places have already checked for this, although I still `assert` in a debug build that this is the case.
> Improve block deletion and RocksDB deletion in general

- nano/node/distributed_work.cpp
- nano/node/distributed_work.hpp
In start_work () :
`else if (!this_l->cancelled && !this_l->completed)`
Was not setting any of these atomics to true, so the same callback would possibly be called in `cancel_once`. Not normally an issue, but can happen and came up with Serg's epoch storm test. Instead of making a new atomic, joined both into a single `finished` atomic, and added a `work_generation_status` enum.
Also added a check `if (callback)` on every call.
> Fix distributed_work segfault when local work generation fails

- nano/nano_node/daemon.cpp
- nano/node/json_handler.cpp
- nano/node/lmdb/lmdb.cpp
- nano/node/lmdb/lmdb.hpp
- nano/node/node.cpp
- nano/node/rocksdb/rocksdb.cpp
- nano/node/rocksdb/rocksdb.hpp
- nano/rpc_test/rpc.cpp
- nano/secure/blockstore.hpp
`"store_vendor": "RocksDB 6.6.0"` or `"LMDB 0.9.23"` in my case.
Also logs the same string on node startup, currently it's only printing to stdcout.
> Add database vendor string to RPC version

- nano/node/json_handler.cpp
- nano/rpc_test/rpc.cpp
Closes #2418 
Will update documentation, should state that the wallet representative will be used from V21, and the own account is used in V20 and before, for unopened accounts.
Adds a suite of tests for RPC receive.
> Set wallet representative with RPC receive on unopened accounts

- nano/rpc_test/rpc.cpp
Changes from https://github.com/nanocurrency/nano-node/pull/2388 were not factored into https://github.com/nanocurrency/nano-node/pull/2419 since there were new RPC tests
> Fix rpc_test build

- nano/core_test/websocket.cpp
- nano/node/active_transactions.cpp
- nano/node/active_transactions.hpp
- nano/node/election.cpp
- nano/node/json_handler.cpp
- nano/node/websocket.cpp
- nano/rpc_test/rpc.cpp
Considered adding more details such as the number of votes for each block, but would need to tally up each election.
Similar to a previous PR, uses `assert (!node.active.mutex.try_lock ());` which can have [undefined behavior](https://en.cppreference.com/w/cpp/thread/mutex/try_lock), but only used in Debug. Don't see an easy alternative in this case, and it was already used in `election.cpp`.
> Add block and voters count in election information

- nano/core_test/bootstrap.cpp
- nano/lib/blocks.cpp
- nano/node/bootstrap/bootstrap_bulk_pull.cpp
- nano/node/bootstrap/bootstrap_server.cpp
- nano/node/wallet.cpp
Use `std::make_unique`/`std::make_shared` where appropriate.
Also removed some duplication in `nano::deserialize_block_json`
> Remove raw new operator used with smart pointers

- nano/core_test/block_store.cpp
- nano/node/lmdb/lmdb.cpp
- nano/node/lmdb/lmdb.hpp
- nano/secure/blockstore_partial.hpp
This was meant to be removed during the upgrade from v14, however the `representation` table was not being opened in the mdb_store constructor (thanks @SergiySW), it had a test which checked it didn't exist, but not that it existed in the first place. Creating a new upgrade path v15 -> v16 which correctly removed this.
> Remove representation table during v15 upgrade

- nano/nano_wallet/entry_com.cpp
Broken by https://github.com/nanocurrency/nano-node/pull/2425. It needed some extra includes
> Fix qt wallet build on Windows

- nano/core_test/node.cpp
- nano/node/active_transactions.cpp
- nano/node/blockprocessor.cpp
- nano/node/network.cpp
- nano/node/node.cpp
- nano/node/wallet.cpp
- nano/node/wallet.hpp
Had a test fail due to no votes happening with `reps_count` being 0 after inserting a rep, this was due to `wallets::compute_reps` resetting atomics. Both counts are now not atomic and protected by a mutex.
Also checked the code for mentions of `enable_voting` and added a check on rep count where relevant. Most notable are some uses of the vote generator.
> Wallet representative counts consistency

- .github/workflows/beta_artifacts.yml
- .github/workflows/develop.yml
- .github/workflows/live_artifacts.yml
- .github/workflows/release_test.yml
- .github/workflows/tests.yml
https://julienrenaux.fr/2019/12/20/github-actions-security-risk/ presents a good explanation as to why this could be problematic.
other change related to artifact being set improperly in Tests workflow and then shadowed in the build step. Changed to be set properly in workflow and removed build step reference
> use commit hash instead of tag for security

- ci/test.sh
There are times where core_test will spuriously fail tests intermittently.
We have a loop on core_test that allows it to retry up to 10 times in the event of a failure.
This needs to be moved from time to time to allow restarts to continue
> Allow core_test retries until 7-1-2020 00:00(gmt)

- nano/core_test/network.cpp
- nano/core_test/node.cpp
- nano/lib/plat/linux/debugging.cpp
- nano/node/network.cpp
- nano/node/network.hpp
- nano/node/transport/tcp.hpp
- nano/node/transport/transport.cpp
- nano/node/transport/transport.hpp
Changes from per-channel limits to a global limiter as originally intended, and fixes a few issues with the limiter
- Fix dropping condition not checking trended_rate
- Fix trended_rate calculation resulting in a 20x lower value
- Increment the sampling period to account for inconsistent sampling
- Non-droppable packets now increase the rate
- Update and simplify validation test
- Add new test using channels directly and ensuring the limit is global
> Global bandwidth limiter

- nano/nano_wallet/entry.cpp
To allow switching wallets via qt config
> qt dev wallet deserialization fix

- nano/lib/utility.cpp
- nano/nano_node/entry.cpp
A new CLI command is introduced `--debug_generate_crash_report`. This reads the stacktrace dump file "nano_node_backtrace.dump" and on linux parses each address and matches it to either the `nano_node` executable, or one of the shared libraries, and calls `addr2line` appropriately. It is a requirement that `addr2line` be installed, I will update the documentation to mention this, an error message is also piped should it fail.
For instance adding `int* p = nullptr; *p = 4` inside of the `nano_daemon::daemon::run` (after setting up signal handlers!!) and running the executable generates a seg fault. Running the existing `--debug_output_last_backtrace_dump` CLI command outputs:
```
Latest crash backtrace:
0# 0x00007F721EE79711
1# 0x00007F721E8BBDF8
2# 0x00007F721D86EF20
3# 0x00007F721E8BBFE2 …
```
> New CLI command to generate a crash report

- nano/node/active_transactions.cpp
- nano/node/active_transactions.hpp
- nano/node/election.cpp
- nano/node/node.cpp
> Erase inactive votes cache after election stop / finish

- nano/core_test/block_store.cpp
- nano/core_test/confirmation_height.cpp
- nano/core_test/ledger.cpp
- nano/core_test/node.cpp
- nano/core_test/processor_service.cpp
- nano/nano_node/entry.cpp
- nano/node/active_transactions.cpp
- nano/node/blockprocessor.cpp
- nano/node/confirmation_height_processor.cpp
- nano/node/json_handler.cpp
- nano/node/node.cpp
- nano/node/nodeconfig.hpp
- nano/node/rocksdb/rocksdb.cpp
- nano/node/vote_processor.cpp
- nano/qt/qt.cpp
- nano/qt_test/qt.cpp
- nano/secure/blockstore.hpp
- nano/secure/blockstore_partial.hpp
- nano/secure/common.hpp
- nano/secure/ledger.cpp
- nano/secure/ledger.hpp
- nano/slow_test/node.cpp
During bootstrapping with RocksDB (collecting all unchecked blocks), 27% of the time was spent checking whether a block exists and updating the unchecked count cache in the ledger. This extra IO was necessary because RocksDB cannot give you accurate counts of the number of keys in a table so it was expensive to determine the unchecked count on the fly. However this can just be done at startup as for the most part this number will actually be low and then just maintain an in-memory cache of the unchecked number, like we now do with: block count, cemented count and rep weights.
This improves bootstrapping substantially for the first phase of collecting all unchecked blocks, but processing unchecked -> checked afterwards is still slow (`unchecked_get` constitutes 50% of the CPU time), this …
> Cache unchecked count

- nano/core_test/node.cpp
- nano/node/network.cpp
The added test fails when `cached_votes` without checking for duplicates. Kept as a vector since it's a very small amount of items.
This should be free performance under saturation since nodes are getting the same vote repeatedly in response. Might result in lower write drops as well.
> Avoid replying to confirm_req with repeated votes

- nano/core_test/active_transactions.cpp
- nano/node/active_transactions.cpp
- nano/node/election.cpp
- nano/node/election.hpp
- nano/node/node.cpp
There's no guarantee that the first block we observe is the winning fork. This change processes all votes for a particular election instead of just the ones for thee first block observed.
> Adding forked votes to inactive vote cache.

- nano/core_test/active_transactions.cpp
- nano/core_test/ledger.cpp
- nano/core_test/node.cpp
- nano/core_test/websocket.cpp
- nano/lib/stats.cpp
- nano/lib/stats.hpp
- nano/node/active_transactions.cpp
- nano/node/active_transactions.hpp
- nano/node/node.cpp
- nano/node/node_observers.hpp
- nano/node/vote_processor.cpp
- nano/node/websocket.cpp
- nano/node/websocket.hpp
- nano/secure/common.hpp
Important note: if a vote arrives before the corresponding block, it's added to inactive_votes_cache and the vote code is `indeterminate`. When the vote is seen again it will be a `replay` if the election has since started. That means these votes are never broadcasted as unique votes. This is important to leave clear in the documentation for anyone using this websocket subscription.
------
Fixes #2421 by not broadcasting votes with unknown status to the websocket unless specified - which was the initial intention.
When elections are over, since we clear the votes immediately, we cannot determine if an arriving vote is a replay or not.
Late votes are now no longer marked as non-replays incorrectly; however, the indeterminate votes still follow the same path as unique votes, through the gap …
> Indeterminate vote status and enhanced websocket vote sub

- nano/node/distributed_work.cpp
- nano/node/distributed_work.hpp
- nano/node/distributed_work_factory.cpp
- nano/node/distributed_work_factory.hpp
- nano/rpc_test/rpc.cpp
Wrap all distributed_work socket handling in a strand. Could use one strand for each peer [I think], but with the very low amount of messages (2 sent and 1 received at max) this seems unnecessary
Other fixes and enhancements:
- Fix a rare issue where generation would finish before `start_work()` is done (by moving the local generation code to the end of the function)
- TSAN race fix in rpc.work_peer_many
- Wrap request parameters in a work_request class
- No logging when ongoing operations are canceled
- Make `backoff` a chrono object
- Move the work_peer_request class into distributed_work and rename it
> Use a strand in distributed_work

- nano/rpc/rpc_handler.cpp
- nano/rpc_test/rpc.cpp
Found by @Joohansson https://github.com/nanocurrency/nano-node/issues/2461
`enable_control` was incorrectly being checked when `watch_work` was set.
The test was using `work_watcher` too, which isn't valid, but `watch_work` is defaulted to true anyway so it wouldn't have been caught. I've updated the test to do some negative testing when enable_control is both enabled/disabled.
> Process RPC incorrect enable_control checking when using watch_work

- nano/core_test/active_transactions.cpp
- nano/core_test/confirmation_height.cpp
- nano/core_test/node.cpp
- nano/node/transport/udp.cpp
- `udp_channels::receive_action` was accessing local_endpoint directly, which showed up as a race under TSAN. Fixed by using the getter.
- By waiting for cementing, not getting any occasional failures anymore in confirmation_height.pending_observer_callbacks
- Cleanup verbose active_transactions tests and fixing another intermittent failure in the vote_replays test, due to frontier confirmation re-starting elections (which would also be fixed by #2441 or similar)
Ran under TSAN+Debug with gcc.
> Fixing some intermittent failures in unit tests, and some cleanup

- nano/core_test/utility.cpp
It relied on a global variable and function, which means multiple runs of unit tests with `gtest_repeat` would fail - making everything local.
> Fix thread worker unit test so it handles repeat runs

- .github/workflows/tests.yml
- ci/check-commit-format.sh
add clang-format back into the tests to be run
update check-commit-format.sh to return all clear
forced push to split cleanup of codebase to #2480
> Add clang-format test back in

- nano/core_test/node.cpp
- nano/node/node.cpp
- nano/node/voting.cpp
- nano/node/voting.hpp
- nano/node/wallet.cpp
- nano/secure/common.cpp
Memory footprint is insignificant compared to the cache for votes from other representatives.
> Generated votes cache size increase and upper bound

- nano/core_test/active_transactions.cpp
- nano/core_test/ledger.cpp
- nano/core_test/node.cpp
- nano/node/active_transactions.cpp
- nano/node/active_transactions.hpp
- nano/node/node.cpp
- nano/node/vote_processor.cpp
This also removes some code-smell around passing in a bool to determine if the lock should actually be acquired.
> Remove unnecessary lock requirement in active_transactions::lock.

- nano/core_test/CMakeLists.txt
- nano/core_test/confirmation_solicitor.cpp
- nano/lib/config.hpp
- nano/node/active_transactions.cpp
- nano/node/active_transactions.hpp
- nano/node/confirmation_solicitor.cpp
- nano/node/confirmation_solicitor.hpp
- nano/node/election.hpp
- nano/node/nodeconfig.hpp
- nano/node/repcrawler.cpp
- nano/node/repcrawler.hpp
Being a revamp this is best reviewed in split mode. The changes are:
- Fix for getting stuck in the loop
- Requests ordering is now respected to ensure prioritization
- Batch count was global and not per-channel
- **confirmation_request_count no longer used to alternate between elections, instead now doing it time-based**. Using a counter + modulo was not great.
- Deleted all uses of single confirm_req since there is more than enough weight on TCP now. This can however be reverted.
- Added a flag to disable active_transactions to allow for testing the solicitor
- Added a basic test for the solicitor
Eventually, it seemed more efficient to get rid of the `request` class and do most of the logic in `::add()` and have `::flush()` only batch and dispatch the messages. Overall I think the …
> Confirmation solicitor revamp

- nano/core_test/CMakeLists.txt
- nano/core_test/message.cpp
- nano/core_test/node.cpp
- nano/core_test/request_aggregator.cpp
- nano/lib/stats.cpp
- nano/lib/stats.hpp
- nano/lib/threading.cpp
- nano/lib/threading.hpp
- nano/node/CMakeLists.txt
- nano/node/network.cpp
- nano/node/network.hpp
- nano/node/node.cpp
- nano/node/node.hpp
- nano/node/request_aggregator.cpp
- nano/node/request_aggregator.hpp
- nano/node/voting.cpp
Adds a class that runs in a new thread to pool confirmation requests by endpoint, before replying with cached votes and generating new votes as necessary.
This allows a reduction of bandwidth, vote generation, and moves some vote generation out of the I/O threads.
Another advantage is using 12-hash votes rather than only up to the number of individual requestt hashes (max 7)
Includes stats for how many votes were cached, generated, or ignored.
> Request aggregator

- .github/workflows/tests.yml
There is some funkiness with clang-format-9 and lambdas that are not
honored
> use clang-format-8

- nano/core_test/CMakeLists.txt
- nano/core_test/distributed_work.cpp
- nano/core_test/fakes/work_peer.hpp
- nano/node/distributed_work.cpp
- nano/node/distributed_work.hpp
- nano/node/distributed_work_factory.cpp
This adds some more robust tests for `distributed_work`, which was lacking a fake peer to test from. The fake peer can act as a good (fast), slow (only replies after a while) or malicious (replies with wrong data) peer.
A few issues came up, all minor and now fixed:
- (commit 1) `node.work_generation_enabled` was being called with the predefined work_peers even though there are secondary work peers that can be used.
- (commit 2) only one peer was supported for each host. There doesn't seem to be any reason for this, so I simply made `outstanding` a vector and supporting changes.
- (commit 3) cancels were not being sent on an "end of stream", which was a bug with the fake work peer; with this PR, any peer that has been reached (written to) and not responded erroneously (malicious) will …
> Support multiple work peers in the same host

- nano/core_test/bootstrap.cpp
- nano/core_test/node.cpp
- nano/node/blockprocessor.cpp
- nano/node/json_handler.cpp
- nano/node/node.cpp
- nano/rpc_test/rpc.cpp
- nano/secure/blockstore.hpp
- nano/secure/blockstore_partial.hpp
The `unchecked_count` cache was not being updated when the unchecked table was cleared, which happened in 2 places. There was no `unchecked_clear` RPC test, so I've added one, the other code block is called on node start-up and isn't entered during tests, so couldn't make a test for it.
Processing blocks also just `unchecked_put` without any check for existence already, this is now checked. Added checks for tests which were confirmed to hit this. The extra `unchecked_exists` call only took 0.08% of CPU time during a snapshot on a bootstrapping attempt (gathering unchecked) on beta with LMDB. Untested on RocksDB, but `unchecked_get` is already an issue with it during bootstrapping, so any negative effects should be sorted for free alongside that.
Did a beta bootstrap and had 0 unchecked …
> Unchecked cache not handling duplicate entries or unchecked_clear

- nano/core_test/fakes/work_peer.hpp
- nano/core_test/node.cpp
- nano/node/node.cpp
- nano/node/repcrawler.cpp
- nano/node/repcrawler.hpp
Move processing effort on to rep_crawler and off of the vote processor.
- The response function has been converted to a lightweight function that simply queues votes to be checked on the next craw interval.
- Logic around updating reps has been moved out of the callback lambda and into the rep processor itself.
- The rep processor no longer accepts arbitrary values and directly computes weight from a given vote so tests have been updated accordingly.
> Rep crawler cleanup

- nano/nano_node/daemon.cpp
- nano/node/node.cpp
This only warns on startup so it will not recognize representatives in a fresh node, but otherwise, it does the following:
If voting is enabled:
- log:
- how many voting accounts are detected
- warn about system resources if more than one voting account
- stdout
- display a warning if more than one voting account
With #2432 the cache size is limited automatically if more accounts are voting, which motivated this PR.
**Examples**
1 representative:
- log: `Voting is enabled, more system resources will be used. 1 representative(s) are configured`
2 representatives:
- log: `Voting is enabled, more system resources will be used. 2 representative(s) are configured. Voting with more than one representative can limit performance`
- stdout: `Voting with more than one representative (2). This can …
> Log when voting and warn if voting with more than one account

- nano/core_test/distributed_work.cpp
When all work peers reply with invalid work (malicious), `distributed_work` backs off for 1 second before starting again, but now with local work generation.
This test required that the fake malicious peer received the request a second time, but it's necessary to test this with local generation disabled, which this PR now does.
Should fix the reported intermittent failure.
> Extend distributed_work.peer_malicious test to fix intermittent failure

- nano/core_test/bootstrap.cpp
- nano/core_test/node.cpp
- nano/core_test/websocket.cpp
Additionally:
- Disable bulk pull for most tests
- Fix websocket.bootstrap_exited TSAN warnings
- Disable bootstrap_processor.pull_requeue_network_error test
- Improve bootstrap_processor.lazy_unclear_state_link_not_existing test
> Update bootstrap tests to disable frontiers confirmation

- nano/node/request_aggregator.cpp
- nano/node/request_aggregator.hpp
Got a `Mutex held for: 1292ms` on `request_aggregator::run()`, which can happen if there are many requests being processed and no vote generation on any of them.
This adds a counter of consecutive requests being processed and refreshes the mutex lock when it hits a threshold (10).
Threshold is set to 1 on the test network to ensure testing.
> Refresh mutex lock after some consecutive requests without generation

- nano/node/node.cpp
- nano/node/node.hpp
To test, add this after L775 in node.cpp
```cpp
store.online_weight_put (transaction, (std::chrono::system_clock::now () - std::chrono::hours (8 * 24)).time_since_epoch ().count (), nano::amount (1000));
```
Do we have any other way of reaching the last entry without using two iterators as I did?
> Clear peers and online weight after 1 week of inactivity

- nano/core_test/request_aggregator.cpp
- nano/lib/stats.cpp
- nano/lib/stats.hpp
- nano/node/request_aggregator.cpp
- nano/node/request_aggregator.hpp
And ensures unique hashes before generating votes, by doing the same sort+unique as for votes.
Based on feedback from @Srayman , these adjusted stats are now useful to determine the ratio of votes-to-hashes and other interesting stats.
```cpp
aggregator_accepted
aggregator_dropped
requests_cached_hashes
requests_generated_hashes
requests_cached_votes
requests_generated_votes
requests_unknow
```
> Adjust request aggregator stats

- nano/core_test/node.cpp
- nano/node/election.cpp
- nano/node/network.cpp
- nano/node/node.cpp
- nano/node/node.hpp
Performing fork republishing after block processing and removing validate_block_by_previous which was performing validity checking that's already performed in the ledger block processor.
> Publish cleanup

- nano/lib/stats.cpp
- nano/lib/stats.hpp
- nano/node/blockprocessor.cpp
Stats have consistently been helpful and leading to many optimizations, these are intended to help grasp the efficacy of the duplicate filter and bottlenecks in single-account processing.
Adds detail stats when ledger processing from the block processor, for `old`, `gap_previous` and `gap_source` process codes.
> Additional ledger stats

- .github/workflows/tests.yml
- CMakeLists.txt
- ci/actions/windows/build.ps1
- ci/build-travis.sh
- nano/core_test/CMakeLists.txt
- nano/core_test/node.cpp
if `(defined(_WIN32) && CI)` to guard from them running
adds CI_TEST to CMakeFiles to define CI="1" if CI_TEST is true
disables node.fork_invalid_block_signature and node.bidirectional_tcp
> unstable tests on actions for windows

- nano/core_test/distributed_work.cpp
- nano/node/distributed_work.cpp
- nano/node/distributed_work.hpp
Hostname support was incomplete. Simplified the class by queuing each request as soon as the address is parsed/resolved, and removing the need to track `outstanding`.
> Resolving hostnames in distributed_work

- nano/core_test/node_telemetry.cpp
- nano/node/cli.cpp
- nano/node/common.cpp
- nano/node/common.hpp
- nano/node/network.cpp
- nano/node/nodeconfig.hpp
- nano/node/telemetry.cpp
- nano/node/telemetry.hpp
Adds "-disable_providing_telemetry_metrics" CLI command for users who do not want to provide metrics to other peers for what ever reason (suggested by @SergiySW). Still sending `telemetry_ack` response messages, otherwise we have to wait for the alarm timeout (3s). `stats` counters remain unchanged, but the payload is 0 and it is not added to the response data set for further processing.
> Optionally disable data in responses to telemetry requests with CLI option

- nano/node/network.cpp
Send additional random peers in `nano::network::send_keepalive_self ()` function
> Improve initial TCP server keepalive

- nano/core_test/node.cpp
- nano/node/bootstrap/bootstrap_server.cpp
- nano/node/network.cpp
- nano/node/network.hpp
- nano/node/repcrawler.cpp
- nano/node/telemetry.cpp
- nano/node/transport/tcp.cpp
- nano/node/transport/tcp.hpp
Representatives behind NAT or with blocked incoming TCP connections
Affected test: node.bidirectional_tcp
> Allow rep crawler targets with ephemeral ports

- nano/core_test/block.cpp
- nano/core_test/bootstrap.cpp
- nano/lib/blocks.cpp
- nano/lib/blocks.hpp
- nano/node/active_transactions.cpp
`block::hash` proved to be an area of high CPU usage during bootstrapping (10%) from the blake2b calls:
While some of this is unavoidable, there are cases where we call `block->hash ()` in multiple places, which is where caching the value will come in handy.
An extension to this may be to have a block cache manager which accounts for different `block` instances via `store::block_get` on the same hash in multiple places, but this would have to be thread safe, the benefit has not been justified as of yet.
`nano::active_transactions::search_frontiers` already had access to the hash, so creating the hash from the block is unnecessary.
> Cache hash for multiple block->hash () calls

- nano/node/lmdb/lmdb_txn.cpp
The issue is that the copy of `mdb_txn_stats` stats contains a pointer to the `transaction_impl` which might be deleted during the time that `is_write ()` gets called later. Storing this in another container while under the protection of the mutex to ensure validity.
Due to `std::vector<bool>` being a special specialization of std::vector, operator[] returns a `std::vector<bool>::reference` and not a bool, so using the `!!` syntax to turn it into a bool so that it is output correctly (otherwise it decays to 0/1)
> ASAN error with database transaction tracker json serialization

- nano/core_test/difficulty.cpp
- nano/lib/config.hpp
Previously 1/16x
On merge also update https://github.com/nanocurrency/nano-work-server
> Lower beta network work threshold to 1/64x base

- nano/core_test/block_store.cpp
- nano/core_test/ledger.cpp
- nano/core_test/versioning.cpp
- nano/nano_node/entry.cpp
- nano/node/lmdb/lmdb.cpp
- nano/node/lmdb/lmdb.hpp
- nano/secure/blockstore.cpp
- nano/secure/blockstore.hpp
- nano/secure/blockstore_partial.hpp
- nano/secure/ledger.cpp
( See previous discussion in #2529 )
This changes how the epoch byte in the state block sideband is [de]serialized, to also store these flags in the 3 most significant bits: `[is_send | is_receive | is_epoch | epoch (5 bits)]`
The upgrade is done in-place but takes a long time due to having to a random read to retrieve the previous block. A vacuum is performed at the end.
The upgrade does the following:
- Iterate through the state_blocks table
- For each block grab the previous block to determine the subtype of the current block
- Serialize the new sideband
- `mdb_cursor_put` with `MDB_CURRENT`
I was expecting no size growth due to using [MDB_CURRENT](http://www.lmdb.tech/doc/group__mdb__put.html#ga92f7832a496213db0f03105e6fa9afae), but no such luck. …
> Sideband upgrade using epoch byte for is_send/receive/epoch

- nano/core_test/CMakeLists.txt
- nano/core_test/network_filter.cpp
- nano/lib/CMakeLists.txt
- nano/lib/blocks.hpp
- nano/lib/stream.hpp
- nano/node/common.hpp
- nano/secure/CMakeLists.txt
- nano/secure/network_filter.cpp
- nano/secure/network_filter.hpp
Splitting from https://github.com/nanocurrency/nano-node/pull/2539
Extracts stream-related functions from `blocks.hpp` to `stream.hpp`. Adds a probabilistic filter based on direct-mapped caches, keyed by 128-bit SipHash.
The filter receives an array of bytes representing a network packet, and is checked for duplicity of the packet. The probability of a false unique is marginal, but not zero, and decreases with the size of the filter. This means it is possible to re-process the same packet. The probability of a false duplicate is the infinitesimal probability of a 128-bit SipHash collision. This means it's effectively impossible to not process a packet due to it being marked as duplicate.
Items are not normally erased. Instead, if a new item is different from the one at the insertion index …
> Probabilistic network packet filter

- nano/core_test/active_transactions.cpp
- nano/node/blockprocessor.cpp
- nano/node/wallet.cpp
Switched the order so the block is added to the watcher before starting the election, which could unluckily result in a drop.
Fixed an occasional failure in `active_transactions.keep_local` where one of the blocks would already have been dropped when checking the active roots.
> Add wallet-processed block to work watcher via the block processor

- nano/node/distributed_work.cpp
- nano/node/distributed_work.hpp
- nano/rpc_test/rpc.cpp
Since there is nothing to force a distributed_work to get destroyed before the node stops, this is a safer way to access the node on the destructor. Fixes some ASAN issues.
> [ASAN] Access node through a weak_ptr on distributed_work dtor

- nano/node/blockprocessor.cpp
- nano/node/cli.cpp
- nano/node/nodeconfig.hpp
Before it was part of `--fast_bootstrap` option only
> Add launch flag --disable_block_processor_unchecked_deletion

- nano/core_test/node.cpp
Couldn't reproduce locally, but seems to happen on actions a lot. Disable test while investigating
> Disable node.fork_open_flip test on Windows actions

- nano/core_test/CMakeLists.txt
- nano/core_test/fakes/websocket_client.hpp
- nano/core_test/websocket.cpp
- nano/node/websocket.hpp
This client keeps connections alive and runs in a separate thread.
Using EXPECT_* to prevent tests hanging in case of a failed assert in a thread.
> Fake websocket client to test the node websocket server

- nano/core_test/websocket.cpp
- nano/node/websocket.cpp
- nano/node/websocket.hpp
Possibility to add or remove accounts in an existing subscription through an `update` action with `accounts_add` and `accounts_del` arrays, both optional. This is useful for external wallets that can't use the all_local_accounts flag.
> Incremental options for ws confirmation subscription

- nano/node/election.cpp
When insert_inactive_votes_cache confirms the election it deletes itself from the active roots, causing the next confirm_if_quorum call to access freed memory.
> Fix election calling confirm_if_quorum after destruction

- nano/node/json_handler.cpp
- nano/node/network.cpp
- nano/node/telemetry.cpp
- nano/node/telemetry.hpp
- nano/rpc_test/rpc.cpp
Json requested being able to see the telemetry metrics of your own node. This can now be queried through the RPC with:
`{"action":"node_telemetry", "address":"::1", "port":"7075"}`
Where `port` is the peering port, (defaults are 7075 for live & 54000 for beta network).
`address` is any valid loopback address: `127.0.0.1`, `::1` or `[::1]`
> Request telemetry data for local node

- nano/core_test/network.cpp
- nano/core_test/node.cpp
- nano/core_test/node_telemetry.cpp
- nano/core_test/peer_container.cpp
- nano/node/cli.cpp
- nano/node/cli.hpp
- nano/node/node.cpp
- nano/node/nodeconfig.hpp
Introduce `--enable_udp` CLI flag, keeping but deprecating `--disable_udp` as it is now an unnecessary option but kept for backwards compatibility. Warning if both are used together.
Most changes are updates to tests so the same functionality is tested.
Unrelated: using `nano::writer::testing` in a couple block_processor tests.
> Disable UDP by default

- nano/nano_node/entry.cpp
- nano/node/portmapping.cpp
- nano/node/portmapping.hpp
If UDP is disabled ( default since #2555 ), does not request any port mapping for that protocol.
> Use only the necessary protocols in UPnP

- nano/core_test/active_transactions.cpp
- nano/core_test/node.cpp
- nano/core_test/socket.cpp
- nano/node/blockprocessor.cpp
- nano/node/bootstrap/bootstrap_bulk_pull.cpp
- nano/node/bootstrap/bootstrap_bulk_push.cpp
- nano/node/bootstrap/bootstrap_frontier.cpp
- nano/node/election.cpp
- nano/node/network.cpp
- nano/node/network.hpp
- nano/node/socket.cpp
- nano/node/socket.hpp
- nano/node/telemetry.cpp
- nano/node/transport/tcp.cpp
- nano/node/transport/tcp.hpp
- nano/node/transport/transport.cpp
- nano/node/transport/transport.hpp
- nano/node/transport/udp.cpp
- nano/node/transport/udp.hpp
- nano/node/wallet.cpp
The socket can drop messages even when the bandwidth limiter is instructed not to, e.g. when the peer isn't keeping up. This PR proposes a buffer drop policy instead of the current droppable flag, so callers can request the socket not to drop as well. 
Policies:
- limiter: Can be dropped by bandwidth limiter (default, as before)
- no_limiter_drop: The limiter should not drop
- no_socket_drop: The limiter should not drop, nor should the socket if possible
The `no_socket_drop` policy is applied to telemetry, otherwise no changes in what is dropped and not. This policy is supposed to be used for low volume messages (the socket impl allows a doubling of the write queue at most, as a safety valve.)
> Buffer drop policies

- nano/lib/utility.hpp
- nano/node/election.cpp
- nano/node/network.cpp
We have a handful of "potential data loss" warnings due to narrowing casts. This silences the warnings through a quite visible cast, which also checks that the values are in range in debug. C++ Core Guidelines/GSL defines a narrow_cast, but it's throwing (same with Boost's, which @wezrule mentioned). I think a good middle ground for our current code base is to assert. Ran through godbolt, and it's optimized away.
> Add GSL-style narrow_cast

- nano/lib/timer.cpp
- nano/lib/timer.hpp
- nano/node/socket.hpp
> Move back timer comments to header

- nano/core_test/toml.cpp
- nano/node/logging.cpp
- nano/node/logging.hpp
Boost 1.70+ allows for a combination of target_file_name, open_mode and enable_final_rotation to mimic the usual log rotation approach of a fixed log filename. This can be activated with a new toml config option, which is off by default to not break existing monitors that services might use. If built with < 1.70, activating the option will emit a stderr message and fall back to the old behaviour.
> Log stable filename

- nano/node/telemetry.cpp
Came over this when running core_test under tsan (node_telemetry.disconnects). Caught it the debugger, so tried to make a fix. Addresses two issues, one is accessing telemetry_impl without locking (which tsan caught), the other is `telemetry_impl->cached_telemetry_data.begin ()` sometimes segfaultet because it was empty, so added a not-empty check. @wezrule Not sure if the mutex order is correct or if this is the best way to handle it. Unable to trigger this code path on beta with node_telemetry rpc, but the test seems happy now.
> tsan: race in telemetry::ongoing_single_request_cleanup

- nano/rpc/rpc_secure.cpp
Same as #1681 but for tls acceptor
> Check against op aborted on secure rpc acceptor shutdown

- nano/core_test/vote_processor.cpp
https://gist.github.com/SergiySW/23743c3c818ac3b9bdc63cdca6ffe9cb
`vote` was changed in while processed
> [TSAN] vote_processor.flush test

- nano/core_test/confirmation_solicitor.cpp
* prevent self connection
* enable UDP
* add missing deadline
> Improve confirmation_solicitor.batches test

- nano/node/json_handler.cpp
- nano/node/node.cpp
- nano/node/online_reps.cpp
Update various places where write locks are done to only the tables actually used as opposed to locking all tables. Didn't bother touching CLI commands as it's not possible to have 2 different processes write to a RocksDB database
> [RocksDB] Limit write locks to necessary tables

- nano/rpc_test/rpc.cpp
Forgot to update rpc tests to use milliseconds in https://github.com/nanocurrency/nano-node/pull/2573 causing those tests to fail.
> Fix rpc telemetry test timestamps

- nano/core_test/block.cpp
- nano/core_test/distributed_work.cpp
- nano/core_test/fakes/work_peer.hpp
- nano/core_test/wallet.cpp
- nano/core_test/work_pool.cpp
- nano/lib/blocks.cpp
- nano/lib/blocks.hpp
- nano/lib/work.cpp
- nano/lib/work.hpp
- nano/nano_node/entry.cpp
- nano/node/active_transactions.cpp
- nano/node/blockprocessor.cpp
- nano/node/bootstrap/bootstrap_bulk_pull.cpp
- nano/node/bootstrap/bootstrap_bulk_push.cpp
- nano/node/common.cpp
- nano/node/json_handler.cpp
- nano/node/node.cpp
- nano/node/node.hpp
- nano/node/wallet.cpp
- nano/node/wallet.hpp
- nano/qt/qt.cpp
- nano/qt_test/qt.cpp
- nano/rpc_test/rpc.cpp
- nano/secure/ledger.cpp
As of this change, work version refers to different work algorithms. Each block type can unequivocally return its work version. It's a virtual method but defaults to `work_1`, and no type overrides it currently. A new algorithm will likely need a new state block definition, to avoid ambiguity, although it could be inferred by trying to validate with both algorithms and then setting the version to the one that was valid (if any).
This change allowed removing work_version as a parameter for some work_validate and work_generate overloads. The work watcher can also infer the version from the block it is watching.
> Block work version

- nano/core_test/confirmation_height.cpp
- nano/node/active_transactions.cpp
- nano/node/active_transactions.hpp
- nano/node/confirmation_height_bounded.cpp
- nano/node/confirmation_height_bounded.hpp
- nano/node/confirmation_height_processor.cpp
- nano/node/confirmation_height_processor.hpp
- nano/node/confirmation_height_unbounded.cpp
- nano/node/confirmation_height_unbounded.hpp
- nano/node/election.cpp
- nano/node/node.cpp
- nano/node/node.hpp
- nano/secure/ledger.cpp
- nano/slow_test/node.cpp
@SergiySW found that `election_winner_details` can be large during high TPS and contribute to holding to the active mutex for large periods while traversing it. This can be reduced by using its own mutex, also adding to the container after it has been added to the confirmation height processor (but while it is paused) means we can remove the batch callback cleanup code entirely. This is replaced with a callback which checks for already confirmed blocks added to the confirmation height processor from rare dependent election timings and removes from election winner details if still existing. Updated all tests to check the container is empty at the end.
TSAN run was clean.
> Reduce active mutex locking with election winner details

- nano/core_test/active_transactions.cpp
- nano/core_test/block.cpp
- nano/core_test/conflicts.cpp
- nano/core_test/fakes/work_peer.hpp
- nano/core_test/node.cpp
- nano/core_test/wallet.cpp
- nano/core_test/work_pool.cpp
- nano/lib/blocks.cpp
- nano/lib/blocks.hpp
- nano/lib/work.cpp
- nano/lib/work.hpp
- nano/node/active_transactions.cpp
- nano/node/distributed_work.cpp
- nano/node/json_handler.cpp
- nano/node/openclwork.cpp
- nano/node/wallet.cpp
- nano/node/websocket.cpp
- nano/rpc_test/rpc.cpp
Blocks now have a method to calculate and return the difficulty based on their work value, work version, and root. Work validation has been cleaned up, removing optional output difficulty from all methods, and with new work_difficulty and work_threshold methods. These are now used where they make sense, such as when previously work_validate was done even though we only wanted to compare the resulting difficulty. Functionally the same, but much less verbose.
Without changing the interface, we can decide to cache the difficulty in the block in the future, if it ever shows up in profiling.
Further changes will be required when a new work version is added, especially if the proof is larger than 8 bytes, but these changes are a step forward in that directtion.
> Block difficulty and work validation cleanup

- nano/core_test/utility.cpp
- nano/lib/CMakeLists.txt
- nano/lib/optional_ptr.hpp
`nano::optional_ptr` is a heap allocated optional, as opposed to the value-wrapper approach in boost/std::optional.
This idea was discussed in relation to #2596 where boost::optional causes some memory overhead in the value-not-present case, and using a bare unique_ptr is inconvenient as it's non-copyable.
> Utility: nano::optional_ptr

- CMakeLists.txt
- cmake/legacyModules/FindBoost.cmake
use version checks supported on older cmakes
use atleast 3.11 FindBoost.cmake as import targets are not properly
exposed on previous versions
> CMakeLists backwards compatibility

- nano/node/bootstrap/bootstrap_attempt.cpp
- nano/node/bootstrap/bootstrap_connections.cpp
- nano/node/bootstrap/bootstrap_lazy.cpp
- nano/node/confirmation_height_processor.cpp
- nano/node/portmapping.hpp
- nano/node/write_database_queue.cpp
- nano/node/write_database_queue.hpp
This prevents having all threads waiting and the system freezing. Mostly important for tests, especially with sanitizers, but could happen on stopping the node normally.
Portmapping requires an atomic bool, and the database queue doesn't after this change.
Other small related bootstrap changes included in this PR per @SergiySW suggestion.
Ran 7 times all core_test and no TSAN issues.
> Lock before stopping when notifying other threads

- nano/node/bootstrap/bootstrap_connections.cpp
- nano/node/cli.cpp
- nano/node/nodeconfig.hpp
Allowing multiple connections to same bootstrap server (useful in tests or for fastest beta nodes sync)
> Launch flag --allow_bootstrap_peers_duplicates

- nano/core_test/network.cpp
Reported in https://github.com/nanocurrency/nano-node/issues/1121#issuecomment-482037451 and confirmed locally; this is a timing issue in test (time between stat update and network container update) which only crops up under TSAN. Solved by checking stats and network sizes separately.
> Fix intermittent send_node_id_handshake unit test failures

- util/build_prep/bootstrap_boost.sh
This should prevent further issues with boost in the event urls go down in the future
> update url for sourceforge

- nano/node/blockprocessor.cpp
- nano/node/node.cpp
- nano/node/rocksdb/rocksdb.cpp
- nano/secure/blockstore.hpp
- nano/secure/blockstore_partial.hpp
`unchecked_del` is the only deleting function which checks for `not_found`. This is because in `unchecked_cleanup ()` we do a first pass where we do bulk reading then write afterwards separately, but before the write transaction it could be removed. RocksDB doesn't report not-found keys being deleted so we need to make sure that the key exists before deleting so that the cache can be updated correctly.
> [RocksDB] Only delete from unchecked when existence is guaranteed

- nano/core_test/node_telemetry.cpp
- nano/nano_node/entry.cpp
- nano/node/rocksdb/rocksdb.cpp
- nano/secure/blockstore.hpp
- nano/secure/blockstore_partial.hpp
Extracted this from #2558 as it has a fix for test failures which is blocking using RocksDB in CI.
Also noticed the `node_telemetry.many_nodes` test fails with RocksDB on Windows/Debug because it takes so long to initialize all the nodes; updated that test
> [RocksDB] Tests not reading account count from store correctly

- nano/core_test/confirmation_height.cpp
The issue comes from the second node processing blocks in the background. Simplifying the test to just check results from a single node
> Fix confirmation_height.gap_live intermittent test failure

- nano/node/request_aggregator.cpp
- nano/node/request_aggregator.hpp
And move sending cached_votes out of mutex locking.
Got a >2000ms mutex hold warning on a spam test, difficult to know the cause but this would be a good first step by simplifying the behavior around locking and unlocking the mutex. With this change, a similar spam test did not result in any warnings here.
> Simplify request aggregator mutex lock behavior

- nano/lib/blocks.cpp
- nano/lib/blocks.hpp
- nano/secure/ledger.cpp
This is used in some "warm" code paths, now avoids grabbing the previous block when the sideband is set, which is usually the case.
> Use the sideband when available in ledger.is_send

- nano/core_test/confirmation_height.cpp
@guilhermelawless noticed this test failing, but only on a Release/RelWithDebInfo build configuration. It failing on the `unbounded` confirmation height processor run because the `invalid_block` stat is only incremented on a Debug build (for optimization purposes). Modified the test to only check the stats when appropriate. Also added additional checks on the `confirmation_height_info` to make sure it is as expected.
> confirmation_height.modified_chain test fails on a non-debug build

- nano/node/wallet.cpp
- nano/node/wallet.hpp
Race on `handle` during teardown.
> tsan fix: rpc.wallet_destroy

- nano/nano_node/entry.cpp
block sideband is not required for some CLI tests
> Improve --debug_profile_bootstrap performance

- nano/core_test/active_transactions.cpp
- nano/core_test/confirmation_solicitor.cpp
- nano/node/active_transactions.cpp
- nano/node/active_transactions.hpp
- nano/node/blockprocessor.cpp
- nano/node/election.cpp
- nano/node/election.hpp
- nano/node/json_handler.cpp
- nano/node/node.hpp
- nano/node/repcrawler.hpp
- nano/node/websocket.cpp
- nano/rpc_test/rpc.cpp
- nano/secure/common.hpp
Each commit refers to a fix or enhancement.
- active_transactions had some unnecessary includes making it required to recompile very often (and thus the whole node code)
- Now allocating a new solicitor in every loop, in the future we can instance it with parameters based on the state of active_transactions
- `confirmation_request_count` was not getting incremented
- RPC confirmation_info would return confirmed elections, which was not the previous behavior
- Added unconfirmed and confirmed total to RPC confirmation_active, useful for keeping track in tests. Otherwise it could look like there are no active roots even though there could be several thousand confirmed.
- Fixed tests for active_transactions, the rep crawler was requesting confirmations instead so had to disable it.
- Added …
> Election refactor follow up

- nano/core_test/confirmation_solicitor.cpp
Currently fails (rarely) under tsan
> Make confirmation_solicitor.batches more robust under tsan

- nano/core_test/network.cpp
Fixes https://github.com/nanocurrency/nano-node/issues/1121#issuecomment-486108233
> Make network.replace_port more robust under tsan

- nano/core_test/testutil.hpp
- nano/node/testing.cpp
- nano/node/testing.hpp
We often have to check if an expression becomes true within a polling loop, which is quite verbose. 
Adding a testutil macro for this, so it becomes
```
ASSERT_TIMELY (5s, stats.count (stat::type::message, stat::detail::confirm_ack, stat::dir::out) == 2);
```
instead of
```
system.deadline_set (3s);
while (stats.count (stat::type::message, stat::detail::confirm_ack, stat::dir::out) != 2)
{
ASSERT_NO_ERROR (system.poll ());
}
```
(edit: https://github.com/nanocurrency/nano-node/pull/2632 fixed the request_aggregator test, adjusted this PR to be macro-only)
@guilhermelawless suggested a lambda version for more complex checks, added to system in the form of `poll_until_true`
> Add ASSERT_TIMELY

- nano/core_test/request_aggregator.cpp
Noticed by @SergiySW . With #2614 cached votes are sent after removing the request and unlocking the mutex, making it necessary to wait for confirm_ack count to be updated.
> Fix request_aggregator unit tests

- nano/core_test/node.cpp
- nano/core_test/socket.cpp
- nano/core_test/wallets.cpp
- nano/lib/utility.cpp
- nano/nano_node/entry.cpp
- nano/node/cli.cpp
- nano/node/node.cpp
- nano/node/node.hpp
#2594 added support for `--config` with inactive node. This PR adds support for reading the `config-node.toml` file too as well as making all CLI commands read it. This is quite prevalent when expecting commands to be used on the RocksDB ledger for instance.
I would suggest testing a couple random CLI commands to make sure the node config and --config CLI options are working as expected. 
Unrelated: `node.bandwidth_limiter` test had a hardcoded port
Unrelated: #2568 modified `assert_internal` to handle a case with Windows on Actions not outputting the stacktrace before exiting. This was resolved in https://github.com/nanocurrency/nano-node/pull/2591 so can be reverted.
> Read config file for CLI commands

- nano/node/active_transactions.cpp
- nano/node/repcrawler.cpp
- nano/node/repcrawler.hpp
Also cleans up redundant code in repcrawler, and makes it more clear confirmations are only solicited from principal representatives.
> Fix wrong number of representatives in confirmation solicitor

- nano/node/election.cpp
- nano/node/election.hpp
- nano/node/node.cpp
- Block broadcasting is used as a backup mechanism, now only done after and every 20 seconds
- Reduced send_confirm_req period from 15 to 5 seconds, as it is the primary mechanism and only targets representatives that haven't voted yet
- Increased time to activate dependencies ensuring at least one block broadcast is performed
> Bandwidth considerations following election refactor

- nano/core_test/node_telemetry.cpp
- nano/node/telemetry.cpp
- nano/node/telemetry.hpp
- nano/slow_test/node.cpp
@Json found that responses from the telemetry RPC were quite erratic:
The number of peers seemed to change with each response.
This was due to a couple issues::
- Latency disparity between the same peer. For instance if the first request took 100ms to arrive at the peer, and the second was quicker (50ms) the peer would reject that request because it falls within its "ddos" protection zone. To solve this, storing the "last reponse" time, as opposed to "last request time" as we when the start of the cache time begins.
- Another issue was that when retrieving the cached metrics locally, we were not taking into account the maximum response time due to delays (cpu spikes, network congestion etc), and we should return the most recent cache in the meantime.
> Telemetry results not correctly utilising cache timeouts

- nano/node/active_transactions.cpp
- nano/node/active_transactions.hpp
- nano/node/blockprocessor.cpp
- nano/node/blockprocessor.hpp
- nano/node/election.cpp
- nano/node/election.hpp
- nano/node/json_handler.cpp
- nano/node/nodeconfig.hpp
This was previously explored in #2440 with good results, but is not necessarily part of those changes.
The goal is to be able to hold more elections even if those are already confirmed. However, looping through all elections every 500ms (our default loop period) is not necessary, so this is only done every ~5 seconds. List of changes:
- `active_elections_size` increased from 10k to 50k. As a side effect, this fixes the slow frontier confirmation issue caused by lingering confirmed elections. `search_frontiers` was adjusted to prevent adding too many.
- Normally check top 5k elections every 500ms, but all 50k every 5 seconds.
- To avoid a situation where most of the top elections are confirmed, the loop counter is only increased for unconfirmed elections.
- Fixed election …
> Increase active elections capacity with periodic full checks

- nano/core_test/active_transactions.cpp
- nano/core_test/message_parser.cpp
- nano/core_test/network.cpp
- nano/core_test/node.cpp
- nano/lib/numbers.cpp
- nano/lib/stats.cpp
- nano/lib/stats.hpp
- nano/node/active_transactions.cpp
- nano/node/active_transactions.hpp
- nano/node/blockprocessor.cpp
- nano/node/blockprocessor.hpp
- nano/node/bootstrap/bootstrap_server.cpp
- nano/node/common.cpp
- nano/node/common.hpp
- nano/node/election.cpp
- nano/node/election.hpp
- nano/node/network.cpp
- nano/node/network.hpp
- nano/node/node.cpp
- nano/node/transport/udp.cpp
- nano/secure/network_filter.cpp
- nano/secure/network_filter.hpp
This is a less complex and risky alternative to #2539 where only blocks (publish messages) are filtered. The expected performance gains for filtering votes is not very large since there is no disk access involved. It also came with increased memory and processing efforts.
The duplicate publish filter is intended at reducing block processing (disk reads) arising from the use of a gossip protocol to push blocks.
Duplicates are checked before serializing the message. When it is unique, the digest is saved and passed around to network processing, which may drop it if the block processor is full. Cleaning up a long unchecked block also erases its digest from the filter.
`blocks_filter` in the block processor has been removed due to redundancy. The capacity of this filter is 256k, resulting in …
> Network duplicate filter for publish messages

- nano/node/confirmation_solicitor.cpp
With this change, less processing happens for elections that won't fit in the solicitor.
> Erase representatives with full queues when adding to confirmation solicitor

- nano/node/election.hpp
- nano/node/json_handler.cpp
- nano/node/telemetry.cpp
@Srayman reported some nodes could not request metrics to some peers during the bulk request phase, but could if requested manually. Now including temporary channels, I don't recall why they were removed as it doesn't seem to cause any issues.
Unrelated: Out of date comment
Unrelated: `block_count` RPC could use ledger cache.
> Include requesting telemetry metrics from temporary channels

- nano/core_test/timer.cpp
- nano/lib/timer.cpp
- nano/lib/timer.hpp
Currently, tick count is updated only on timer pause/stop, but we have some code that assumes it's updated on `value()` as well. This PR makes it so. @guilhermelawless also suggested returning ticks from restart, useful in test.
> Update tick count in timer::update

- nano/node/active_transactions.cpp
- nano/node/gap_cache.cpp
- nano/secure/common.cpp
- nano/secure/common.hpp
instead of 5 seconds. To allow more frequent new blocks arrival with realtime network & kess usage for expensive bootstrap
Thanks @argakiig for finding this!
> Delay inactive/gap cache bootstrap start for 30 seconds

- nano/core_test/signing.cpp
- nano/node/signatures.cpp
- nano/node/signatures.hpp
- nano/node/state_block_signature_verification.cpp
- nano/slow_test/node.cpp
@guilhermelawless noticed that the signature checking thread was blocking on the `future.wait ()` line sometimes. This was due to the `multi_threaded_cutoff` check being removed in https://github.com/nanocurrency/nano-node/pull/2570 (to enable better use of the thread pool). However there was an issue in the code if it was passed a value between [256, 512] which this check was dealing with. This has been solved, added a test to `core_test` to catch this in the future, as well as a more exhaustive `slow_test`.
> Signature checker blocking fix

- nano/core_test/node.cpp
This test was resorting to bootstrapping as backup when it should fail instead. Now the test has bootstrap disabled, and the fix was to locally process the genesis chain in each node, ensuring all representatives will be able to connect the last blocks.
With a sanitizer, less nodes are used because the repcrawler timings can remove one or more representatives during the test, making it fail.
Disabling aggressive flooding in blockprocessor::process_live makes the test fail, as expected. Also did some cleanup using ASSERT_TIMELY.
> Fix node.aggressive_flooding

- nano/core_test/active_transactions.cpp
- nano/core_test/confirmation_height.cpp
- nano/core_test/node.cpp
- nano/node/active_transactions.cpp
- nano/node/active_transactions.hpp
- nano/node/election.cpp
- nano/node/json_handler.cpp
- nano/node/wallet.cpp
- nano/rpc_test/rpc.cpp
Splitting off from #2441 which is now heavily out of date due to the confirmation height processor redesign. Moved the new test over for completeness.
The PR (#2441) changed `wallet::search_pending` to check `block_confirmed_or_being_confirmed` before calling `node_l->receive_confirmed`. I'm not sure for consistency if it should call it for in-progress blocks, I've instead made it so that `block_confirm` is not called. This is something reviewer should take into consideration about what is expected behaviour.
> Improve confirmation consistency

- nano/node/blockprocessor.cpp
- nano/node/vote_processor.cpp
To `100ms` , anything below is very noisy due to locking on the active mutex.
> Increase minimum time to log block processing

- nano/lib/utility.cpp
- nano/lib/utility.hpp
There exists a `__func__` standard variable/macro which provides an unqualified string of the current function. GCC has a `__PRETTY_FUNCTION__` macro and similar exists in MSVC. I found out that boost has a macro `BOOST_CURRENT_FUNCTION` which encapsulates all possible compiler extensions. Tested with MSVC & clang putting `debug_assert (false);` in the first active_transactions.cpp core_test:
MSVC:
```
Assertion (false) failed
void __cdecl nano::active_transactions_confirm_active_Test::TestBody(void)
C:\Users\Wesley\Documents\Nano\raiblocks\nano\core_test\active_transactions.cpp:14
```
Clang:
```
Assertion (false) failed
virtual void nano::active_transactions_confirm_active_Test::TestBody()
/home/wezrule/nano/raiblocks/nano/core_test/active_transactions.cpp:14
```
This is useful because …
> Output current function in assert diagnostics

- nano/core_test/difficulty.cpp
- nano/lib/config.hpp
- nano/lib/work.cpp
- nano/lib/work.hpp
- nano/node/blockprocessor.cpp
This article outlines the decision process for these thresholds: [Development Update: V21 PoW Difficulty Increases](https://medium.com/nanocurrency/development-update-v21-pow-difficulty-increases-362b5d052c8e).
Only adds definitions, `nano::work_threshold (version, details)` is not yet used anywhere besides tests.
We can change [these lines](https://github.com/nanocurrency/nano-node/compare/develop...guilhermelawless:work-threshold-definitions?expand=1#diff-5efcd17408c6db0b3d2576f25f90d4c4R87-R90) to early-return only for the live network if we would like to test live thresholds on the beta network.
> Definitions for work thresholds with epoch_2

- nano/core_test/active_transactions.cpp
- nano/node/active_transactions.cpp
- nano/node/active_transactions.hpp
- nano/node/election.cpp
Suggested by @Srayman .
Extends `active_transactions::recently_confirmed` with block hashes and another hashed-index to find by hash. After the separation from `recently_cemented` in https://github.com/nanocurrency/nano-node/pull/2625 , we can now increase the size freely. It's been increased to 64k instead of being tied to the confirmation history config (does this warrant a "breaking" label?).
With this change, we can check if a vote is for a recently confirmed block, avoiding polluting `inactive_votes_cache` and marking the vote as a replay if all hashes in it are recently confirmed blocks.
This should slightly impact the behavior of the network under saturation. I think an increase to `inactive_votes_cache` size should also be explored in the future.
Ran core_test under TSAN.
> Check if a vote is for a recently confirmed block

- nano/core_test/request_aggregator.cpp
- nano/node/request_aggregator.cpp
- nano/node/request_aggregator.hpp
Using `NANO_TIMED_LOCKS` , noticed the request aggregator mutex was sometimes being held for long, meaning I/O threads are locked as `request_aggregator::add` needs the mutex.
There is no reason to hold the mutex through the `aggregate` method, so now it releases it as soon as possible by moving the requests to a local variable.
Tests were adjusted as more stats now update in the background, making heavy use of ASSERT_TIMELY to clean it up.
All good under TSAN.
> Move all request aggregator operations out of the mutex hold scope

- nano/core_test/active_transactions.cpp
- nano/node/confirmation_solicitor.cpp
- nano/node/confirmation_solicitor.hpp
- nano/node/network.cpp
- nano/node/network.hpp
If we're not getting votes from representatives after some time, it makes more sense to send them the election winner rather than a random flood, but the flood is still kept at half scale. The duplicate filter prevents this from being a large burden on representatives.
Therefore, with this PR, the behavior is: **for up to 30 elections per loop, send to top sqrt(peers)/2 representatives that haven't voted for that election, and to sqrt(peers)/2 random peers.**
A second copy of `representatives` is made in the solicitor since some representatives could be erased from the list afterr #2649 .
Note: the change on the `update_difficulty` test is not necessary but makes it faster since it does not wait for the election broadcasting (outside of tests, the node broadcasts a block with updated …
> Directed block broadcasting for long elections

- nano/node/blockprocessor.cpp
The mutex is not required for state blocks anymore. Ran under TSAN.
> Optimize mutex access when adding blocks to block processor

- nano/core_test/active_transactions.cpp
- nano/core_test/conflicts.cpp
- nano/core_test/election.cpp
- nano/core_test/ledger.cpp
- nano/core_test/node.cpp
- nano/core_test/vote_processor.cpp
- nano/node/active_transactions.cpp
- nano/node/active_transactions.hpp
- nano/node/blockprocessor.cpp
- nano/node/election.cpp
- nano/node/node.cpp
This was previously part of https://github.com/nanocurrency/nano-node/pull/2440 , although with many changes.
Using a similar strategy of saving the last prioritized difficulty during `update_active_difficulty()`, the result of inserting an election now includes another boolean, hinting that the election may not be a priority due to a large number of active elections and low difficulty of the inserted block.
Active difficulty is now calculated only from these prioritized elections. The cutoff is defined at 10% of the `active_elections_size` config which is now 50k (so cutoff is 5k). During `request_confirm`, the top elections are prioritized.
When an election is prioritized, a vote is generated for the current winner.
-----
Except for the newly added test, all changes are due to changing …
> Delay voting for non-priority elections under saturation

- nano/core_test/node.cpp
- nano/node/blockprocessor.cpp
- nano/node/state_block_signature_verification.cpp
- nano/node/state_block_signature_verification.hpp
I noticed `node.block_processor_reject_state` was often freezing on windows, this is due to the verification callback being called and notifying the block processor before transitioning into an inactive state, so the `block_processor::flush` ends up waiting for the condition forever. I've added a second callback to solve this.
> Prevent getting stuck in block processor flush

- nano/core_test/active_transactions.cpp
- nano/core_test/difficulty.cpp
- nano/core_test/distributed_work.cpp
- nano/core_test/node.cpp
- nano/core_test/wallet.cpp
- nano/core_test/websocket.cpp
- nano/lib/config.cpp
- nano/lib/config.hpp
- nano/lib/work.cpp
- nano/nano_node/entry.cpp
- nano/node/active_transactions.cpp
- nano/node/distributed_work.cpp
- nano/node/json_handler.cpp
- nano/node/node.cpp
- nano/node/nodeconfig.cpp
- nano/node/nodeconfig.hpp
- nano/rpc_test/rpc.cpp
Once we move to c++17, these can be constexpr-defined in lib/config.hpp.
Further changes will be done in #2671
> Refactor work thresholds as nano::work_thresholds

- nano/core_test/ledger.cpp
- nano/lib/blocks.cpp
- nano/lib/blocks.hpp
- nano/node/blockprocessor.cpp
- nano/secure/common.hpp
- nano/secure/ledger.cpp
This is a follow up to #2638. With this PR in place, block work is now validated during ledger processing according to their epoch version and some block details. The following article details the reasoning for this change: [Development Update: V21 PoW Difficulty Increases](https://medium.com/nanocurrency/development-update-v21-pow-difficulty-increases-362b5d052c8e) . Threshold definition is found in #2638.
When an account is upgraded with epoch 2, blocks must meet the new thresholds or they are discarded during ledger processing. Before ledger processing, an initial work validation is performed on node entry.
Best reviewed while hiding linespace changes.
> Validate work difficulty during ledger processing

- nano/core_test/active_transactions.cpp
`recently_cemented` is only changed in the conf height observer callbacks, after cementing. This is the intended behavior, but the test was intermittently failing under TSAN.
No failures after 100 runs.
> Fix intermittent failure in active_transactions.confirmation_consistency

- nano/core_test/node.cpp
- nano/node/node.cpp
Moves `active.publish` until after election creation, otherwise the block is only added if the election already existed. Important for #2643 .
Added test fails without this change (send2 does not exist in election).
> Consistently add conflicting block to election

- nano/node/node.cpp
- nano/node/repcrawler.cpp
- nano/node/repcrawler.hpp
This can be done now that confirmed elections linger for 5 seconds in active roots after confirmation ( #2535 and follow up PRs ), such that there is little risk of a live vote being marked as indeterminate.
The rep crawler is always checked, but online weight only for live votes or rep crawler queries. Gap cache only for indeterminate votes.
> Optimize vote post-processing operations

- nano/core_test/ledger.cpp
- nano/core_test/wallet.cpp
- nano/core_test/websocket.cpp
- nano/node/distributed_work.cpp
- nano/node/json_handler.cpp
- nano/node/node.cpp
- nano/node/node.hpp
- nano/node/wallet.cpp
- nano/rpc_test/rpc.cpp
- nano/secure/common.hpp
- nano/secure/ledger.cpp
This flag is flipped when the first epoch 2 block is successfully processed.
Differences in behavior after the flag is flipped:
- RPC `work_generate` uses the new epoch 2 threshold as default
- RPC `work_validate` validates for the new threshold as default (breaking behavior in #2671)
- RPC `block_create` uses the new threshold as default
- Node wallet pre-caches work at the new threshold (mentioned by @SergiySW in #2671)
- Websocket `work` multiplier
> Epoch 2 started flag in ledger cache

- nano/node/active_transactions.cpp
- nano/node/network.cpp
- nano/node/transport/tcp.cpp
- nano/secure/common.hpp
Node version 19 (with TCP realtime & lazy bootstrap support)
> Increase minimum supported protocol version to 17

- nano/core_test/confirmation_height.cpp
- nano/node/active_transactions.cpp
- nano/node/active_transactions.hpp
- Time spent prioritising by uncemented blocks is done for a lower time (7ms in total by default) but more frequently (every request loop, once some constraints are met).
- Increased `confirmed_frontiers_max_pending_size` (previously named `confirmed_frontiers_max_pending_cut_off`) from 1000 to 10000. This allows buffer more in the conf height processor for processing.
- Separated an if statement in (the now named) `confirm_prioritized_frontiers` which can save a disk read in some circumstances.
- Renamed some functions/variables and added comments to better explain what is happening
During testing this in **automatic** frontiers confirmation mode on a non-pr node on the beta network using a `rel_time_next_frontier_check` of 10s a full cement took 2 hours (~20M blocks). using 30s it took …
> Improve automatic frontiers confirmation

- .github/workflows/analyzers.yml
- .github/workflows/release_test.yml
- .github/workflows/tests.yml
OSX excluded, setting appears to cause instability with test machines
https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idtimeout-minutes
> set timeout to 1hr to catch tests that hang

- nano/core_test/wallet.cpp
- nano/node/wallet.cpp
- nano/node/wallet.hpp
This is done by using the node alarm to delay the work cache action by 10 seconds (1 second in tests). Since those can't be canceled, the wallet keeps a map state of each account, and when the alarm triggers, this is checked to only queue the action if the root is the same.
The map is wrapped in `nano::locked`.
> Delay wallet work caching to allow using lower difficulty on demand

- nano/core_test/wallet.cpp
- nano/core_test/websocket.cpp
- nano/node/distributed_work.cpp
- nano/node/json_handler.cpp
- nano/node/json_handler.hpp
- nano/node/node.cpp
- nano/node/node.hpp
- nano/node/wallet.cpp
- nano/rpc_test/rpc.cpp
I'm marking as a non-functional change since we don't currently have any other work version (only `work_1`).
`epoch_1` threshold is still used directly in some places (most notably in `node.default_difficulty()`, but these should disappear after V21 is released.
> Work version parameter in default_difficulty and use it in more places

- nano/core_test/bootstrap.cpp
- nano/core_test/network.cpp
- nano/node/CMakeLists.txt
- nano/node/bootstrap/bootstrap.cpp
- nano/node/bootstrap/bootstrap.hpp
- nano/node/bootstrap/bootstrap_attempt.cpp
- nano/node/bootstrap/bootstrap_connections.cpp
- nano/node/network.cpp
- nano/node/network.hpp
- nano/node/peer_exclusion.cpp
- nano/node/peer_exclusion.hpp
Moves peer exclusion code into its own headers, moves the object from bootstrap initiator to network, some general cleanup and adds a validation test.
> Move excluded_peers to network

- nano/node/wallet.cpp
In https://github.com/nanocurrency/nano-node/pull/2680 I erased from `delayed_work` in `wallet::action_complete` to prevent queueing an outdated request, but this can make it assert when the request is not found later. Removing the assert is enough as the default action is to not do anything about it, which is correct.
> Remove assert if a delayed work cache request is not found

- nano/qt_test/qt.cpp
Missed this test in recent updates, saw failing in CI due the node targetting internally a lower difficulty.
> Fix qt test wallet.seed_work_generation

- nano/core_test/active_transactions.cpp
- nano/core_test/confirmation_solicitor.cpp
- nano/core_test/node.cpp
- nano/node/active_transactions.cpp
- nano/node/active_transactions.hpp
- nano/node/blockprocessor.cpp
- nano/node/blockprocessor.hpp
- nano/node/election.cpp
- nano/node/election.hpp
- nano/node/node.cpp
- Generate votes for:
- started election (if prioritized)
- changed winner
- election prioritization
- Move votes generator from block processor to active transactions
> Move vote generator calls into election code

- nano/qt_test/qt.cpp
Mouse clicks from the QTest library are not registering on radio buttons in more than one version of QT (confirmed by @argakiig), though they do work on CI. This change bypasses the testing library by calling the click action directly.
> Fix qt tests failing to click radio buttons

- nano/core_test/confirmation_height.cpp
- nano/core_test/utility.cpp
- nano/lib/threading.hpp
- nano/node/confirmation_height_bounded.cpp
- nano/node/confirmation_height_bounded.hpp
- nano/node/confirmation_height_processor.hpp
- nano/node/confirmation_height_unbounded.cpp
- nano/node/confirmation_height_unbounded.hpp
The atomic variables used do not have any synchronize-with relationships with any data across threads and all of the atomics involved are independent. One of the reasonable uses of relaxed atomics is dumb counters (not used for anything like control flow). It would allow more freedom for compiler/CPU optimizations due to removing the happens-before restrictions across the atomic boundary, especially as the algorithms used are single threaded. But I understand that it makes the code harder to read and reason about and the easiest way to shoot yourself in the foot generally, however I think in this case it is ok, especially as it isn't used for anything critical.
Bug: Some sizes were not being set in `confirmation_height_bounded` (again only affects the RPC stats -> objects).
Unrelated: …
> Using relaxed atomics for counts not involved in control flow in conf height processor

- nano/node/bootstrap/bootstrap.cpp
- nano/node/bootstrap/bootstrap_attempt.cpp
- nano/node/bootstrap/bootstrap_attempt.hpp
- nano/node/bootstrap/bootstrap_bulk_pull.cpp
- nano/node/bootstrap/bootstrap_connections.cpp
`pulling` is checked before some `condition.wait` meaning it must be modified while holding the mutex. The same for `new_connections_empty`.
I took a look through all condition variables in the node (not tests) and these were the only remaining as far as I could grasp.
> Prevent more rare deadlocks due to races for condition variables

- nano/core_test/network.cpp
- nano/core_test/node_telemetry.cpp
- nano/core_test/toml.cpp
- nano/lib/stats.cpp
- nano/lib/stats.hpp
- nano/node/bootstrap/bootstrap_attempt.cpp
- nano/node/bootstrap/bootstrap_server.cpp
- nano/node/logging.cpp
- nano/node/logging.hpp
- nano/node/peer_exclusion.cpp
- nano/node/peer_exclusion.hpp
- nano/node/telemetry.cpp
- nano/node/transport/tcp.cpp
- Manage excluded peers by address, not full endpoint
- Increase score on failed telemetry message
- Erase peer on failed bootstrap confirmation
- Check for peer exclusion before:
- accepting connection
- random keepalive
- fallback for channels not found during tcp message processing
- general TCP reachout
The node should no longer reconnect to excluded peers with TCP. By using UDP channels can still connect; no effort was made to use this feature with UDP since the intention is to remove support in the future, and the node now ships with UDP disabled by default.
> Prevent reconnecting to excluded peers with sufficient score

- nano/core_test/confirmation_height.cpp
- nano/node/confirmation_height_processor.cpp
- nano/node/confirmation_height_processor.hpp
- nano/node/confirmation_height_unbounded.hpp
- nano/slow_test/node.cpp
Was able to hit this assert in `confirmation_height_processor::run ()`:
`debug_assert (confirmation_height_unbounded_processor.pending_empty ());`
during the following scenario :
- There is at least 1 pending write entry in the unbounded conf height processor
- 0 blocks currently awaiting processing in the main conf height processor class
- A block was confirmed when hit the chain in the pending write above but was not a block higher than it.
- It must be in `confirmation_height_processor::pause ()` function so that `pause` is set (and the difference between the number of blocks uncemented is > unbounded_cutoff so that it hits the bounded processor), the main `run` loop on the conf height processor is iterated.
This causes unbounded pending entries not to be written and then the bounded …
> Incorrect cemented count during conf height algo transition

- nano/core_test/distributed_work.cpp
- nano/core_test/node.cpp
- nano/core_test/wallet.cpp
- nano/node/active_transactions.cpp
- nano/node/json_handler.cpp
- nano/node/node.cpp
- nano/node/node.hpp
- nano/node/nodeconfig.cpp
- nano/node/nodeconfig.hpp
- nano/node/wallet.cpp
- nano/rpc_test/rpc.cpp
Moves `max_work_generate_difficulty` out of config and into the node class, now calculated on the fly since it's rarely used.
`limited_active_difficulty` must be updated once #2691 is in.
> Ensure max_work_generate_difficulty is updated when changing the default difficulty

- nano/node/active_transactions.cpp
in core_test websocket.confirmation_options
> [TSAN] lock order inversion in active transactions / wallet

- nano/node/json_handler.cpp
- nano/rpc_test/rpc.cpp
This is a semantics change for RPC `work_validate`, due to the transition to new work levels with epoch 2.
Two new fields are added:
- `valid_all` , true if the work is valid at the **current default difficulty** (updated to epoch_2 levels after the first epoch_2 block is processed)
- `valid_receive` , true if the work is valid at the lower epoch_2 receive difficulty
If difficulty is not explicitly given, then the `valid` field is not included in the response, to break integrations loudly.
> Change response for RPC work_validate with implicit difficulty

- nano/node/bootstrap/bootstrap_bulk_pull.cpp
- nano/node/bootstrap/bootstrap_connections.cpp
- nano/node/bootstrap/bootstrap_connections.hpp
Hit this TSAN error on a recent spam test on beta (clang/linux):
https://gist.github.com/wezrule/eaf9b7ffd5ad3c2958c7e64448af0e78
Seems like protecting `start_time` is the appropriate step (`time_point` can't be atomic, at least in C++14). Not sure if that provides enough granularity but everything else is `std::atomic` so it seems sufficient.
> [TSAN] start_time data race in bootstrap_client

- nano/core_test/wallet.cpp
- nano/node/blockprocessor.cpp
- nano/node/testing.cpp
- nano/node/wallet.cpp
- nano/node/wallet.hpp
- Allow removing a block by its root, even if the hash does not match
- Simplify (1 less indent level) `work_watcher::watching`
- Test suite ensuring removal and propagation of updated block in different conditions
> Ensure propagation and removal for the work watcher

- nano/lib/locks.hpp
- nano/lib/threading.cpp
- nano/lib/threading.hpp
- nano/node/json_handler.cpp
- nano/node/node.cpp
- nano/node/node.hpp
- nano/rpc_test/rpc.cpp
- nano/slow_test/node.cpp
Note: the slow_test change is best reviewed with no whitespace changes
RPC epoch_upgrader was running on the worker but it was waiting on other tasks that it pushed to the worker as well. Through a series of unfortunate events, the exact behavior of the RPC was not being unit tested.
Since it is long running but rarely used, this changes it to run an async task on a new thread (which is attributed the new role "Epoch upgrader"). `node` stores a future of this task, to prevent running simultaneous upgraders. It's also wrapped in a `nano::locked`. The RPC now returns `"started":"0"` if another is already running.
There's also a fix for a count-limited upgrade, and the slow_test expanded to test it as well.
Ran an epoch upgrade on beta net under TSAN, stopping the node correctly stopped the …
> Epoch upgrader as an async task

- nano/core_test/active_transactions.cpp
The if condition is comparing a double to a boolean, whereas it should be comparing the multipliers directly. Not essential for v21 as just a test and it's been like this since inception
> Fix logic in active_transactions.prioritize_chains test

- nano/node/election.cpp
- nano/node/election.hpp
Noted by @Srayman when frontier confirmation inserts a few thousand blocks at once.
Instead of basing only on time, a hard limit on confirmation requests helps avoid resorting to fallback mechanisms (block broadcasting, escalating to dependents) too soon.
This is implemented with a new state `broadcasting` , and before moving to this state at least two confirmation requests must be done. This indirectly extends the time before moving to backtracking by 10 seconds.
Time between broadcasts reduced to 15 from 20 seconds.
> Separate election state for the broadcasting block fallback

- nano/node/active_transactions.cpp
- nano/node/confirmation_height_bounded.cpp
- nano/node/confirmation_height_bounded.hpp
- nano/node/confirmation_height_processor.cpp
- nano/node/confirmation_height_processor.hpp
- nano/node/confirmation_height_unbounded.cpp
- nano/node/confirmation_height_unbounded.hpp
- nano/node/write_database_queue.cpp
- nano/node/write_database_queue.hpp
- nano/secure/common.hpp
- nano/slow_test/node.cpp
The confirmation height processor can halt the block processor longer than necessary by holding onto the write_database_queue lock even when it releases the lmdb write lock. This adds the ability to release it. Ideally tested by @Srayman who first noticed this and can confirm its effectiveness (in combination with #2714).
- Frontiers confirmation time spent prioritising ledger accounts is increase by x5 to 25ms per request loop when the number of active transactions is low. This is to help find the few uncemented frontiers when the number of frontiers is large if they are missed during a high tps event.
- The bounded processor can modify the batch_write_size is give an optimum max amount of blocks to cement while holding the db write transaction to keep interference low with the block …
> Release write_guard lock when no longer required

- nano/core_test/node_telemetry.cpp
- nano/core_test/testutil.hpp
- nano/core_test/websocket.cpp
- nano/node/common.cpp
- nano/node/common.hpp
- nano/node/json_handler.cpp
- nano/node/network.cpp
- nano/node/telemetry.cpp
- nano/node/telemetry.hpp
- nano/rpc_test/rpc.cpp
This was suggested by @Inkeliz in https://github.com/nanocurrency/nano-node/issues/2726
Nodes now respond with the active difficulty in the telemetry response. Nodes on the beta network will need to upgrade to DB13 to receive telemetry from upgraded peers as this change is not backwards compatible.
Few unrelated changes:
- Moving signature/node_id to the bottom of the RPC as they are the least useful to people.
- Updated some variable names
- Timestamp didn't need to be checked in the `consolidate_data` section as it always uses average.
> Add active difficulty to node telemetry

- nano/node/confirmation_height_processor.cpp
- nano/node/confirmation_height_processor.hpp
- nano/slow_test/node.cpp
Changed `awaiting_processing` container from `std::unordered_set` to a boost multi-index container of a fifo queue and unique hash to keep the existing property of quick search but also operate on the oldest block hashes first. Won't really make a difference overall but seems more correct to cement blocks in same order they were confirmed.
Renamed `confirmation_height_bounded_processor` to `bounded_processor` (same with unbounded) as the extra variable details seem unnecessary.
Unrelated: Changing `batch_write_size` from 64k to 32k initially to be more conservative for nodes which restart with fully cemented ledgers where a feedback mechanism may not be in place for a while.
> Use a multi-index container to allow fifo queue for pending confirmations

- nano/core_test/toml.cpp
- nano/lib/rpcconfig.cpp
- nano/lib/tomlconfig.cpp
- nano/lib/tomlconfig.hpp
- nano/node/daemonconfig.cpp
One of the toml read methods was not reading within a try/catch. Re-arranged the methods slightly to avoid duplicating code.
There was also this check before setting the error when reading from a stream:
```
auto pos (stream.tellg ());
if (pos != std::streampos (0))
```
Removing this check has all tests pass nonetheless, and now only the lowest level method is responsible for setting the internal tree and error.
> Safely read override values when no config file is present

- ci/record_rep_weights.py
update record_rep_weights script to python3 as 2.7 is EoL
> record_rep_weights to py3

- nano/node/testing.cpp
For slow_test `node.fork_storm`
> Allow starting more that max_peers_per_ip test nodes

- nano/core_test/common.hpp
- nano/core_test/testutil.hpp
- nano/core_test/websocket.cpp
- nano/lib/blocks.cpp
- nano/lib/blocks.hpp
- nano/node/blockprocessor.cpp
- nano/node/json_handler.cpp
- nano/node/websocket.cpp
- nano/node/websocket.hpp
- Refactored obtaining the state subtype through ledger into a free function that uses the sideband block_details instead. Used in two RPCs and this new websocket, as it's guaranteed that blocks will have a sideband there.
- New websocket subscription for blocks that were just processed and it is the first time they're seen. One application of this is an integration watching blocks that they didn't create themselves, and potentially updating them with new work. Like an external work watcher. The name of the topic is chosen to be very explicit that these blocks are not yet confirmed.
- (Unrelated) fixed a couple warnings when compiling core_test
> Websocket new_unconfirmed_block

- nano/node/json_handler.cpp
Noticed I wasn't getting a websocket notification if `use_peers` is `false`. The easiest way of accomplishing this is just using distributed work without peers which fallsback to local work generation immediately.
Sample notification
```json
{
"success": "true",
"reason": "",
"duration": "690",
"request": {
"version": "work_1",
"hash": "718CC2121C3E641059BC1C2CFC45666C99E8AE922F7A807B7D07B62C995D79E2",
"difficulty": "ffffffc000000000",
"multiplier": "1.000000000000000"
},
"result": {
"source": "local",
"work": "1627ff6c0ddbcab4",
"difficulty": "ffffffd7529945e2",
"multiplier": "1.573357211876761"
},
"bad_peers": ""
}
```
> Websocket notification for RPC work_generate without peers

- nano/core_test/websocket.cpp
- nano/node/active_transactions.cpp
- nano/node/node.cpp
- nano/rpc_test/rpc.cpp
Was affecting websocket active_difficulty. Tests for it and RPC active_difficulty now pre-upgrade the node to epoch2 to ensure the output is correct.
> Remove invalid uses of epoch_1 work threshold

- nano/rpc_test/rpc.cpp
This was simply due to the first block getting auto received on confirmation so the `receive_action` would fail. Disabling voting solves it.
Removed the thread sleeps, they don't seem to be required for this test.
> Fix rpc.wallet_history failures

- nano/core_test/ledger.cpp
This is likely due to wallet rep counts not updating quick enough on CI due to online weight fluctuating very heavily in this test, causing votes to not be generated. Waiting for the online weight to stabilize by waiting on a voting rep should fix it.
Ran CI twice and didn't trigger whereas it would trigger often without this change.
> Fix system.generate_send_new intermittent failures

- nano/core_test/active_transactions.cpp
- nano/node/election.cpp
- nano/node/election.hpp
Mostly applicable to tests, but consider this sequence of events:
- An election gets created for a processed block
- A vote arrives for a conflicting block; gets added to election, not inactive
- The conflicting block gets processed
Currently, `election::publish` calls `insert_inactive_votes_cache` but votes are not tallied since there was no inactive vote.
This fixes the above situation by calling `confirm_if_quorum` if no votes were cached when a new conflicting block is inserted.
> Tally votes on conflicting block with no inactive votes

- nano/core_test/node.cpp
Failure was repeatable for me on windows. I git-bisected it to #2535 but couldn't spot any change that would cause this. A slight change in timings could be responsible. Adjusted the test conditions accordingly.
> Fix node.fork_invalid_block_signature intermittent failures, re-enable on windows CI

- nano/core_test/network.cpp
- nano/node/network.cpp
- nano/node/network.hpp
Was only reproducible on MacOS (for what ever reason), the `socket::async_connect` completion handler had not been called yet, so the `syn_cookie` assignment may have come after the purging in the test which can mess up the node handshake, due to the `syn_cookie` already existing. Am now  checking that the `syn_cookie` is set before continuing.
> Fix network.tcp_no_connect_excluded_peers test failure

- nano/core_test/active_transactions.cpp
- nano/core_test/node_telemetry.cpp
- nano/core_test/wallet.cpp
- nano/nano_node/entry.cpp
- nano/node/active_transactions.cpp
- nano/node/bootstrap/bootstrap_attempt.cpp
- nano/node/election.cpp
- nano/node/ipc/ipc_access_config.cpp
- nano/node/network.cpp
- nano/node/network.hpp
- nano/node/write_database_queue.cpp
- nano/rpc_test/rpc.cpp
The Xcode IDE gives various warnings in the Issue Navigator, mostly around unused variables and constructor initializer list differences with the class member variable order. The `std::string to_string (nano::ipc::access_permission permission)` function is probably still useful later, but currently it is dead code (there's a warning about it being unused). Can always be added later when necessary.
> Fix Xcode warnings

- nano/core_test/wallet.cpp
- nano/node/voting.cpp
- nano/node/wallet.cpp
This relaxes restrictions on the action and avoids potential deadlocks through lock-order-inversion.
Best reviewed with hidden whitespace changes.
>  Perform wallet representative action without holding any mutex

- nano/core_test/wallet.cpp
By random chance, the pre-set work could pass even for the blocks it's not intended for (due to test difficulty being low). The two removed lines are, in the end, out of scope for this test.
> Fix intermittent failure in test wallet.work_cache_delayed

- nano/node/confirmation_height_bounded.cpp
- nano/node/confirmation_height_processor.hpp
- nano/node/confirmation_height_unbounded.cpp
Requested by @Srayman for some profiling statistics similar to the block processor which spits out the number of blocks and how long they took to process when > 100ms of time was spent. Some new example log output:
```
[2020-May-06 16:45:31.406785]: Cemented 30893 blocks in 146 milliseconds (bounded processor)
[2020-May-06 16:45:33.703541]: Cemented 30822 blocks in 155 milliseconds (bounded processor)
[2020-May-06 16:45:36.177800]: Cemented 31001 blocks in 148 milliseconds (bounded processor)
[2020-May-06 17:00:09.319870]: Cemented 22364 blocks in 96 milliseconds (unbounded processor)
[2020-May-06 17:00:14.168904]: Cemented 17178 blocks in 102 milliseconds (unbounded processor)
```
I've changed the bounded processor to also dynamically update the `batch_write_size` at the end in the case …
> Add cemented block log timings

- nano/node/network.cpp
This behavior was recently changed as part of #2468 . This specific change has the least impact to bandwidth usage out of all changes in that commit.
The list of peers to which a new vote is republished now includes PRs. Fanout is unchanged at `.5 * sqrt(peers)`. The effective fanout change on the main network is from ~14 to ~17.
This change allows PRs that do not directly connect to other PRs to still see their votes. Ensuring PR connectivity is another approach that will be explored in the future.
Note that this change does not apply to PRs as they do not republish votes since #2468 .
> Republishing a vote to principal representatives

- nano/core_test/confirmation_height.cpp
- nano/core_test/difficulty.cpp
- nano/lib/stats.cpp
- nano/lib/stats.hpp
- nano/node/confirmation_height_bounded.cpp
- nano/node/confirmation_height_bounded.hpp
- nano/node/confirmation_height_unbounded.cpp
- nano/node/confirmation_height_unbounded.hpp
- nano/secure/blockstore_partial.hpp
`release_assert` if there is a problem found in the conf height processor as this should never happen. 
Will log to the console before this happens though and added/modified some tests to use the bounded/unbounded processors directly to allow death testing to ensure it is working correctly. Death tests named as recommended by https://github.com/google/googletest/blob/master/googletest/docs/advanced.md#death-test-naming
> Force node exit if ledger inconsistency in the conf height processor is found

- docker/node/config/config-node.toml
The rpc server is enabled by default and port mappings are provided for both the rpc server and the websocket server. Keeping the configuration and documentation consistent between the two will be clearer.
> Enable WebSocket server by default in Docker image

- CMakeLists.txt
- ci/actions/osx/install_deps.sh
- docker/ci/Dockerfile-clang
- docker/ci/Dockerfile-clang-6
- docker/ci/Dockerfile-gcc
- util/build_prep/bootstrap_boost.sh
- util/build_prep/centos/prep.sh.in
- util/build_prep/fetch_boost.sh
- util/build_prep/macosx/prep.sh.in
- util/build_prep/ubuntu/prep.sh.in
add 1.72 and 1.73 for convenience
* docs at https://github.com/nanocurrency/nano-docs/pull/297
* boost(1.70 static/shared) cache used again on nix and osx builds
Closes #2776 as it was a workaround, no longer necessary.
> Set boost min to 1.69

- nano/core_test/uint256_union.cpp
- nano/lib/numbers.hpp
- nano/slow_test/node.cpp
Extends the specialization of std::hash to cover all bytes of 256_union and 512_union. This affects how set-like containers store them internally.
> Union std::hash coverage

- nano/core_test/confirmation_solicitor.cpp
- nano/node/confirmation_solicitor.cpp
Also fixed up the existing test, was not consistently working as intended.
> Confirmation requests and broadcasts if available vote is for a conflicting block

- nano/core_test/confirmation_height.cpp
- nano/node/active_transactions.cpp
- nano/node/active_transactions.hpp
- nano/node/confirmation_height_bounded.cpp
- nano/node/confirmation_height_bounded.hpp
- nano/node/confirmation_height_processor.cpp
- nano/node/confirmation_height_unbounded.cpp
- nano/node/confirmation_height_unbounded.hpp
- nano/node/election.cpp
- nano/node/node.cpp
- nano/node/node.hpp
- nano/node/nodeconfig.cpp
- nano/node/online_reps.cpp
- nano/slow_test/node.cpp
The issue is that in `node::processed_confirmed` there was an assumption that x2 the max block processor time (default 5s), so 10s was enough for the block to be committed to the ledger after being confirmed. This was not always the case during high load (1000tps) on some nodes where it might have taken longer. That number has now been doubled but also it was hardcoded before and didn't respect config changes which has now been changed. Updated the validation for the max block processor time so that it is always greater than the process confirmed interval. In the event the block still doesn't exist, it will handle that case too and allow the block to be confirmed later rather than be stuck.
The tests added were used during the debugging of this issue. They use send/receive to self which …
> Stuck uncemented blocks after heavy load

- nano/core_test/socket.cpp
Causing access of the counted_completion mutex after it goes out of scope.
> [TSAN] Fix off-by-one in socket.drop_policy test

- nano/node/blockprocessor.cpp
- Incorrectly formed boost format
- Work and difficulty not logged as hex
> Fix insufficient work logging

- nano/core_test/confirmation_solicitor.cpp
- nano/core_test/election.cpp
- nano/core_test/ledger.cpp
- nano/node/active_transactions.cpp
- nano/node/active_transactions.hpp
- nano/node/election.cpp
- nano/node/election.hpp
- nano/secure/ledger.cpp
- nano/secure/ledger.hpp
When an election is backtracked (fallback behavior), its dependents are activated. When many blocks are unconfirmed in the same chain, it's more efficient to bisect it and activate the midpoint between the current election height and the current confirmation height. This should converge sufficiently fast.
For worst case scenarios, also added a pessimistic fallback that starts an election for the first unconfirmed block.
> Bisected election backtracking

- nano/core_test/active_transactions.cpp
- nano/node/active_transactions.cpp
- nano/node/active_transactions.hpp
- nano/node/election.cpp
- nano/secure/blockstore.hpp
- nano/secure/blockstore_partial.hpp
@wezrule noticed a failure during a test related to a block not being found in the ledger when activating dependencies.
There are in fact two issues:
1. In between adding the dependency and activating, the block could be rolled back, so we need to check if it exists
2. Due to potential simultaneous sideband changes in ledger processing, we need to retrieve a new copy of the block instead of simply checking if it exists and using the election object.
Added `store::block_account_calculated` that is used when we already have a sideband-loaded block in memory.
----
For reviewing would recommend hiding whitespace changes
> Retrieve block when activating dependencies

- nano/load_test/entry.cpp
To output a descriptive error message rather than:
```
terminate called after throwing an instance of
'boost::process::process_error'
what():  execve failed: No such file or directory
```
> Check executable paths in load_test

- nano/nano_node/entry.cpp
- nano/node/node.cpp
- nano/secure/common.cpp
- nano/secure/common.hpp
Noticed that the `--debug_rpc` CLI command wasn't correctly reporting on some things like cemented block count. This is because `inactive_node_flag_defaults` disables generating the cache unless it needs to, however also wasn't doing it for all, which it now does.
`--compare_rep_weights` & `--debug_dump_representatives` were not actually using the `node_flags` variable they created. This worked by chance because any setting of rep/account/epoch2 will set them all as any 1 requires iterating over all accounts (account/epoch2 were not being set to 0 in `inactive_node_flag_defaults`.
> CLI commands incorrect ledger cache setup

- nano/node/node.cpp
- nano/node/nodeconfig.hpp
- nano/node/write_database_queue.cpp
- nano/node/write_database_queue.hpp
- nano/slow_test/node.cpp
`node_telemetry.under_load` was failing. git bisected and found it was caused by https://github.com/nanocurrency/nano-node/pull/2782. It seems the increase in iterations on the test network (it's gone from 20 to 400!) was creating too much work. As the number of iterations is dependent on the block_processor_batch_max_time, I am changing default if using test network, which should scale with the `process_confirmed_interval` which is also changed from 500ms to 50ms on test network.
`many_accounts_send_receive_self` can time out after sequential voting PR, increase deadline timer.
Fixes a bug with popping from empty `write_database_queue` when stopping the node causing a hang.
> Slow test fixes

- nano/core_test/election.cpp
- nano/core_test/node.cpp
- nano/node/active_transactions.cpp
- nano/node/active_transactions.hpp
- nano/node/election.hpp
This was a regression introduced by https://github.com/nanocurrency/nano-node/pull/2778
Adds two tests to ensure proper behavior:
- `election.dependencies_open_link` which covers the fix by itself
- `node.dependency_graph_frontier`, a more complex test ensuring we can walk down a more complex graph before confirming it from the bottom up. This test is a bit long at 8 to 10 seconds (same with sanitizers though), but seems like a strong addition.
> Fix open blocks not getting activated through dependencies

- nano/core_test/toml.cpp
- nano/lib/rpcconfig.cpp
- nano/lib/rpcconfig.hpp
- nano/rpc/rpc_connection.cpp
- nano/rpc/rpc_handler.cpp
@Json's ramdisk node is crashing when pumping out 2000BPS `process` RPC calls. There are some boost standard error outputs suggesting problems with rotating the files at this high logging output speed.
However I cannot reproduce this even, even with spamming 50MB of log messages per second over a few threads. Seems to be something special about his set-up, removing the logging output manually fixed the issue for him, so am adding a logging section to the rpc config which allows these messages to be disabled (they are enabled by default). This can be extended in the future to change the rotation/max size size and maybe some other options, but right now this should be sufficient.
> Add logging section to rpc config to optionally disable logging

- nano/core_test/active_transactions.cpp
- nano/core_test/confirmation_height.cpp
- nano/core_test/conflicts.cpp
- nano/core_test/gap_cache.cpp
- nano/core_test/ledger.cpp
- nano/core_test/node.cpp
- nano/core_test/vote_processor.cpp
- nano/node/active_transactions.hpp
- nano/node/blockprocessor.cpp
- nano/node/node.cpp
- nano/node/testing.cpp
- nano/node/testing.hpp
- nano/rpc_test/rpc.cpp
Building off the multi-level election controls added in https://github.com/nanocurrency/nano-node/pull/2785, this PR changes the block processing behavior to only start an election if the block's ancestors are confirmed.
- There is a superlinear usage of resources the more elections are active for the same chain, which is now prevented.
- On confirming an election, the successors (in the same chain and destination chain for sends) are activated (functionality from https://github.com/nanocurrency/nano-node/pull/2785).
- Frontier confirmation works as the fallback behavior, for bootstraps and nodes restarting after getting blocks. Backtracking (https://github.com/nanocurrency/nano-node/pull/2778) later starts the bottom-most election if unable to confirm the frontier.
> Sequential elections

- nano/core_test/CMakeLists.txt
- nano/core_test/telemetry.cpp
- nano/node/CMakeLists.txt
- nano/node/json_handler.cpp
- nano/node/peer_exclusion.hpp
- nano/node/telemetry.hpp
- nano/node/transport/tcp.hpp
- nano/rpc_test/rpc.cpp
- nano/slow_test/node.cpp
Also updated some other places to use `telemetry` instead of `node_telemetry`
> Make RPC name consistent with stats, websocket & protocol naming for telemetry

- nano/node/blockprocessor.cpp
Since we drop the unchecked table and download blocks again after a node restart, this isn't necessary. It's creating a local loop when not dropping unchecked blocks (flag [`--disable_unchecked_drop`](https://docs.nano.org/commands/command-line-interface/#-disable_unchecked_drop) which is used by [`--fast_bootstrap`](https://docs.nano.org/commands/command-line-interface/#-fast_bootstrap)
Removing this saves a disk read for unchecked blocks and all tests are passing without further changes.
Thanks @Srayman for finding this one!
> Process old does not need to queue unchecked

- nano/nano_node/daemon.cpp
- nano/secure/ledger.cpp
Some reports of node taking a minute or so to start up on fresh boot. Instead of having blank prompt, output something semi-reassuring
> Output ledger initialization message on start-up

- nano/core_test/active_transactions.cpp
- nano/core_test/ledger.cpp
- nano/core_test/node.cpp
- nano/core_test/request_aggregator.cpp
- nano/lib/blockbuilders.cpp
- nano/lib/blockbuilders.hpp
- Adds `build_shared()` to the abstract builder, so that the caller doesn't have to specify `std::shared_ptr<nano::state_block> ...`,   using `auto` instead. Keeps tests formatting clean.
- Use block builders in all `active_transactions` and `node` tests from `core_test`
Used the following script used to convert (95% of cases work without modifications): https://gist.github.com/guilhermelawless/6424ea9199db7584e314381cbce5dc65
> Block builders build_shared and use in more tests

- nano/core_test/node.cpp
- nano/lib/stats.cpp
- nano/lib/stats.hpp
Notes: https://github.com/cryptocode/notes/wiki/Histogram-in-stats
Down the line, we can switch this to boost.histogram (requires 1.70+ so it's too soon)
Qt wallet updates and actual use of the histogram stats api can be done in separate PRs.
> Add histogram support to stats
