nanocurrency/nano-node

CMakeLists.txt, rai/rai_node/entry.cpp
Tested on archlinuxarm for armv7l and aarch64
=> Add the possibility to build rai_node on arm too

CMakeLists.txt
rai_node building speed increased by 30%
=> Remove unused cryptopp .cpp

rai/node/rpc.cpp, rai/node/rpc.hpp
account_get, account_key, key_create, key_expand
=> Porting several RPC from CLI

rai/node/rpc.cpp, rai/node/rpc.hpp
account_remove, representatives, wallet_change_seed & frontier_list (list of frontiers in wallet)
=> Porting RPC from CLI part 2 & extended RPC frontier_list

rai/qt/qt.cpp
following on from #103 simple change to switch default unit to Mrai as more commonly used.
=> Switch default units to Mrai

rai/qt/qt.cpp
https://github.com/clemahieu/raiblocks/issues/69
=> Auto-refresh by entering in "Peers"

rai/qt/qt.cpp, rai/qt/qt.hpp
https://github.com/clemahieu/raiblocks/issues/121
=> Multi-connection Bootstrap GUI button

rai/core_test/rpc.cpp, rai/node/rpc.cpp, rai/node/rpc.hpp
deterministic_key & bulk requests
=> RPC deterministic_key, accounts_balances, accounts_frontiers, accounts_pending

rai/qt/qt.cpp
https://github.com/clemahieu/raiblocks/issues/73
=> GUI: "Create account" with locked wallet

rai/qt/qt.cpp, rai/qt/qt.hpp
https://github.com/clemahieu/raiblocks/issues/110
=> GUI: Wallet balance in advanced

rai/qt/qt.cpp
Partially: https://github.com/clemahieu/raiblocks/issues/70
=> GUI: Multiple accounts restore from Seed

rai/qt/qt.cpp, rai/qt/qt.hpp
\+ show representative of current account
=> GUI: change representative & password with locked wallet

CMakeLists.txt, rai/qt/qt.cpp, rai/qt/qt.hpp
& correct status at startup if wallet isn't protected with password
& default rai_live_network for RAIBLOCKS_GUI build
=> GUI: "Accounts" button in main menu

rai/qt/qt.cpp
https://github.com/clemahieu/raiblocks/issues/151
=> Feedback to incorrect send & seed import

rai/node/bootstrap.cpp, rai/node/bootstrap.hpp
1st ~200k blocks should sync faster
=> Initial Faucet & Landing accounts bootstrap

rai/core_test/block_store.cpp, rai/core_test/rpc.cpp, rai/secure.cpp, rai/secure.hpp
https://github.com/clemahieu/raiblocks/issues/194
https://github.com/clemahieu/raiblocks/issues/19
=> Adding blocks_info subdatabase for faster block_account & block_balance

blake2/blake2.h, blake2/blake2b-ref.c, rai/rai_node/entry.cpp
to fix ARM64 compiling after updating blake2b SSE
=> Fix: Updating blake2b reference to latest version

rai/secure.cpp
=> Adding feedback to database upgrade (v10)

.gitmodules
=> Fix submodule url

rai/lib/work.hpp
Existing code relies on transitive includes but this fails on some targets.
=> add <condition_variable> include

CMakeLists.txt
=> cmake: add rpath config for libraries, add librai_lib

Info.plist
See: http://doc.qt.io/qt-5/highdpi.html
=> Fix blurry text on retina displays on OSX.

rai/node/wallet.hpp
=> fix another typo

CL/cl.hpp
=> Fix typo in comment

bootstrap.py
Changed file opens to "with open()"s, https://stackoverflow.com/questions/31334061/file-read-using-open-vs-with-open
Changed string concatenation from + to "".join() because it's faster for 3 elements
Changed use of a counter variable "block_number" and 3 conversions to string to enumerate() and one conversion to string
Should still work just the same as it did before, even if using Python 2.7 upward
Double check it still works though please
=> Improved python code in bootstrap.py

CMakeLists.txt
Should fix #337 and several others
=> flip default for RAIBLOCKS_SIMD_OPTIMIZATIONS: OFF

rai/core_test/uint256_union.cpp, rai/lib/numbers.cpp
=> Fixes bug when converting string to decimal in uint128_union/uint256_union

.travis.yml, ci/build-travis.sh, ci/test.sh
- Build the entire project
- Execute the tests
- mask test failures for now
=> Add tests to travis (failures masked)

.github/ISSUE_TEMPLATE.md
Hi there,
It's hard to solve a problem when important details are missing.
Ref: https://github.com/blog/2111-issue-and-pull-request-templates
Best regards,
Donutloop
=> doc: add issue template for creating a new issue

rai/lib/blocks.cpp, rai/lib/numbers.cpp, rai/node/node.cpp, rai/node/wallet.cpp, rai/secure.cpp
Hey guys, first time contributing! I went though some code and tried to find any places things could be cleaned up. This doesn't address any specific bug, but I thought this might be slightly useful and a good way to see some of the code.
I'm hoping someone with more knowledge of repo can take a look at commit `e0292db`, seemed a bit strange to me.
Also, are performance PR's wanted? I thought I may have seen some places to improve some performance and if so I'd love to help out.
If this satisfies any bounty my XRB address is `xrb_15fy38cbw7t4tmwwrg3dri1w9r4hnabwcam787asoqb53a1mxe8mfqipahu8`
=> Code clean up

LICENSE
A year range is okay according to several sources, including [FSF](http://www.gnu.org/licenses/gpl-howto.html).
=> License copyright year update

rai/node/testing.cpp, rai/qt_test/qt.cpp
This fixes all of the 7 failing QT tests.
@androm3da I believe this is applicable for your bug bounty, along with #452. I've PM'd you my XRB address on Discord. There I'm `PlasmaPower#0068`.
=> Fix QT tests

rai/node/bootstrap.cpp, rai/node/bootstrap.hpp
If bulk pull client fails in the middle of large pull
=> Requeue pull with last received expected block

rai/core_test/rpc.cpp, rai/lib/blocks.cpp, rai/lib/blocks.hpp, rai/node/bootstrap.cpp, rai/node/bootstrap.hpp, rai/node/common.cpp, rai/node/common.hpp, rai/node/node.cpp, rai/node/rpc.cpp, rai/secure.cpp
- added virtual destructors to classes w/virtual methods
- added qualification to std::abs to get the generic func
=> Fix warnings - virtual destructors

.gitlab-ci.yml, ci/build.sh
- build boost deps
- remove zesty, add xenial+artful
=> Fix gitlab CI: add boost bootstrap

rai/lib/numbers.cpp, rai/node/node.cpp, rai/node/wallet.cpp
A cleanup PR in the "flat is better than deep" category.
=> Simplify code; mostly reduced nesting.

rai/node/bootstrap.cpp
Added async_read zero-size check to receive_frontier.
I believe this fixes the receive_frontier example in https://github.com/clemahieu/raiblocks/issues/415.
async_read seems to fail in two different ways on disconnects. You get a "Bad file descriptor" error most of the time. However, async_read sometimes complete "successfully" with a size of zero, so that must be checked as well.
=> receive_frontier fix 

.gitignore, rai/node/bootstrap.cpp
Typo in bootstrap.cpp @1011
--	if (connection->node->config.logging.bulk_pull_logging ())
++	if (node->config.logging.bulk_pull_logging ())
Not much to see here just a minor typo and updating .gitignore
=> typo and .gitignore

.gitignore, .travis.yml, ci/build-travis.sh, ci/test.sh, docker/ci/Dockerfile, load-tester/Cargo.lock, load-tester/Cargo.toml, load-tester/src/launch_node.rs, load-tester/src/main.rs, load-tester/src/rpc.rs, rai/node/rpc.cpp
This PR adds a test for very high transaction load, written in Rust.
I'm also going to open a couple of issues for problems identified with this. Edit: #537 #538
=> Add load tester

rai/node/bootstrap.cpp
https://github.com/clemahieu/raiblocks/issues/524
=> Fixing requeue_pull

rai/lib/blocks.cpp, rai/lib/blocks.hpp, rai/node/bootstrap.cpp, rai/node/bootstrap.hpp, rai/node/node.cpp, rai/node/rpc.cpp, rai/secure.cpp
=> Replace empty virtual destructors with =default

rai/node/bootstrap.cpp, rai/qt/qt.cpp
=> Revert QTimers Fixes #527

docker/node/Dockerfile
Use `https://sourceforge.net` instead of `http://sourceforge.net`
=> Update Dockerfile - use `https://` instead of `http://`

.travis.yml, ci/build-docker-image.sh, ci/build-travis.sh, ci/deploy-docker.sh
The first build of this will take a while, but after the first build on master it'll have a cache to go against.
Edit: fixes #577
=> Deploy docker images in Travis

rai/node/node.cpp, rai/rai_node/entry.cpp
To resolve issue https://github.com/clemahieu/raiblocks/issues/328
Replacing https://github.com/clemahieu/raiblocks/pull/342
=> Adding data_path support for CLI operations

.travis.yml, ci/build-docker-image.sh, ci/build-travis.sh, ci/custom-timeout.sh, ci/deploy-docker.sh, docker/ci/Dockerfile, docker/node/Dockerfile, doxygen.config, rai/core_test/block_store.cpp, rai/core_test/node.cpp, rai/secure.cpp, rai/secure.hpp
Also includes clang-format so we can check that Travis passes.
I've been testing this a lot by enabling Travis on my fork. It's succeeded 3 times, and it's on its 4th run right now here: https://travis-ci.org/PlasmaPower/raiblocks/jobs/337654181
=> Docker deploy (for real this time)

README.md
RaiBlocks -> Nano, link updates and more resources.
Would be nice to update the unpruned ledger size info too (anyone got exact size?)
Preview: https://github.com/cryptocode/raiblocks/tree/readme-update-feb-2018
=> Readme update feb 2018

.gitlab-ci.yml, ci/build-gitlab.sh
=>  [CI] remove trusty, add hashes, add optimized builds

ci/bootstrap_boost.sh
Update src tarball URL
Make wget less chatty
=> [CI] Fix bootstrap boost

rai/core_test/block_store.cpp, rai/secure.cpp
Unchecked subdatabase allowed duplicates
https://github.com/clemahieu/raiblocks/issues/513
https://github.com/clemahieu/raiblocks/issues/522
=>  Fixing posible DB growth with unchecked blocks

docker/ci/Dockerfile
Again: Use `https://sourceforge.net` instead of `http://sourceforge.net`
=> Update CI Dockerfile

rai/node/rpc.cpp, rai/node/rpc.hpp, rai/node/wallet.cpp, rai/node/wallet.hpp
Draft watch-only accounts for large services
=> Watch only accounts

rai/core_test/network.cpp, rai/ledger.cpp, rai/node/bootstrap.cpp, rai/node/common.cpp
Also includes a test for bootstrapping ublocks.
=> Fix bootstrapping ublocks

CMakeLists.txt
gtest for windows updated to /MT and MTd
=> gtest link dll against windows

rai/core_test/wallets.cpp
update nonWalletDbs to account for utx database
=> Fix test for wallet_create_max to allow for utx database addition

docker/node/config/beta.json, rai/node/node.cpp
Specify some pre-configured representatives for the beta network
=> Specify beta network representatives

rai/node/bootstrap.cpp
I'm not sure why this is here, and it's preventing bulk_push sometimes.
=> Remove bulk_push_server receive !bootstrap.in_progress check

rai/node/bootstrap.cpp
Peer dropping seems a bit aggressive (causes a lot of connections in time_wait) - this PR adds logging to help investigate.
=> Log dropped peers if bulk pull logging is active

rai/node/node.cpp
Also fix log output where port was reported as an error code
=> Log errors in work peer client

rai/node/wallet.cpp
Check existance of up to 64 accounts from last found + extra check for large wallets
=> Increase change_seed accounts check count

rai/node/wallet.cpp
if there are more than ~~1 account~~ 4 accounts to insert
=> Disable work generation for change_seed

rai/common.cpp, rai/common.hpp
Merging in some efficiency gains for computing amount and balances of blocks.
=> Non recursive amount

docker/node/entry.sh
If the DB file gets above 20GB, stop the node, vacuum the DB, and restart.
=> Automatically vacuum database if it gets too large in the Docker container

rai/ledger.cpp, rai/node/node.cpp
If tthis is request for forked block/account representative knows about
=> Adding optional confirm_req answers

rai/node/bootstrap.cpp
Bootstrap logging messages will silence unless the appropriate logging is enabled in config.json
=> logging updates

rai/node/bootstrap.cpp
Silence Windows Specific Common Errors while bootstrapping
=> Windows Specific Logging

rai/core_test/node.cpp, rai/core_test/rpc.cpp, rai/core_test/wallet.cpp, rai/node/node.cpp, rai/node/rpc.cpp, rai/node/wallet.cpp
Also fixes a couple of work related things that should've been fixed a long time ago.
=> Fix handling of invalid wallet work

rai/node/node.cpp
https://tools.ietf.org/html/rfc1918
https://tools.ietf.org/html/rfc6598
https://tools.ietf.org/html/rfc4193
=> Removing private addresses from live network peers

rai/core_test/node.cpp, rai/node/node.cpp, rai/node/node.hpp
I accidentally messed up #860 so here we go again. Sorry @meltingice!
=> Fix typo: quorom -> quorum

rai/node/bootstrap.cpp
Add stats for outgoing bulk push. @argakiig like so?
=> Add stats for outgoing bulk push

rai/common.hpp, rai/node/rpc.cpp
Fixing changes i forgot to include prior
=> Remove canary

rai/node/node.cpp
CLI "unchecked_clear" and optional unchecked_clear for "vacuum" & "snapshot"
=> CLI unchecked_clear

rai/node/wallet.cpp
Voting for each pending block separately
=> Simplify search_pending

rai/qt/qt.cpp
=> Correct account fields in QT wallet

rai/common.cpp, rai/node/node.cpp
New genesis account created, four representatives online and ready. Preconfigured representatives present now as well.
=> Restart of Beta network

rai/blockstore.cpp
https://github.com/nanocurrency/raiblocks/issues/919
=> Add missing version_put

docker/node/config/beta.json, docker/node/config/live.json
=> Update live.json & beta.json

rai/node/node.cpp, rai/node/node.hpp
or online stake is less than required quorum
=> Confirm req to all peers if reps list is empty

rai/node/rpc.cpp
Returning balance for state blocks & previous for all blocks (except open)
https://github.com/nanocurrency/raiblocks/issues/893
=> Raw history changes

rai/core_test/block.cpp, rai/lib/blocks.cpp, rai/node/bootstrap.cpp, rai/node/common.cpp, rai/node/rpc.cpp, rai/node/rpc_secure.cpp, rai/qt_test/qt.cpp
=> Initialize booleans when not explicitly set

rai/node/rpc.cpp, rai/node/wallet.cpp
=> Fix possible wallet locked errors in RPC

appveyor.yml, ci/deploy-docker.sh
Fixed Pull Request building
Configured Build matrix for Live and Beta
Updated for MSVC 2017 build environment
=> Appveyor Fixes

.gitlab-ci.yml, ci/build-gitlab.sh
Automated Xenial Beta network build from gitlab
=> Automated Build for Beta Network

ci/deploy-docker.sh
If the tag matches RC dont tag as latest in docker (closes #1004)
=> docker latest tag not applied if regex RC matches

rai/core_test/conflicts.cpp, rai/core_test/gap_cache.cpp, rai/core_test/ledger.cpp, rai/core_test/node.cpp, rai/node/common.cpp, rai/node/common.hpp, rai/node/node.cpp, rai/node/node.hpp, rai/secure/blockstore.cpp, rai/secure/blockstore.hpp, rai/secure/common.cpp, rai/secure/common.hpp, rai/secure/ledger.cpp, rai/secure/ledger.hpp, rai/slow_test/node.cpp
Hash-only voting support, closes #987
=> Add hash only votes, which can be batched

rai/node/wallet.cpp
With running daemon V15.0, fixes #1077
=> Fix possible write transaction lock

rai/node/node.cpp
=> Ensure full blocks are not generated as part of vote-by-hash

rai/lib/utility.cpp, rai/lib/utility.hpp
=> Added start of "release_assert()"

rai/lib/numbers.cpp
=> Improve account_decode

rai/node/bootstrap.cpp, rai/node/bootstrap.hpp, rai/node/stats.cpp, rai/node/stats.hpp
=> Deprecate bulk_pull_blocks

rai/lib/errors.cpp
Thanks to @PlasmaPower for spotting this
=> Missing return statement in error_process_messages

rai/core_test/rpc.cpp
https://github.com/nanocurrency/raiblocks/issues/1121
=> Fix test rpc.payment_begin_end

rai/core_test/rpc.cpp, rai/node/rpc.cpp
=> Exclude active blocks from the pending RPC

rai/rai_node/entry.cpp
Expand CLI --debug_validate_blocks
=> Validate pending blocks

rai/rai_node/daemon.cpp, rai/rai_wallet/entry.cpp
config.json file permissions didnt allow writing to on windows, updated
=> fixed config.json file permissions

rai/node/bootstrap.cpp, rai/node/bootstrap.hpp, rai/node/common.hpp
=> Added support for PENDING_HASH_AMOUNT_AND_ADDRESS to bulk_pull_account

rai/node/cli.cpp
=> Better `--snapshot` CLI error messages

rai/core_test/network.cpp
=> Add a test for bulk_pull_account

rai/node/node.cpp
Reverts nanocurrency/raiblocks#1237
=> Revert " Escalation for long unconfirmed elections"

rai/node/node.cpp
This gives a stats breakdown of invalid, valid, replay.
=> Add vote status stats even when vote logging is off

rai/node/node.cpp
Second half of pull request #1246
=> Remove process_active from confirm_req

rai/node/rpc.cpp
=> Save DB random block read with include_active

util/changelog_generator
Improve the changelog generation script to produce higher quality output
=> Better changelog generation

rai/core_test/network.cpp, rai/core_test/processor_service.cpp, rai/core_test/rpc.cpp, rai/core_test/wallet.cpp, rai/lib/interface.cpp, rai/lib/utility.cpp, rai/lib/utility.hpp, rai/lib/work.cpp, rai/lib/work.hpp, rai/node/bootstrap.hpp, rai/node/node.cpp, rai/node/node.hpp, rai/node/wallet.hpp, rai/slow_test/node.cpp
converting to boost threads and setting 8MB worker thread stack size
=> std::thread to boost::thread

rai/core_test/rpc.cpp, rai/node/rpc.cpp
Include Protocol Version in rpc version response closing #1189
=> Enhance version rpc

appveyor.yml, rai/node/node.cpp
=> Fix MSVC linker error using rai_bootstrap_weights

rai/core_test/block.cpp, rai/core_test/conflicts.cpp, rai/core_test/message.cpp, rai/core_test/message_parser.cpp, rai/core_test/network.cpp, rai/core_test/node.cpp, rai/lib/blocks.cpp, rai/lib/blocks.hpp, rai/node/bootstrap.cpp, rai/node/bootstrap.hpp, rai/node/common.cpp, rai/node/common.hpp, rai/node/lmdb.cpp, rai/node/lmdb.hpp, rai/node/node.cpp, rai/node/node.hpp, rai/node/rpc.cpp, rai/rai_node/entry.cpp, rai/secure/blockstore.hpp, rai/secure/common.cpp, rai/secure/common.hpp, rai/secure/ledger.cpp, rai/secure/ledger.hpp
Unique blocks and votes together to minimize memory usage.
=> Block uniquer

rai/node/node.cpp
The "also_publish" flag was added in #1335 and was not used.  This changeset uses it.
=> Actually use also_publish flag

rai/node/node.cpp
Log vote processing time so we can tell how many votes are coming in without the spam of logging every vote
=> Log vote processing time

rai/core_test/node.cpp, rai/node/node.cpp, rai/node/node.hpp
The base branch for this is releases/v16 because this is targeting a V16.3.
=> Replay votes in response to a confirm_req for an active block

rai/node/node.cpp
If there are more than 256 * 1024 new unprocessed votes
=> Add vote_processor overflow mode

rai/core_test/message.cpp, rai/node/common.cpp, rai/node/common.hpp, rai/node/node.cpp
=> Message header extensions: remove unused flags

rai/node/node.cpp, rai/node/stats.cpp, rai/node/stats.hpp
Since vote logging is typically off
=> Add vote overflow stats

rai/node/CMakeLists.txt
...so it shows up in IDE navigation, etc.
=> Add missing header

rai/node/bootstrap.cpp
Also needs cherry-picked to v17
=> Fix iteration in rai::bootstrap_attempt::lazy_finished

rai/node/bootstrap.cpp, rai/node/node.cpp, rai/node/stats.cpp, rai/node/stats.hpp
=> Differentiate between lazy and non-lazy bootstrap in stats

rai/core_test/network.cpp, rai/node/bootstrap.cpp, rai/node/bootstrap.hpp, rai/node/common.cpp, rai/node/common.hpp
=> Extend "bulk_pull" to have a count parameter

rai/node/node.cpp
=> Fixed issue with incorrect timing computation

rai/node/bootstrap.cpp
During a bootstrap client attempt there are very likely very few blocks in the ledger.
Do not accept a bulk_push towards our bootstrap server while this is on-going because, if the blocks are properly ordered, it can lead to a lot of elections.
=> Do not accept incoming bulk_push requests while bootstrapping

rai/node/node.cpp, rai/node/node.hpp
Additionally decreasing broadcast_interval_ms for live/beta networks
=>  Add max_broadcast_queue for rai::active_transactions

rai/node/node.cpp
Vote processor is a customer of active transactions which is stopped first, thus clearing roots without a lock.
=> Shutdown segfault fix

rai/node/bootstrap.cpp
=> Fix initialization order

.gitmodules
Clean up .gitmodules as Beast is no longer a separate submodule (it is part of boost)
=> Remove beast from .gitmodules

rai/node/node.cpp, rai/node/node.hpp, rai/rai_node/entry.cpp
To emulate live/beta network processing performance
https://github.com/nanocurrency/raiblocks/pull/1492
=> CLI --debug_profile_bootstrap

nano/lib/blocks.hpp
Closes https://github.com/nanocurrency/raiblocks/issues/375
=> Block size computation improvement

.github/ISSUE_TEMPLATE.md, CMakeLists.txt, README.md, util/changelog_generator, util/makesrc
Notably this does not include the link to Travis CI yet
Part of #1305
=> Rename all links to our GitHub repo

nano/lib/interface.h
They will be replaced with a new planned API soon
=> Deprecate all existing API calls

nano/core_test/gap_cache.cpp, nano/node/node.cpp, nano/node/node.hpp, nano/node/rpc.cpp
…y receive which made their names inaccurate.
=> Renaming block_processor::process_x functions.

nano/core_test/rpc.cpp, nano/node/node.cpp, nano/node/rpc.cpp, nano/node/rpc.hpp, nano/secure/blockstore.cpp
Disable sideband account & height for open blocks
Add sideband information to RPC blocks_info & block(_info)
Add local timestamp to RPC account_history
=> Sideband RPC & open blocks adjustment

nano/node/rpc.cpp
=> Improve RPC shutdown

nano/node/node.cpp
Missed in https://github.com/nanocurrency/nano-node/pull/956
=> Restore blocks_hashes.insert

nano/node/node.cpp, nano/node/node.hpp
To prevent stack overflow on some platforms
=> Limit recursive confirm_back ()

nano/core_test/node.cpp
To check PR https://github.com/nanocurrency/nano-node/pull/1581
=> Test node.block_processor_reject_rolled_back

nano/core_test/gap_cache.cpp, nano/core_test/network.cpp, nano/nano_node/entry.cpp, nano/nano_wallet/entry.cpp, nano/node/bootstrap.cpp, nano/node/bootstrap.hpp, nano/node/node.cpp, nano/node/node.hpp, nano/node/nodeconfig.cpp, nano/node/nodeconfig.hpp, nano/node/rpc.cpp, nano/node/stats.cpp, nano/node/stats.hpp
https://github.com/nanocurrency/nano-node/issues/1516
=> Priority lazy bootstrap for wallet accounts

nano/node/bootstrap.cpp
to lazy_pull_flush (), lazy request_pull () & fallback to lazy bootstrap
=> Add existing blocks check for lazy bootstrap pulls

nano/core_test/rpc.cpp, nano/node/rpc.cpp, nano/node/wallet.cpp, nano/node/wallet.hpp
for "send", "receive", "account_representative_set"
Affecting https://github.com/nanocurrency/nano-node/issues/1181
=>  Improve provided "work" for RPC

CMakeLists.txt, appveyor.yml, nano/nano_wallet/entry_com.cpp
Fix for https://github.com/nanocurrency/nano-node/issues/84
=> Make nano_wallet for Windows console

nano/node/node.cpp, nano/node/node.hpp
=> Add alarm operations to memory stats RPC

appveyor.yml
Fixes #575 
in repo branch of #1697 needed to access secure variables
=> Sign windows

CMakeLists.txt
=> Exclude miniupnpc install ()

nano/node/ipc.cpp
Thanks to dotcom for finding this
=> ipc: Handle rpc actions doing async ops

nano/node/rpc_secure.cpp
See: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=67274
=> Fix uses of lambdas on GCC < 7.1.0

.github/ISSUE_TEMPLATE.md
Changing the details around the bug bounty in the Github issue template.
=> Update github issue template bug bounty info

docker/node/Dockerfile, docker/node/entry.sh
move data_path for docker to prevent resync of ledger
add symlink for legacy support to docker
=> check for legacy directory

nano/lib/numbers.hpp, nano/qt/qt.cpp, nano/qt/qt.hpp
Useful during debugging, for copying and plugging amounts into json requests, etc.
=> Raw support in Qt wallet

nano/core_test/rpc.cpp, nano/node/rpc.cpp
https://github.com/nanocurrency/nano-node/issues/1717
Also returns restored count
=>  Return last account restored in RPC wallet_change_seed

nano/node/cli.cpp
Supported in wallet_change_seed & wallet_create
Following https://github.com/nanocurrency/nano-node/issues/793
=> Add "seed" option to CLI

nano/core_test/work_pool.cpp, nano/lib/work.cpp, nano/lib/work.hpp, nano/nano_node/daemon.cpp, nano/nano_node/entry.cpp, nano/nano_wallet/entry.cpp, nano/node/openclwork.cpp, nano/node/openclwork.hpp
https://github.com/nanocurrency/nano-node/issues/1749
=> Support difficulty for OpenCL generate_work ()

CMakeLists.txt, appveyor.yml, docker/ci/Dockerfile, util/build_prep/bootstrap_boost.sh, util/build_prep/centos/prep.sh.in, util/build_prep/macosx/prep.sh.in, util/build_prep/ubuntu/prep.sh.in
Update Boost minimum in CI tooling to 1.67
Update required module for boost to 1.67 in CMake
=> Set CI boost min/default to 1.67

nano/node/rpc.cpp
RPC "account_representative_set", "receive"
To fix rare issue https://github.com/nanocurrency/nano-node/issues/1778
=> Return error message for failed async RPC actions

nano/slow_test/node.cpp
send_action is not used directly anywhere in node or QT wallet
=> Make wallet.multithreaded_send slow test async

nano/node/bootstrap.cpp
Follow-up to https://github.com/nanocurrency/nano-node/pull/1386
=> Use to_bytes in bootstrap as well

nano/core_test/rpc.cpp, nano/node/rpc.cpp
Following https://github.com/nanocurrency/nano-node/pull/1798
=> Add optional difficulty in RPC "work_validate"

nano/node/rpc.cpp, nano/node/wallet.cpp, nano/qt/qt.cpp
Extra logging for:
* wallet unlock
* invalid password attempt
* wallet lock
* changing password
=> Log wallet lock/unlock

nano/core_test/network.cpp, nano/core_test/node.cpp, nano/node/bootstrap.cpp, nano/node/bootstrap.hpp, nano/node/nodeconfig.cpp, nano/node/nodeconfig.hpp
=> Add TCP server timeout

nano/node/peers.cpp, nano/secure/common.hpp
=> Remove node_id_version

nano/core_test/block.cpp, nano/lib/blockbuilders.cpp, nano/lib/blockbuilders.hpp
@argakiig could you see if this simplifies the block builder use in update_work_action?
=> Add copying operation to block builder

nano/lib/blockbuilders.cpp
when creating state_block_builder from block set build flags when fields are updated;
=> build.state().from() set build flags

nano/node/transport/udp.cpp
=> Remove strand assert

nano/core_test/interface.cpp, nano/core_test/uint256_union.cpp, nano/core_test/wallet.cpp, nano/lib/numbers.cpp
This is based on #1521 from @rkeene see that for more info.
=> Emit "nano_" prefixed addresses

nano/core_test/websocket.cpp, nano/node/websocket.cpp, nano/node/websocket.hpp
Closes #1914 
Compiles/passes on 1.69/1.70 on macOS. Could you see if this fixes your Linux build @SergiySW ?
=> Support Boost v.1.70

nano/core_test/conflicts.cpp, nano/node/active_transactions.cpp
Add deadlines
Add could_fit_delay for removing active transactions (1 for live/beta network same to previous, 10 for test network for slow tests)
=> Update conflicts.adjusted_difficulty test

nano/core_test/node.cpp, nano/core_test/websocket.cpp, nano/lib/numbers.cpp, nano/lib/work.cpp, nano/node/bootstrap.cpp, nano/node/logging.cpp, nano/node/node.cpp, nano/node/nodeconfig.cpp, nano/node/transport/udp.cpp, nano/node/websocket.cpp, nano/rpc_test/rpc.cpp, nano/slow_test/node.cpp
Some more warnings have been introduced on our end
=> Fix our warnings

nano/core_test/websocket.cpp
Thanks @guilhermelawless for the help debugging this
=> Fix some websocket test issues

nano/node/wallet.cpp
update election winner and blocks when re-working
=> updating work_watcher::run

nano/node/node.cpp, nano/node/transport/udp.cpp
Error in PR https://github.com/nanocurrency/nano-node/pull/1971
=> Fix UDP channels insert

nano/node/network.cpp, nano/node/network.hpp, nano/node/transport/udp.hpp
I'm on the latest clang-format available on brew, and it disagrees with master. Let's see what CI thinks.
=> Include ordering fix

nano/load_test/entry.cpp
Noticed this when building master on Ubuntu with Boost 1.70. Boost 1.70 has some breaking changes, and this is a workaround for supporting 1.6x as well.
=> Support for boost 1.70 in load tester

nano/node/transport/tcp.cpp, nano/secure/common.cpp, nano/secure/common.hpp
=> Add node_constants half_period

nano/core_test/ledger.cpp, nano/core_test/node.cpp
Changes from branch: work now required, uint512 -> qualified_root.
Updated with epoch_conflict_confirm from @SergiySW
=> Ledger tests related to epoch conflicts

nano/lib/stats.cpp, nano/lib/stats.hpp, nano/node/socket.cpp, nano/node/socket.hpp
=> Limit socket queue_size

nano/core_test/websocket.cpp, nano/nano_rpc/entry.cpp, nano/node/daemonconfig.cpp, nano/node/election.cpp, nano/node/logging.cpp, nano/node/node.cpp
Unused and uninitialized variables and wrong c'tor initializer ordering.
=> Fix assorted compiler warnings

nano/node/bootstrap.cpp
Master formatting disagrees with mine and wez's, might need formatting guards if other's get issues after this PR
=> Formatting issues on master

nano/core_test/block_store.cpp, nano/nano_node/entry.cpp, nano/node/json_handler.cpp, nano/node/lmdb.cpp, nano/node/lmdb.hpp, nano/node/testing.cpp, nano/rpc/rpc_handler.cpp, nano/rpc/rpc_handler.hpp, nano/rpc_test/rpc.cpp, nano/secure/blockstore.hpp
=> Add optional cemented count to block_count RPC command

nano/rpc_test/rpc.cpp
Closes https://github.com/nanocurrency/nano-node/issues/2101
Thanks to @guilhermelawless for validating the trend-sequence fix
=> Fix locking issue and intermittent failure in rpc.active_difficulty

nano/core_test/node.cpp, nano/nano_node/entry.cpp, nano/node/bootstrap.cpp, nano/node/network.cpp, nano/node/nodeconfig.hpp, nano/node/testing.cpp, nano/node/transport/tcp.cpp
=> Flag to disable TCP realtime network

nano/core_test/active_transactions.cpp, nano/core_test/block_store.cpp, nano/core_test/network.cpp, nano/core_test/node.cpp
Some assorted issues found during sanitizer runs
=> Fix intermittent test issue and cleanup unused vars

nano/node/active_transactions.cpp
Considering much more aggressive dropping of active transactions after https://github.com/nanocurrency/nano-node/pull/2116
=> Send confirm_req each request_confirm loop

nano/node/active_transactions.cpp
Using the new `active_elections_size` config option (well half this number) as a maximum number of frontiers to request elections to set the confirmation height for
=> More aggressive setting confirmation height of frontiers during low tps

nano/core_test/active_transactions.cpp
test explains what assert triggers if 2116 was reverted
=> test validating #2116

util/build_prep/bootstrap_boost.sh
URL for boost source updated to valid one
added boost 1.70 to bootstrap script
=> fix boost downloads

nano/node/active_transactions.cpp, nano/node/json_handler.cpp, nano/rpc_test/rpc.cpp
Unrelated: shadowed local variable in `active_transactions.cpp`
=> RPC version network label and identifier

nano/node/json_handler.cpp
#2151 
On OSX due to a shadowed variable
=> Fix building error caused by #2151

nano/rpc_test/rpc.cpp
Error in https://github.com/nanocurrency/nano-node/pull/2191
=> Fix rpc.node_id test

nano/rpc_test/rpc.cpp, nano/secure/blockstore_partial.hpp
Also fixes `release_assert` for the confirmation height database.
=> Add test for retrieving non-existing account

nano/core_test/toml.cpp, nano/lib/rpcconfig.cpp, nano/node/websocketconfig.cpp
When some categories were found it had required options.
=> No required options in TOML parsing

nano/qt/qt.cpp
qt wallet on master doesn't work in debug mode as any write tx on io threads will assert now.
=> Post to worker thread in qt wallet when doing write tx's on io threads

nano/node/wallet.cpp
Was only using local work generation
=> Use distributed work in work watcher

nano/core_test/active_transactions.cpp, nano/node/blockprocessor.cpp, nano/node/blockprocessor.hpp
due to verify_state_blocks () old blocks filter
=> Fix active transactions difficulty update for state blocks

nano/nano_wallet/entry.cpp
Add the config override option to dev wallet as well, same as node and rpc.
Example, `nano_wallet --config node.rocksdb.enable=true`
=> Support --config option in Qt wallet

nano/lib/tomlconfig.hpp
=> Don't comment toml tables in generate_config

nano/node/node.cpp, nano/node/repcrawler.cpp, nano/node/repcrawler.hpp
Also update probable rep with response only if channel was changed
=> Periodic rep crawler weights update

nano/nano_node/entry.cpp
```bash
./nano_node --debug_profile_validate
Starting validation profile
Average validation time: 184 ns (5414818 validations/s)
```
=> Profile work validation

nano/node/wallet.cpp
Might be good diagnostics info for services with large wallets/lots of accounts
=> Object stats for work watcher container

nano/node/json_handler.cpp, nano/rpc_test/rpc.cpp
And RPC tests for `unchecked`, `unchecked_get`
=> RPC unchecked json_block option

.travis.yml
Follows https://github.com/nanocurrency/nano-node/pull/2344
=> Update travis beta-osx job with cached qt

nano/lib/diagnosticsconfig.cpp, nano/lib/rocksdbconfig.cpp, nano/lib/rpcconfig.cpp, nano/lib/stats.cpp, nano/node/cli.cpp, nano/node/ipcconfig.cpp, nano/node/logging.cpp, nano/node/node_pow_server_config.cpp, nano/node/node_rpc_config.cpp, nano/node/nodeconfig.cpp, nano/node/websocketconfig.cpp
- Add message at the top of the file with usage information and warning against uncommenting all fields (toml label added because of this change)
- Add warnings for select fields which may impact performance substantially
- Format all fields for consistency
- Add IPC config documentation
- Other small misc improvements
=> Improve sample configuration file

nano/nano_node/entry.cpp, nano/nano_wallet/entry.cpp, nano/node/cli.cpp, nano/node/cli.hpp
show help in messagebox linking docs launch flags with detail text being the help output
support launch flags being passed through nano_wallet like nano_node does
=> Add support for launch flags passed to nano_wallet

README.md
Current layout:
[![Build Status](https://travis-ci.org/nanocurrency/nano-node.svg?branch=master)](https://travis-ci.org/nanocurrency/nano-node) [![Build status](https://ci.appveyor.com/api/projects/status/q66rbt2ux6apjj03/branch/master?svg=true)](https://ci.appveyor.com/project/argakiig/raiblocks/branch/master)
New:
[![Build Status](https://travis-ci.org/nanocurrency/nano-node.svg?branch=master)](https://travis-ci.org/nanocurrency/nano-node) [![Build status](https://ci.appveyor.com/api/projects/status/q66rbt2ux6apjj03/branch/master?svg=true)](https://ci.appveyor.com/project/argakiig/raiblocks/branch/master) ![GitHub release (latest by date)](https://img.shields.io/github/v/release/nanocurrency/nano-node) ![GitHub tag (latest by date)](https://img.shields.io/github/v/tag/nanocurrency/nano-n …
=> Latest release, latest tag and discord badges

nano/node/bootstrap/bootstrap.cpp
Best reviewed without whitespace changes.
Thanks to sev for the detailed report.
=> Fix early return preventing mutex lock in attempt_restart_check

nano/node/socket.cpp
Fail with an error if buffer is too small
=> Socket buffer size error code

nano/core_test/node.cpp, nano/node/blockprocessor.cpp, nano/node/blockprocessor.hpp, nano/node/node.cpp
- Remove rolled back blocks list
- Don't stop initial rollback election
=> Remove rolled back blocks list

ci/actions/windows/build.ps1
=> update vc_redist url

nano/fuzzer_test/CMakeLists.txt, nano/fuzzer_test/fuzz_bignum.cpp, nano/fuzzer_test/fuzz_endpoint_parsing.cpp
=> Fuzz account, hex, dec and endpoint parsing

nano/lib/config.hpp
=> Define GCC sanitizers builds

nano/core_test/node.cpp, nano/node/active_transactions.cpp, nano/node/election.cpp, nano/node/election.hpp, nano/node/json_handler.cpp
=> Encapsulating election::confirmed so its implementation can vary.

CMakeLists.txt
short explainations of policies being set
=> guard policy setting by version checks

nano/node/blockprocessor.cpp
Removed in https://github.com/nanocurrency/nano-node/pull/2279
=> Restore max block processor signature verification batch size

nano/nano_node/entry.cpp
* fix blocks signatures
* support daemon launch options for profiling
* use block count cache
=> Update --debug_profile_process CLI test

nano/nano_node/entry.cpp
* improve flags for inactive node
* support daemon launch options for profiling
* count us for BPS ration
=>  Update --debug_profile_bootstrap CLI test

nano/core_test/confirmation_height.cpp
Thanks to @cryptocode for finding this on MacOS and producing the gist containing the stacktraces from TSAN:
https://gist.github.com/cryptocode/770c05c9fce360dae9f34b3b03954842
`observer_order` in the test was not protected.
=> [TSAN] confirmation_height.cemented_gap_below_receive test

nano/node/election.cpp
Out of https://github.com/nanocurrency/nano-node/pull/2440
=> Remove vote cache & generate new vote if election winner is changed

nano/core_test/confirmation_height.cpp
=> Reworking confirmation_height.dependent_election test

nano/node/active_transactions.cpp, nano/node/active_transactions.hpp, nano/node/cli.cpp, nano/node/nodeconfig.hpp
=> Configurable inactive votes cache size

nano/node/nodeconfig.cpp
Noticed by nox/srayman. We can consider adding port support in a future pr.
=> Update preconfigured_peers comment regarding port

ci/actions/windows/install_deps.ps1
Move qt for windows assets to s3 for permanent asset storage
=> Host qt assets on s3

ci/actions/deploy.sh, ci/actions/windows/build.ps1, ci/actions/windows/deploy.ps1
extra whitespace changes in powershell scripts
=> gather sha256 hashes of artifacts and upload to s3 with artifacts

ci/actions/deploy.sh, ci/actions/windows/deploy.ps1
write out sum on nix to directory we have write permission on
=> typo on windows sha256 Out-File

nano/node/active_transactions.cpp
Modify inactive cache conditions to prevent multiple insertions for confirmed entries
Thank @guilhermelawless !
=> Modify inactive cache to prevent multiple insertions for confirmed

nano/core_test/wallet.cpp
This was due to sometimes the blocks having difficulty larger than `limited_active_difficulty` (min between trended_active_difficulty and `config.max_work_generate_difficulty`). Forcing the config value to a high value and the trend to immediately above the highest difficulty between the blocks is sufficient.
=> Fix intermittent wallet.work_watcher_update failure

nano/core_test/node.cpp, nano/node/node.cpp, nano/node/node.hpp, nano/node/testing.cpp, nano/node/testing.hpp, nano/secure/ledger.cpp, nano/secure/ledger.hpp
=> Add node sequence for tests

nano/core_test/active_transactions.cpp, nano/node/active_transactions.cpp, nano/node/active_transactions.hpp, nano/node/election.cpp, nano/node/election.hpp, nano/node/voting.cpp, nano/node/voting.hpp
Restoring removed in PR https://github.com/nanocurrency/nano-node/pull/2688
=> Vote generator session for batch insertions

nano/node/confirmation_height_unbounded.cpp
Note: Review without viewing whitespace changes.
Currently all uncemented blocks in a single account (and associated source account if relevant) are cemented, however for single block per account transactions this means we will be writing 1-2 blocks each time which will be quite slow. Instead batch up all the writes, I'm not adding the extra complexity involved in checking if number of writes is `> batch_write_size` as the unbounded processor should not be dealing with many blocks (4096 usually), but some spillage over the max is possible, but is not be a problem.
Batching is done in the bounded conf height processor already so that can be used to assist review already if necessary. Another PR will be made to better handle the write database queue during intermittent write commits, which …
=> Improve batching of writes in unbounded conf height processor

nano/nano_node/entry.cpp
Also improves the start message. Example for --debug_opencl
> Starting OpenCL generation profiling. Platform: 0. Device: 0. Threads: 1048576. Difficulty: 0xfffffff800000000 (1.0000x from base difficulty 0xfffffff800000000)
=> Add difficulty and multiplier to CLI work generation commands

util/changelog.py
mapping between sections and labels handled in SECTIONS
Other added as a catchall if there are no matching labels
sample markdown output
=> changelog_generator refactored as changelog.py

nano/core_test/active_transactions.cpp, nano/node/repcrawler.cpp
Because it's done in request loop quite frequent
=> Remove confirmation requests for a new representative

nano/nano_node/daemon.cpp, nano/node/node_pow_server_config.cpp
- additionally disable possible nano_pow_server launch in daemon (not used)
=> Clarify nano_pow_server configs are not in use

nano/core_test/active_transactions.cpp, nano/lib/stats.cpp, nano/lib/stats.hpp, nano/node/active_transactions.cpp, nano/node/active_transactions.hpp
- election_non_priority
- election_priority
- election_block_conflict
- election_difficulty_update
- election_drop
- election_restart
Ensured correct behavior in core_test
=> New stats for elections

nano/rpc_test/rpc.cpp
This test has the comment `// If this test fails, try increasing the num_blocks size.` which implies that it can fail under some circumstances, as it relies on the confirmation height processor not processing blocks faster than querying via the RPC. This isn't always the case, so using the `write_database_queue` to be sure it can't finish before being queried.
=> Fix intermittently failing rpc.confirmation_height_currently_processing test

nano/core_test/node_telemetry.cpp
The issue was just because the channel is erased from the network **after** added to the exclusion peers list, so there was a small window where it wouldn't be removed. Making the network size checks be done first in a small loop and then check peer exclusion list after.
=> Fix intermittent node_telemetry.remove_peer_different_genesis test

nano/core_test/conflicts.cpp
The issue is that the work difficulty can be higher for the `send5` block. This was added in https://github.com/nanocurrency/nano-node/pull/2673 and I think is sufficient to just move it with the other block additions at the start (as per the comment about independent elections in the test). 200 iterations of the test saw no failures.
=> Fix intermittently failing conflicts.adjusted_multiplier test

nano/node/active_transactions.cpp
=> Fix previous balance in active_transaction::insert ()

util/changelog.py
url to generate PAT's included in script
highlight caveat about branch tip releases and how to work around them
=> update changelog logic
